crates/json-rpc/src/response/error.rs
crates/json-rpc/src/response/mod.rs
crates/json-rpc/src/response/payload.rs

- Adds shortcut methods to instantiate response errors
- Adds `serialize_payload` to the response objects to allow easy converting to the default `Response`
**This is a breaking change, as it changes the ErrorPayload message to a Cow**. However, it doesn't break anything in the library/

feat: errors for responses

---

crates/consensus/src/header.rs
crates/network-primitives/src/traits.rs
crates/provider/src/ext/anvil.rs
crates/provider/src/provider/trait.rs
crates/rpc-types-eth/src/block.rs

Related https://github.com/alloy-rs/alloy/issues/1241

consensus: make `Header` `base_fee_per_gas` u64

---

crates/consensus/src/header.rs
crates/eips/src/eip4844/mod.rs
crates/provider/src/fillers/gas.rs
crates/rpc-types-eth/src/block.rs

Should close https://github.com/alloy-rs/alloy/issues/1241

consensus: make `Header` blob fees u64

---

crates/signer-local/Cargo.toml
crates/signer-local/src/private_key.rs

Add `keystore-geth-compat` feature for `signer-local` crate, in order to enable the serialization of the `address` field in the keystore file.
Close #1376 .
Add `keystore-geth-compat` feature, which requires the `keystore` one to be enabled, in the `Cargo.toml` file.

feat(signer-local): add `keystore-geth-compat` feature

---

crates/rpc-types-engine/src/identification.rs

I made a PR which was approved on https://github.com/ethereum/execution-apis/pull/590 to add Trin Execution's Client Code.
I would like to use the `ClientCode` type, which would entail adding Trin Execution's ClientCode. I can always roll my own type, but I thought it would be best to use alloy as we already migrated to `alloy-privatives`/`alloy-rlp` instead of `open-ethereum` alternatives
Add Trin Execution's client code

feat(engine): Add Trin Execution client code

---

crates/contract/Cargo.toml
crates/contract/src/interface.rs
crates/json-rpc/Cargo.toml
crates/json-rpc/src/packet.rs
crates/network/Cargo.toml
crates/network/src/ethereum/wallet.rs
crates/provider/src/heart.rs
crates/pubsub/src/managers/req.rs
crates/rpc-client/Cargo.toml
crates/rpc-client/src/batch.rs
crates/rpc-client/src/builtin.rs
crates/rpc-types-debug/Cargo.toml
crates/rpc-types-debug/src/debug.rs
crates/rpc-types-engine/src/jwt.rs
crates/rpc-types-engine/src/lib.rs
crates/rpc-types-eth/Cargo.toml
crates/rpc-types-eth/src/erc4337.rs
crates/rpc-types-eth/src/filter.rs
crates/rpc-types-eth/src/lib.rs
crates/rpc-types-eth/src/state.rs
crates/rpc-types-trace/src/filter.rs
crates/rpc-types-trace/src/geth/mux.rs
crates/rpc-types-trace/src/tracerequest.rs
crates/rpc-types/Cargo.toml
crates/rpc-types/src/rpc.rs
crates/serde/src/other/arbitrary_.rs
crates/serde/src/storage.rs
crates/signer-local/Cargo.toml

Supersedes https://github.com/alloy-rs/alloy/pull/1368
Closes #1365

feat: replace std/hashbrown with alloy_primitives::map

---

crates/provider/Cargo.toml
crates/provider/src/fillers/gas.rs

Closes: https://github.com/alloy-rs/alloy/issues/1371
Related Foundry PR: https://github.com/foundry-rs/foundry/pull/8963 that depends on this implementation
If `max_fee_per_blob_gas` is `Some(0)` or `None` we set it to a valid value `next_block_blob_fee()`.

fix: ensure `max_fee_per_blob_gas` field handles `Some(0)` gracefully

---

crates/eips/src/eip1898.rs

unlike the serde deserialize the from_str did not support u64

fix: support u64 hex from str for BlockId

---

crates/consensus/Cargo.toml
crates/consensus/src/receipt/mod.rs

Ease of usage of trait, especially in function signatures that return opaque type.
Auto-impl `alloy_consensus::TxReceipt` for `&` and `Arc`

Auto-impl `alloy_consensus::TxReceipt` for ref

---

crates/consensus/src/receipt/any.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs

Enable conversion from bool to `Eip658Value` in `TxReceipt::status_or_post_state` trait method body
Changes signature `TxReceipt::status_or_post_state` from returning ref to `Eip658Value`, to returning static type

Return static `Eip658Value` from `TxReceipt` trait method

---

crates/eips/src/eip1559/helpers.rs

reverts back to #83 using safe u128

fix: safe match for next base fee

---

crates/consensus/src/header.rs
crates/consensus/src/lib.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/legacy.rs

A small cleanup after https://github.com/alloy-rs/alloy/pull/1397. Changing the field names is non-breaking because bincode doesn't store any metadata for fields, including their names.

chore(consensus): less derives for bincode compatible types

---

Cargo.toml
crates/consensus/Cargo.toml
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/mod.rs
crates/eips/Cargo.toml

https://github.com/alloy-rs/alloy/issues/1349
Built on top of https://github.com/alloy-rs/eips/pull/8

feat(consensus): bincode compatibility for EIP-7702

---

crates/consensus/src/block.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/typed.rs
crates/rpc-types-eth/src/block.rs

this reorders all impls so that it matches the trait

chore: apply same member order

---

crates/eips/src/eip1898.rs

this is convenient for functions that accept a ref hash and need to convert that

feat: add helper from impl

---

crates/rpc-types-mev/src/mev_calls.rs

According to [mev-share specs](https://github.com/flashbots/mev-share/blob/main/specs/bundles/v0.1.md#bundle-composition) there should be support for nested bundles inside the bundle request, but in mev_calls.rs, `BundleItem` did not have `Bundle`. This was found during implementation of `mev_simBundle` on reth ([comment](https://github.com/paradigmxyz/reth/issues/9472#issuecomment-2388573965))
fixes #1416 
also ref: https://github.com/paradigmxyz/mev-share-rs/issues/44
Added support for `Bundle` inside `BundleItem`, and added a test to check if a nested bundle request can be deserialized.

feat(rpc-types-mev): Add support for `Bundle` inside `BundleItem`

---

Cargo.toml
crates/provider/Cargo.toml
crates/provider/src/heart.rs
crates/transport-ws/Cargo.toml
crates/transport-ws/src/native.rs
crates/transport/Cargo.toml
crates/transport/src/layers/retry.rs

The `std::time` library is mostly not supported on the wasm32 target.
For this reason, we switch out some of these calls to use the crate
`wasmtimer`.
My first pull request. I was in a bit of a hurry to make this PR, I will allocate more time tomorrow or next week.
@DaniPopes, let me know if there's anything I can do to ease merging this PR. We'll probably want to test this internally first, when we've upgraded to version `0.4`.

fix(provider): use wasmtimer for wasm32 target

---

crates/consensus/src/transaction/legacy.rs

We are currently producing incorrect rlp for non-eip155 legacy transactions

fix: enforce correct parity for legacy transactions

---

crates/eips/Cargo.toml
crates/eips/src/eip1559/basefee.rs

Adds [`arbitrary::Arbitrary`](https://docs.rs/arbitrary/latest/arbitrary/trait.Arbitrary.html) support for `alloy-eips` `BaseFeeParams`.

feat(eips): Arbitrary BaseFeeParams

---

crates/rpc-types-trace/src/geth/mod.rs

closes #1347
the options are a bit weird, and maybe we shouldn't have designed the options like this, because this was designed from server POV.
this adds helpers to not mess up config.
apparently tracer arg is required, but I don't even khow to trigger the default structlogs tracer because this doesn't have a name afaik

feat: add helpers to configure GethDebugTracingOptions properly

---

crates/rpc-client/Cargo.toml
crates/rpc-client/src/poller.rs

A follow up to PR #1426. A Tokio `sleep` is called, leading to a
runtime error on WASM targets.
@DaniPopes, upon trying to use the `main` with the last PR in, I got another error which is fixed in this PR.

fix(rpc-client): use wasm-compatible sleep

---

crates/eips/src/eip4844/sidecar.rs

Fixes `BlobTransactionSidecarItem` serialization which previously would [panic with](https://github.com/anton-rs/kona/actions/runs/11202556451/job/31138815038?pr=638) `invalid type: string \"0\", expected usize`.

fix(eips): Blob Sidecar Item Serde

---

crates/rpc-types-beacon/src/events/mod.rs

`proposer_index` is not "The execution block number of the parent block".

fix: proposer_index rustdoc

---

crates/genesis/src/lib.rs

Should close https://github.com/alloy-rs/alloy/issues/1445

GenesisAccount : implement `deserialize_private_key`

---

crates/rpc-types-eth/src/transaction/request.rs

Make the builder error generic over the builder for reuse during network implementation

feat: BuildTransactionErr abstract over builder type

---

crates/provider/src/fillers/nonce.rs

imo we should use pending here so that the this doesn't pick an already pending nonce in the pool.
@klkvr not exactly sure how this impacts things like
https://github.com/foundry-rs/foundry/pull/9096

chore: use pending for next initial nonce

---

crates/provider/src/fillers/mod.rs

Makes `RecommendedFillers` generic over `Network`.
Associated type in the trait requires `TxFiller`, which is generic over `Network`; it just has `Ethereum` as default.
So it's impossible to implement custom fillers for a specific network, if they can't be implemented for `Ethereum` as well.
The solution is a bit awkward since now you can implement `RecommendedFillers<NetworkA>` and `RecommendedFillers<NetworkB>` for `NetworkA`, but the pro is that it's not a breaking change.
The alternative would be to introduce an associated type, but it would be breaking, since associated type defaults are unstable.
Make `RecommendedFillers` generic over `Network` 😅 .

fix: Make RecommendedFillers generic over Network

---

crates/provider/src/builder.rs
crates/provider/src/fillers/mod.rs

Follow-up from #1458
@klkvr proposed a better way to handle network bound.
There is a small downside: if someone has implemented `RecommendedFillers` for some type that doesn't implement `Network`, this change is breaking. The likelihood of that is very slow though, so probably it's fine.

fix: Change bound in RecommendedFillers to TxFiller<Self>

---

crates/node-bindings/src/nodes/geth.rs
crates/node-bindings/src/nodes/reth.rs

I see most places use Option<&T>,  I think maybe Option<&T> is better than &Option<T>. If it's not, please close it.

chore: unify use Option ref

---

crates/rpc-types-trace/src/filter.rs

fix(types/filter): treat empty filter address as non-matching 

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs
crates/network-primitives/src/traits.rs
crates/rpc-types-eth/src/transaction/mod.rs
crates/signer-trezor/src/signer.rs

`to` naming convention can be confusing because we already have a `to` function in most implementations and this `to` function designates the receiving address while here we are going to get the kind of the transaction.
For example here it could be really confusing with potential double `to().to()` to catch the final address:
https://github.com/paradigmxyz/reth/blob/c4d7b591834055bdf3afed96b696e0a2cef0f383/crates/primitives/src/transaction/mod.rs#L226-L247

consensus: replace `to` by `kind` in Transaction trait

---

crates/consensus/src/receipt/any.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs

Small step toward https://github.com/paradigmxyz/reth/pull/11643#discussion_r1797592811

consensus: add more constraints to `TxReceipt` trait

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs
crates/rpc-types-eth/src/transaction/mod.rs

Split off from #1460 and #1169 
Change output type of `input` to `Bytes` to allow cheaper cloning by downstream users

refactor: change input output to Bytes

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/legacy.rs

Split off from #1460 
Transaction JSON names this field `gas`

fix: rename gas_limit to gas in serde def for txns

---

crates/rpc-types-txpool/src/txpool.rs

split from #1460 
Current impls bound `T` to default, which is unintnentional
Manually impl with no bound

fix: correct default impls to not bound T

---

crates/consensus/src/transaction/envelope.rs

Split off from #1460 
Currently deser fails when the type tag is missing. This is a problem in some RPC impls
Allow deser of legacy transactions when type tag is missing

fix: allow missing-tag deser of tx envelope

---

crates/provider/src/provider/trait.rs

feat: add missing eth_getTransaction methods

---

crates/contract/src/call.rs
crates/provider/src/fillers/mod.rs
crates/provider/src/heart.rs
crates/provider/src/provider/trait.rs

RootProvider is an arc, this should just be cloned into the pendingtransactionbuilder
https://github.com/alloy-rs/alloy/blob/4c32ff922e2774ad581fbd6941e2f9cb026b7a44/crates/provider/src/provider/root.rs#L23-L26
so we can send a this type across boundaries.

feat: make Pending transaction own the provider

---

crates/consensus/src/header.rs
crates/rpc-types-eth/src/block.rs

The requests root is now a hash over an RLP encoded list of all requests in the block, i.e. a "requests hash". See https://github.com/ethereum/EIPs/pull/8854
Rename `requests_root`.
Closes #1339

chore: rename requests root to requests hash

---

crates/consensus/src/header.rs

#1379 passed the PR checks, but somehow not on main.
Remove remaining references to `requests_root`

fix: use `requests_hash`

---

crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/receipts.rs
crates/rpc-types-eth/src/transaction/receipt.rs

Closes #1493 
`state_root` in `TransactionReceipt` would conflict with `Eip658::PostState(root)` in `Receipt` as both have serde aliases set as `root`. Remove `state_root`.

fix(`rpc-types-eth`): receipt deser

---

crates/eips/src/eip4844/sidecar.rs

ports reth function:
https://github.com/paradigmxyz/reth/blob/bc43613be35f316304f7ce4a2225855ac26b5923/crates/primitives/src/transaction/sidecar.rs#L254-L256
note: this is currently behind arbitrary because idk if this is sound, so this is only really intended for testing.

feat: port generate_blob_sidecar

---

crates/eips/src/eip2718.rs

use Vec::with_capacity avoid realloc

eips: update fn encoded_2718

---

crates/rpc-client/src/builtin.rs
crates/rpc-client/tests/it/ws.rs
crates/transport-ws/src/lib.rs
crates/transport-ws/src/native.rs

feat: make it possible to configure Ws config

---

crates/rpc-types/Cargo.toml

closes #1453
imo this is reasonable because if you want those crates without serde you should not use rpc-types and use those crates directly.
the alternative is making serde a feature on all rpc types crates which I don't think is reasonable

chore: enable serde types dependencies in rpc-types

---

crates/eips/src/eip2718.rs
crates/eips/src/eip4844/builder.rs
crates/eips/src/eip4844/sidecar.rs

chore: remove redundant cfgs

---

crates/consensus/src/header.rs

fix requests root

---

crates/consensus/src/header.rs

Previous code had a bunch of incorrect placeholders only required for arbitrary impls that output incorrect headers.
Remove the placeholders

chore: make Header encoding good

---

.github/CODEOWNERS

I can't be subscribed to notifications on my own PRs without also getting email/github notifications for every PR
Remove self from codeowners

chore: remove self from codeowners

---

crates/provider/Cargo.toml
crates/provider/src/blocks.rs
crates/provider/src/ext/admin.rs
crates/provider/src/ext/debug.rs
crates/provider/src/ext/mod.rs
crates/provider/src/ext/net.rs
crates/provider/src/ext/trace.rs
crates/provider/src/ext/txpool.rs
crates/provider/src/fillers/gas.rs
crates/provider/src/provider/trait.rs

- Disable more geth/reth tests when not run in CI
- remove a bunch of bad-behavior `init_tracing` calls in tests to remove extraneous logs in test output
followup to #1393. That PR fixed `cargo t` this pr fixes `cargo t --all-features`

tests: fix more ci only

---

crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/typed.rs

closes #1494 
Add `MaybeTagged` serde to `TypedTransaction` to allow deser of json objects missing the type flag

fix: maybetagged serde for typed transaction

---

crates/provider/src/layers/cache.rs
crates/rpc-types-trace/src/geth/mod.rs

1. fix an clippy warning:
```
warning: first doc comment paragraph is too long
--> crates/provider/src/layers/cache.rs:61:1
|
61 | / /// The [`CacheProvider`] holds the underlying in-memory LRU cache and overrides methods from the
62 | | /// [`Provider`] trait that should attempt to fetch from cache and fallback to the RPC in case of a
63 | | /// cache miss.
64 | | ///
65 | | /// Most importantly, the [`CacheProvider`] adds `save_cache` and `load_cache` methods to the
| |_
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_long_first_doc_paragraph
= note: `-W clippy::too-long-first-doc-paragraph` implied by `-W clippy::all`
= help: to override `-W clippy::all` add `#[allow(clippy::too_long_first_doc_paragraph)]`
warning: `alloy-provider` …
```

docs(prestate): comment prestate more clear

---

crates/eips/src/eip7685.rs

The hashing is tested against an equivalent python script to verify the correctness of the result.

eip7685: add unit tests and reduce paths

---

crates/rpc-types-engine/src/cancun.rs
crates/rpc-types-engine/src/sidecar.rs

We have an interceptor in Reth that stores engine API messages, including extra fields, which are now present in the sidecar. This interceptor stores them on disk by serializing them with serde.
Derive `Serialize`/`Deserialize` for the sidecar.

feat: derive serde for `ExecutionPayloadSidecar`

---

crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/envelope.rs
crates/eips/src/eip2718.rs
crates/eips/src/eip4844/sidecar.rs

Closes #1499 
current `Encodable` and `Decodable` implementations do not RLP encode or RLP decode the sidecar. Instead they encode only the fields, without the header, producing incorrect RLP output
Current behavior has been moved into more-explicitly named functions and is used to construct correct RLP implementations
This is a breaking change as things that previously (incorrectly) deserialized now will not

fix: correct implementations of Encodable and Decodable for sidecars

---

crates/consensus/src/transaction/mod.rs

Nice to have at an alloy level to remove the bound here https://github.com/paradigmxyz/reth/blob/20dc0c7da0a12e31ab0c896ccf4208585658ad07/crates/primitives-traits/src/transaction/mod.rs#L19

consensus: add `Debug` trait bound for `Transaction` trait

---

crates/rpc-types-trace/src/geth/mux.rs
crates/rpc-types-trace/src/geth/pre_state.rs

In some cases, we only need to track the ether balance/nonce changes, so no need to return the lonng code/storage back, so propose to add two new options: `disableCode` and `disableStorage` to indicate wheather need to track code/storage or not.

feat(rpc-types-trace/prestate): support disable_{code,storage}

---

crates/genesis/src/lib.rs

The next fork is Osaka, and we'll have a devnet for it soon, alongside Prague.
Add Osaka to the genesis spec.

feat: add osaka time to genesis

---

Cargo.toml

This includes breaking changes in the auth types, as `signature(&self)` now returns a `Result`

deps: bump alloy-eip7702

---

crates/eips/src/eip4844/sidecar.rs

Right now this encodes as list and expects string during decoding which is incorrect. 
I am wondering if we should remove those impls completely? Given that sidecar encoding on its own is not defined

fix: sidecar rlp decoding

---

crates/rpc-types-eth/src/block.rs

An easy to manage and maintain conversion util with the goal to replace https://github.com/paradigmxyz/reth/blob/2ae93682b4978bf80bf27c777334ead30d3e04f5/crates/rpc/rpc-types-compat/src/block.rs#L104

rpc: impl `From<Sealed<alloy_consensus::Header>>` for `Header`

---

crates/consensus/src/constants.rs

Not sure but seems like this hash was not correct as per:
- https://github.com/paradigmxyz/reth/blob/fcca8b1523fa7c1917754389fd08c9b21eb57987/crates/primitives-traits/src/constants/mod.rs#L74
- https://holesky.etherscan.io/block/0

consensus: fix `HOLESKY_GENESIS_HASH`

---

crates/eips/src/merge.rs

Related https://github.com/paradigmxyz/reth/pull/12027#pullrequestreview-2391948259

eips: rm `BEACON_CONSENSUS_REORG_UNWIND_DEPTH`

---

crates/consensus/src/block.rs

chore: add blockbody default

---

crates/eips/src/eip1559/constants.rs

As in reth we will eliminate unnecessary redeclarations here (to import alloy constants):
https://github.com/paradigmxyz/reth/blob/5e4da59b3a83c869647ad38b6f679f7594c11938/crates/primitives-traits/src/constants/mod.rs#L12-L24
We also need to make sure that the reth test:
https://github.com/paradigmxyz/reth/blob/5e4da59b3a83c869647ad38b6f679f7594c11938/crates/primitives-traits/src/constants/mod.rs#L83-L91
is in alloy in order to secure the implementation.

eips: add missing unit test for `MIN_PROTOCOL_BASE_FEE`

---

crates/consensus/src/block.rs
crates/rpc-types-eth/src/block.rs

The goal here is similar to https://github.com/alloy-rs/alloy/pull/1532
In reth we have: 
https://github.com/paradigmxyz/reth/blob/2ae93682b4978bf80bf27c777334ead30d3e04f5/crates/rpc/rpc-types-compat/src/block.rs#L178-L192
And I have found myself several times in the situation where I was forced to go through the `reth-rpc-types-compat` crate just for this small conversion.
Seems like more logical and smooth to have it directly in alloy since the target type is an alloy rpc type.
I did a test against reth implementation to check the results are the same

rpc: add `uncle_block_from_header` impl and test

---

crates/eips/src/eip7685.rs

Clarifies that `Requests` in EIP7685 only contains `requests_data`, not the request type.

docs: expand on what `Requests` contains

---

crates/consensus/src/receipt/receipts.rs

This is done to replace https://github.com/paradigmxyz/reth/blob/ba78e439385469925c6fc9df36444f1ef5a6a1bc/crates/primitives/src/receipt.rs#L104 in order to be used in reth
Related https://github.com/paradigmxyz/reth/pull/12059

consensus: implement `root_slow` for `Receipts`

---

crates/provider/src/provider/trait.rs

Changes default behavior of `eth_call` and `eth_estimateGas` to use the `"pending"` block tag.
per discussion in slack channel
Users do not expect to simulate on latest height and timestamp, and will get subtly incorrect outputs when calls read `block.height` or `block.timestamp`. Users generally expect the _next_ value when simulating, as they are anticipating submitting a transaction. This changes default client behavior to specify `"pending"` for those calls

feat: make eth_call and eth_estimateGas default to using Pending block

---

crates/provider/src/ext/anvil.rs
crates/rpc-types-anvil/Cargo.toml
crates/rpc-types-anvil/src/lib.rs

Currently we don't have `anvil_reorg` in the `AnvilApi` trait. 
Introduce `anvil_reorg` to `AnvilApi` and its related types to `rpc-types-anvil`.

feat: introduce `anvil_reorg` and related types.

---

crates/consensus/src/signed.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/rlp.rs
crates/eips/src/eip2718.rs
crates/eips/src/eip4844/sidecar.rs

Spawned from the depths of #1485 
Fix transaction coding APIs to be usable and clear
- #1510 output for `encode_with_signature`
- Codebase generally confuses the 2 uses of RLP encoding (tx payload and network format)
- The docs for `encode_with_signature` are wrong
- `encode_with_signature` produces 2718 output when `with_header` is false, and RLP in network format when `with_header` is `true`. All other `encode_` methods produce RLP output in non-network format
- `decode_with_signature` is missing entirely
- `EncodableSignature` seems to now be redundant as reth migrated to `alloy-primitives::Signature`
create a simple API in which encoding and decoding function names specify which format they produce/accept

fix: make a sensible encoding api

---

crates/consensus/src/transaction/envelope.rs

Adds a method to the `TxEnvelope` type that returns if the associated signature is protected.

feat(consensus): Protected Legacy Signature

---

crates/provider/src/fillers/gas.rs
crates/provider/src/layers/cache.rs
crates/provider/src/provider/trait.rs

Different args in `alloy-provider` crate: 
```
/// Gets a block by its [BlockHash], with full transactions or only hashes.
async fn get_block_by_hash(
&self,
hash: BlockHash,
kind: BlockTransactionsKind,    <--
)
...
/// Get a block by its number.
// TODO: Network associate
async fn get_block_by_number(
&self,
number: BlockNumberOrTag,
hydrate: bool,                  <--
)
```
Changing `hydrate` argument to `kind` to make methods symmetrical.

fix(alloy-provider): `get_block_by_number` arg

---

crates/provider/src/ext/anvil.rs
crates/provider/src/provider/trait.rs

I was hasty in merging https://github.com/alloy-rs/alloy/pull/1582, checking the status through an external interface said it was good to merge, when in fact it was not.
Fix the remaining tests and unbreak CI. Sorry

test: fix tests

---

.github/workflows/ci.yml

Also removes the `cfg-check` job since it's no longer necessary as it's enabled by default since 1.80.

ci: add success job

---

crates/network/src/any/mod.rs
crates/rpc-types-eth/src/lib.rs

fix: update AnyNetwork type aliases

---

crates/consensus/src/transaction/eip4844.rs

Current implementation has a bug: 
https://github.com/alloy-rs/alloy/blob/193bcd8d8d204e89e74b25a51b395cbb5e8087e4/crates/consensus/src/transaction/eip4844.rs#L889
Here we need to use `..header.payload_length`
Also we didn't override `rlp_header_signer` for eip4844 tx with sidecar which resulted in invalid rlp in some edge cases
Fix decoding methods and change them to use common flow of all other such methods without temporary buffer creation

fix: RLP for `TxEip4844`

---

crates/consensus/src/receipt/receipts.rs

Follow up on https://github.com/alloy-rs/alloy/pull/1563:
- Full coverage with unit tests
- Small refactor

consensus: rm `Receipts` `root_slow` unused method

---

crates/consensus/src/transaction/eip4844.rs
crates/rpc-types-eth/src/transaction/mod.rs

Fixes `TransactionResponse::tx_hash` implementation for rpc transaction type. It now relies on inner envelope to implement `Encodable2718`.
Also includes small clean-up in eip4844 removing unnecessarily overriden methods

fix: hash handling

---

crates/consensus/Cargo.toml
crates/consensus/src/signed.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/typed.rs
crates/rpc-types-eth/src/transaction/mod.rs

#1460 removed the arbitrary impl for rpc transaction because we didn't have it for tx envelope. This PR implements arbitrary for transaction types. It requires `k256` feature to be able to sign transactions and 7702 authorizations.

feat: implement Arbitrary for transaction types

---

crates/network/src/any/either.rs
crates/network/src/any/unknowns.rs

`OtherFields` has some useful helper methods (e.g `deserialize_into`), and it is useful to have a way to access them directly from `UnknownTypedTransaction`

feat: use `OtherFields` on `UnknownTypedTransaction`

---

crates/consensus/src/receipt/receipts.rs
crates/consensus/src/receipt/status.rs

ref https://github.com/foundry-rs/foundry/issues/9239#issuecomment-2453005357
Right now we will fail to deserialize receipt if both `status` and `root` are present.
Update serde impl to deserialize `Eip658Value` as untagged enum with `status` and `root`. We prefer `status` as it is more common and adds useful context.
This also allowed to just use `serde(flatten)` for status field and remove manual serde for receipt.

fix: receipt status serde

---

crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/typed.rs
crates/network/src/any/mod.rs
crates/network/src/any/unknowns.rs
crates/network/src/lib.rs
crates/serde/src/optional.rs

RIght now `AnyTxType` is serialized as number but we should use quantity for it.
Also, `MaybeTaggedEnvelope` would correctly deserialize legacy transaction if map has all its fields and a different type flag. This is the case for deposit transaction breaking its deserialization in `AnyTxEnvelope` context
Serialize and deserialize `AnyTxType` as `U8`
Fail `Untagged` variant deserialization if `type` is present.
Also fixed deserialization of transaction fields in `Transaction` trait impl. We had incorrect name for `gas` and didn't use quantity when deserializing integers.

fix: serde for `AnyTxEnvelope`

---

crates/provider/src/provider/caller.rs
crates/provider/src/provider/eth_call.rs

Closes #1471 
- Change the `data` and `overrides` fields in `EthCallParams` to be `Cow`. 
- Accept `EthCallParams` as arg in `Caller.call(&self, method, params: EthCallParams<'_, N>)`.
- `ProviderCall` should be used over `EthCallParams`

fix(`provider`): make `Caller` `EthCall` specific

---

crates/consensus/Cargo.toml
crates/eip5792/Cargo.toml
crates/eip5792/src/wallet.rs

After https://github.com/alloy-rs/alloy/pull/1579 we can directly use `ChainId` (u64) instead of U64 big int in `WalletCapabilities`.

eip5792: use `ChainId` in `WalletCapabilities`

---

crates/serde/src/storage.rs

Closes #1553 
Introduce the enum `StorageKeyKind` with variants `Hash(B256)` and `Number(U256)`. Used in `JsonStorageKey`.
Tries to deserialize a string into the `Hash` variant first.

feat(`serde`): StorageKeyKind

---

crates/provider/src/fillers/nonce.rs

ref #1491
dashmap is clone, which imo is a footgun, because dashmap acts as `Rwlock<HashMap>` not `Arc<Rwlock<HashMap>>`
> DashMap tries to be very simple to use and to be a direct replacement for RwLock<HashMap<K, V>>. To accomplish this, all methods take &self instead of modifying methods taking &mut self. This allows you to put a DashMap in an Arc<T> and share it between threads while being able to modify it.

fix: wrap dashmap in Arc

---

crates/consensus/src/block/header.rs
crates/network-primitives/src/lib.rs
crates/network-primitives/src/traits.rs
crates/network/src/lib.rs
crates/rpc-types-eth/src/block.rs

Closes https://github.com/alloy-rs/alloy/issues/1626

fix: re-introduce HeaderResponse trait

---

crates/rpc-types-eth/src/fee.rs

Currently we don't correctly handle a `eth_feeHistory` response in which `gasUsedRatio` is `null`.
Handle this case by deserializing to an empty vec.

fix(`rpc-types`): `FeeHistory` deser

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs
crates/network/src/any/either.rs
crates/network/src/any/unknowns.rs
crates/rpc-types-eth/src/transaction/mod.rs

Migrate reth utility method https://github.com/paradigmxyz/reth/pull/12437#discussion_r1837882648
Adds trait method `alloy_consensus::Transaction::is_dynamic_fee`

Add trait method `Transaction::is_dynamic_fee`

---

crates/consensus/src/transaction/legacy.rs

Makes sure that we never panic when dealing with chain_ids up to `u64::MAX`. Larger chain_ids would just fail decoding/deserialization

fix: make EIP-155 signatures logic safer

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs
crates/network/src/any/either.rs
crates/network/src/any/unknowns.rs
crates/rpc-types-eth/src/transaction/mod.rs

Port utility method from reth https://github.com/paradigmxyz/reth/blob/3a337cd7d4ad8c14569d20141fdcc2b1c54dbdf3/crates/primitives/src/transaction/mod.rs#L329-L342
Adds trait method `Transaction::effective_gas_price`

Add trait method `Transaction::effective_gas_price`

---

crates/provider/Cargo.toml
crates/provider/src/ext/debug.rs

I noticed that `debug_executionWitness` only existed on the server side, and not on the alloy client side.
Add the `debug_executionWitness` method to the `DebugApi`

feat(debug): add debug_executionWitness to debug api

---

crates/consensus/src/block/header.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/legacy.rs

Recent changes in `consensus` types brought breaking changes to serialization/deserialization usecases. 
See https://github.com/foundry-rs/foundry/pull/9280/files/999eea97817168b67318f15b3e58f33d378e8c96#r1844004048 and https://github.com/foundry-rs/foundry/issues/9324.
Add aliases to avoid breaking changes
- Alias `sha3Uncles` with `ommersHash` and `miner` with `beneficiary` in `Header`.
- Alias `gas` with `gasLimit` in tx types.

fix(`consensus`): serde aliases to avoid breaking changes

---

crates/consensus/src/block/header.rs
crates/consensus/src/transaction/mod.rs

Improve usability of abstraction of data primitives. Ref https://github.com/paradigmxyz/reth/pull/12613.
Add blanket implementations of `Transaction` and `BlockHeader` for `&T` and `Arc<T>`.

Add blanket impl of Transaction, TxReceipt and BlockHeader references

---

crates/transport/src/layers/retry.rs

Closes https://github.com/alloy-rs/alloy/issues/1147
Use `TransportFut` in the bound which adjusts when to require `Send`.
This is a bit more restrictive but should be fine as all transports are requried to produce `TransportFut`

fix: wasm compatibility for RetryBackoff

---

crates/rpc-types-mev/src/eth_calls.rs

Previously https://github.com/alloy-rs/alloy/pull/978 missed `coinbase` and `timeout` when adding the additional undocumented fields available on the actual node.  I suspect this happened because the the initial versions of `rpc-types-mev` were based on Flashbots' public API docs for `eth_callBundle`, but the public options are actually only a subset of what's actually available on an actual node.  
This simply adds the missing fields and their builder methods. I'll also make a follow-on PR to add functionality for them in reth.

feat: Add more missing eth_callBundle arguments

---

crates/consensus/src/transaction/envelope.rs

doesn't hurt, need this because default enforced in reth for testing

chore: add default for txtype

---

crates/signer/src/lib.rs

Currently we are still re-exporting deprecated `Signature` from `alloy-signer`
Export `PrimitiveSignature` instead

fix(`signer`): export PrimitiveSignature instead of deprecated sig

---

deny.toml

this is still present until ssz released
unclear why the ci passed earlier @DaniPopes 
ah it didn't but not a blocker for auto merge -.-

ci: add ignored advisory back

---

crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/mod.rs

we need this often and this can be implemented on txtype and transaction itself.
this first introduces the trait and in a next step this can be added to `Transaction: Typed2718`

feat: introduce Typed2718 trait

---

crates/consensus/src/transaction/eip4844.rs
crates/contract/src/event.rs
crates/genesis/src/lib.rs
crates/rpc-types-eth/src/filter.rs
crates/transport/src/utils.rs

chore: make clippy happy

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs
crates/network/src/any/either.rs
crates/network/src/any/unknowns.rs
crates/rpc-types-eth/src/transaction/mod.rs

`alloy-consensus::Transaction` implementors didn't have a cheap way to check if the transaction was a `Create`. They had to go through `kind` which copies the 21-byte `TxKind`. This may scale poorly for code that processes (hundreds of) thousands of transactions per second: https://github.com/paradigmxyz/reth/issues/12838.
Add `is_create` to the trait that allows fast non-allocating implementation. I considered making `kind` returns `&TxKind` but transactions like EIP-4844, 7702, etc. only store an `Address` and it would be bad if we forced them to promote it to `TxKind`.

feat(consensus-tx): enable fast `is_create`

---

crates/consensus-any/src/receipt/envelope.rs
crates/consensus/src/lib.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs
crates/rpc-types-any/Cargo.toml
crates/rpc-types-any/src/transaction/receipt.rs
crates/rpc-types-eth/src/log.rs
crates/rpc-types-eth/src/transaction/receipt.rs

Unblocks: https://github.com/paradigmxyz/reth/issues/12701

feat: modifiy ReceiptWithBloom and associated impls to use with Reth

---

crates/provider/src/provider/trait.rs

Related: #1681.
Right now cannot call `eth_getFilterLogs` JSON-RPC method without using `raw_request` which is not ideal.
Adds a new `get_filter_logs` method to `Provider` trait.

feat: get_filter_logs in Provider trait

---

crates/provider/src/provider/trait.rs

Related: #1681.
Right now cannot call `get_block_transaction_count_by_number` JSON-RPC method without using `raw_request` which is not ideal.
Adds a new `get_block_transaction_count_by_number` method to `Provider` trait.

feat: get_block_transaction_count_by_number in Provider trait

---

crates/contract/src/call.rs
crates/provider/src/builder.rs
crates/provider/src/provider/trait.rs

Currently, the `on_anvil_*`  methods on the provider builder return a provider based on `Http<Client>` transport client. 
Since, the default transport in `Provider` is `BoxTransport`, there exists friction when working with types that wrap a Provider. It becomes necessary to add the `T: Transport` generic to `Foo<P: Provider<T>, T: Transport + Clone>>.
The following (cleaner) way isn't possible:
```rust
struct Foo<P: Provider> {
provider: P,
}
impl<P: Provider> Foo<P> { // default transport is BoxTransport
pub fn new(provider: P) -> Self {
Self { provider }
}
pub async fn get_block_number(&self) -> TransportResult<u64> {
self.provider.get_block_number().await
}
}
#[tokio::main]
async fn main() -> Result<()> {
let provider = ProviderBuilder::new().on_anvil(); // provider based on …
```

fix(provider): use `BoxTransport` in `on_anvil_*`

---

crates/consensus-any/src/block/header.rs
crates/consensus/src/block/header.rs
crates/eips/src/eip4844/mod.rs
crates/eips/src/eip7742.rs
crates/eips/src/lib.rs
crates/provider/src/fillers/gas.rs
crates/rpc-types-beacon/src/payload.rs
crates/rpc-types-engine/src/lib.rs
crates/rpc-types-engine/src/payload.rs
crates/rpc-types-engine/src/prague.rs
crates/rpc-types-engine/src/sidecar.rs
crates/rpc-types-eth/src/block.rs

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7742.md
https://github.com/ethereum/execution-apis/pull/574
https://github.com/ethereum/EIPs/pull/8994
- Added new mod to alloy-eips with utilities for blob fee calculation.
- Extended `PayloadAttributes` with `target_blobs_per_block` and `max_blobs_per_block`.
Some PRs are not merged and field names are different per different specs for now, but besides that this should be complete

feat: EIP-7742

---

crates/eips/src/eip7742.rs
crates/rpc-types-beacon/Cargo.toml
crates/rpc-types-beacon/src/relay.rs

Removes parent target blob cound from `calc_excess_blob_gas_at_transition` and adds `target_blobs_per_block` to `SignedBidSubmissionV4`

fix: EIP-7742 fixes

---

Cargo.toml
crates/json-rpc/Cargo.toml
crates/transport/Cargo.toml

We don't actually use it for no_std crates so there's not much here.
Closes https://github.com/alloy-rs/alloy/issues/1628.

chore(deps): bump thiserror 2

---

crates/eips/src/eip6110.rs
crates/eips/src/eip7685.rs

Adds constant `DEPOSIT_REQUEST_TYPE` similarly to
https://github.com/alloy-rs/alloy/blob/eb8fb7133e19248b8ba3cda009b3f63deacce0c5/crates/eips/src/eip7002.rs#L18-L20
and https://github.com/alloy-rs/alloy/blob/eb8fb7133e19248b8ba3cda009b3f63deacce0c5/crates/eips/src/eip7251.rs#L15-L17
And a helper `Requests::push_request_with_type` which appends request data to the given request typ

feat: EIP-7685 requests helpers

---

crates/consensus/src/transaction/mod.rs

add a default helper to compute the blob gas used

feat: add blob_gas_used

---

crates/eips/src/eip7685.rs

We can do this here to avoid additional checks on callsite

fix: omit empty requests

---

crates/consensus/src/block/header.rs
crates/eips/src/eip7742.rs

Closes https://github.com/alloy-rs/alloy/issues/1709

fix: adjust EIP-7742 to latest spec

---

crates/consensus-any/src/receipt/envelope.rs
crates/consensus/src/lib.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/mod.rs
crates/eips/src/eip2718.rs

Divides `RlpReceipt` into `RlpEncodableReceipt` and `RlpDecodableReceipt`, implementing `RlpEncodableReceipt` for references.
Provides `impl Encodable2718 for ReceiptWithBloom` when inner receipt knows its type.

feat: impl `Encodable2718` for `ReceiptWithBloom`

---

crates/consensus-any/src/receipt/envelope.rs
crates/rpc-types-any/Cargo.toml
crates/rpc-types-any/src/transaction/receipt.rs
crates/rpc-types-eth/src/log.rs

Based on #1719 
I've added this impl to support a more generic `AnyReceiptEnvelope` https://github.com/alloy-rs/alloy/blob/67576f9f6e70026116443851a43e4c805902c3b3/crates/rpc-types-eth/src/log.rs#L156-L160
However, it is in fact incorrect as `Borrow` shouldn't be implemented in this case
This PR reverts changes including this impl and changes `AnyReceiptEnvelope` back to always holding a `Receipt<T>`
If we want to still support `AnyReceiptEnvelope` being generic over arbitrary receipt types, we'd need to either add `AsRef<Self> for alloy_primitives::Log` and use it instead or introduce a separate `Log` trait to replace such bounds with: https://github.com/alloy-rs/alloy/blob/67576f9f6e70026116443851a43e4c805902c3b3/crates/consensus/src/receipt/receipts.rs#L27-L29

fix: remove `Borrow` impl for RPC receipt

---

crates/consensus/src/proofs.rs

this way the function can support any type of header

chore: relax ommers root fn

---

crates/provider/src/ext/debug.rs

Closes https://github.com/alloy-rs/alloy/issues/1728#issuecomment-2512171575
closes #1738

feat: specialized geth tracer

---

crates/consensus/src/transaction/mod.rs

`Signature` is being migrated to `PrimitiveSignature` and all alloy code now uses the latter
from: https://github.com/alloy-rs/core/issues/788

docs: Fix `SignableTransaction` docs to use `PrimitiveSignature`

---

crates/json-rpc/src/result.rs

Using Debug (used by tracing::Value for str) escapes strings which makes it really hard to copy paste or extract to format it or whatever when debugging

chore: Display instead of Debug the response JSON

---

crates/consensus/src/receipt/receipts.rs

The `Deref` / `DerefMut` derives were kind of an antipattern, giving the illusion that `Encodable` was implemented, when it was only due to deref coercion. Decodable was also not implemented. This is required if we ever want to use the `Receipts` type in reth.
This instead this removes the derived derefs, and directly implements the encodable / decodable traits.

feat: impl Encodable / Decodable for Receipts

---

crates/provider/src/fillers/gas.rs

With EIP-7691, we can no longer rely on `BlockHeader::next_block_blob_fee` as it will start producing invalid values once the update fraction changes.
This PR changes blob fee filler to use `feeHistory` instead to obtain those values from RPC.
I think we should also consider either deprecating `BlockHeader::next_block_excess_blob_gas`/`BlockHeader::next_block_blob_fee` methods or making them accept an update fraction parameter

fix: use `feeHistory` when estimating blob fee

---

crates/eips/src/eip7691.rs
crates/eips/src/lib.rs

Closes #1712 
Implements https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7691.md
The current API might be a bit confusing given that the fn has same signature as `eip4844::calc_blob_gasprice`. Unsure how we can make this nicer, something similar to `BaseFeeParams` could probably work but it's unclear how callers would set it
Also I don't not how we should handle this in `BlockHeader::next_block_blob_fee` and `BlobGasFiller`. Given variable update fraction we no longer can estimate the blob fee for next block without knowing the hardfork activation times

feat: EIP-7691

---

crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/recovered.rs

ports the reth `RecoveredTx` to alloy as `Recovered`.
this is similar to `Signed`.
we don't have `recover_signer` as part of any API rn, so this introduces this as a new trait.
once we're happy with this we can integrate this like: `Signed -> Recovered<Signed>`
wdyt @Rjected @klkvr

chore: introduce recovered and recoverable

---

crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/pooled.rs

migrates the reth `PooledTransactionElement` type and renames it to just `PooledTransaction`.
@klkvr I assume we can simplify the decode/encode impls now

feat: port reth pooled tx type

---

crates/network-primitives/src/traits.rs

`TransactionResponse`'s base trait `alloy_consensus::Transaction` already has `to` method with the exact same default implementation.
It causes the following error when using `TransactionResponse` along with `Transaction`, and the result is the same when `to()` is called with either of the above traits. It would be a bit confusing.
```rs
error[E0034]: multiple applicable items in scope
--> crates/.../...
|
216 |                 .to()
|                  ^^ multiple `to` found
|
= note: candidate #1 is defined in an impl of the trait `TransactionResponse` for the type `alloy_rpc_types_eth::Transaction<T>`
= note: candidate #2 is defined in an impl of the trait `TransactionTrait` for the type `alloy_rpc_types_eth::Transaction<T>`
help: disambiguate the method for candidate #1
|
215 | …
```

feat: Remove duplicated `to` method in `TransactionResponse`

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs
crates/network/src/any/either.rs
crates/network/src/any/unknowns.rs
crates/rpc-types-eth/src/transaction/mod.rs
crates/rpc-types-eth/src/transaction/request.rs

Address #1735 ,  unifies tx types around eip2718
Implements the Typed2718 for transaction types with `fn ty`

feat(consensus): require typed2718 for transaction

---

crates/eips/src/eip1898.rs

feat: add arbitrary for alloy types

---

crates/consensus/src/block/header.rs

These helpers are useful in reth consensus methods for example, and had to be reimplemented.
Added these methods to the `BlockHeader` trait. Removes the methods from the concrete `Header`, making it breaking unless the trait is already imported.

chore: add consensus helper methods to BlockHeader

---

crates/rpc-types-eth/src/transaction/request.rs

Couple quick nits to make `TransactionRequest` behavior clearer

nits: improve doc clarity around build functions

---

crates/consensus/src/block/mod.rs
crates/consensus/src/transaction/mod.rs

https://github.com/paradigmxyz/reth/issues/12519
Brought BlockBody fns from reth to replace reth's BlockBody type with alloy's

feat: reth's block body fns

---

crates/rpc-types-eth/src/block.rs

https://github.com/ethereum/execution-apis/pull/570
geth already removed support for this, reth is wip
https://github.com/paradigmxyz/reth/pull/13303

docs: add note about deprecated total difficulty

---

crates/provider/src/provider/trait.rs
crates/transport/src/layers/retry.rs

Currently, we cannot set custom retry policies (`RetryPolicy`) as the `RetryBackoffService` defaults to the `RateLimitRetryPolicy` type here: https://github.com/alloy-rs/alloy/blob/663e926b1b721184c78433631e4c86647d9e2222/crates/transport/src/layers/retry.rs#L81.
Make the `RetryBackoffLayer` and `RetryBackoffService` generic over `RetryPolicy` with `RateLimitRetryPolicy` as the default.

fix(`transport`): allow `RetryPolicy` to be set via layer

---

crates/consensus/src/transaction/pooled.rs

adds some helpers to convert into a signed variant

chore: add helpers to unwrap a variant

---

crates/rpc-types-engine/src/payload.rs

This is similar to how we handle `ExecutionPayload`s and makes it clear which fields were actually added in v4

chore: reuse v3 envelope in v4 envelope

---

crates/eips/src/eip1559/constants.rs
crates/eips/src/eip1559/helpers.rs
crates/eips/src/eip1559/mod.rs

port fn we added to reth
https://github.com/paradigmxyz/reth/blob/ca4095a6a807e4859f508bb9748b1608832f5b41/crates/ethereum/payload/src/config.rs#L40-L47
note: this doesn't really fit into the 1559 mod, but it's the closest and that's also where the gas limit const is defined

chore: port calc block gas limit

---

crates/consensus/src/block/mod.rs

chore: add arbitrary for block

---

crates/node-bindings/src/utils.rs

Add two edge case tests for `extract_value` in https://github.com/alloy-rs/alloy/blob/main/crates/node-bindings/src/utils.rs#L26, which extract values given keys from the line of text. 
When there is no comma (like extract `value` from string `"key: value"`), the function will fail the test.
Also add doc to better explain this function.
The code uses different patterns for finding values for keys ending with '=' and ': ', as shown below. By changing them into the same pattern, the issue is fixed. 10 tests in `utils.rs` are all passed.
```
// Try to find the key with '='
if let Some(pos) = line.find(key_equal.as_ref()) {
let start = pos + key_equal.len();
let end = line[start..].find(' ').map(|i| start + i).unwrap_or(line.len());
if start <= line.len() && end <= line.len() {
return …
```

Add edge case tests for `extract_value` and fix the newly discovered bug

---

crates/rpc-types-beacon/src/requests.rs

this is more useful when deal with unwrap_or_default chaining

chore: add convenience tryfrom impl

---

crates/rpc-types-admin/src/admin.rs

The difficulty field is being removed from this part of the response in https://github.com/ethereum/go-ethereum/pull/30744
See the new struct: https://github.com/ethereum/go-ethereum/blob/314e18193eeca3e47b627408da47e33132d72aa8/eth/protocols/eth/handler.go#L119-L126
Make the `difficulty` field optional

chore: remove difficulty field from admin_nodeInfo response

---

crates/rpc-types-eth/src/erc4337.rs

these are hex or decimal so we need to use the serde helpers
https://github.com/ethereum-optimism/op-geth/blob/928070c7fc097362ed2d40a4f72889ba91544931/core/types/transaction_conditional.go#L89-L92
ref https://github.com/paradigmxyz/reth/issues/13488

fix: support hex values for conditional options

---

crates/rpc-types-eth/Cargo.toml
crates/rpc-types-eth/src/block.rs
crates/rpc-types-eth/src/filter.rs
crates/rpc-types-eth/src/transaction/error.rs
crates/rpc-types-eth/src/transaction/request.rs

with thiserror we can have this for no-std now

chore: replace derive_more with thiserror

---

crates/rpc-types-eth/src/erc4337.rs

port 
https://github.com/ethereum-optimism/op-geth/blob/928070c7fc097362ed2d40a4f72889ba91544931/core/types/transaction_conditional.go#L106-L126
ref https://github.com/paradigmxyz/reth/issues/13488

feat: add cost fn for conditional opts

---

crates/rpc-types-eth/src/erc4337.rs

use op's naming for this and keep a (deprecated) alias

chore: rename ConditionalOptions

---

crates/network-primitives/src/block.rs
crates/rpc-types-eth/src/block.rs

feat: add map transactions to rpc block type

---

crates/eips/src/eip2935.rs

EIP-2935: update contract bytecode & address

---

crates/consensus/src/transaction/envelope.rs

modifies the derived untagged impl to return the tagged attempt error, which is more useful that the generated "data did not match any variant of untagged enum MaybeTaggedTxEnvelope".
this requires private serde API but this should be okay because this is what untagged expands to.
we could technically make this work if we handroll deserde entirely but would be more error prone
```rust
impl<'de> _serde::Deserialize<'de> for MaybeTaggedTxEnvelope {
fn deserialize<__D>(
__deserializer: __D,
) -> _serde::__private::Result<Self, __D::Error>
where
__D: _serde::Deserializer<'de>,
{
let __content = <_serde::__private::de::Content as _serde::Deserialize>::deserialize(
__deserializer,
)?;
let __deserializer = _serde::__private::de::ContentRefDeserializer::<
__D::Error,
>::new(&__content);
if let …
```

feat: return tagged variant deserde error

---

crates/consensus/src/block/header.rs
crates/eips/src/eip4844/mod.rs
crates/eips/src/eip7840.rs
crates/eips/src/lib.rs
crates/genesis/Cargo.toml
crates/genesis/src/lib.rs
crates/rpc-types-eth/src/block.rs

Implements EIP-7840 https://github.com/ethereum/EIPs/pull/9129
`alloy_eips::eip7840` has 2 structs: `BlobScheduleItem` which is the one present in genesis config as per EIP, and `BlobParams` which is a new aggregated configuration for blob constants, including an update fraction which is going to change in Prague as well with EIP-7691. All methods of header which need to perform blobfee-related calculations are now accepting `BlobParams` similarly to methods performing eip1559 calculations.
`ChainConfig` is extended with `blob_schedule` which is a mapping from `String` to `BlobScheduleItem`. It is not great because this means that we'd need to perform parsing of strings into the actual hardforks names on demand and won't have type-safety during parsing.
One way to improve this could be to …

feat: EIP-7840

---

crates/serde/src/other/mod.rs

inserting a value requires serde_json in scope, this adds a helper to work around this

feat: add insert helper to otherfields

---

crates/consensus/src/transaction/envelope.rs
crates/rpc-types-eth/src/transaction/request.rs

this is a footgun because this forces users to add a _ => unreachable on a match missing new tx types

chore: rm non exhaustive for envelope

---

crates/consensus/src/conditional.rs
crates/consensus/src/lib.rs
crates/consensus/src/transaction/meta.rs

introduces a helper type that encapsulates 4337 block conditionals.
this needs a few followups to make it actually useful
ref https://github.com/paradigmxyz/reth/issues/13488#issuecomment-2560173772

feat: add BlockConditional

---

crates/consensus/src/conditional.rs
crates/rpc-types-eth/src/erc4337.rs

adds match functions to `TransactionConditional`
this will be used to determine if a conditional fn satisfies block attributes

feat: add match functions

---

crates/consensus-any/src/receipt/envelope.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs
crates/genesis/src/lib.rs
crates/network-primitives/src/traits.rs
crates/provider/src/fillers/gas.rs
crates/rpc-types-eth/src/transaction/receipt.rs
crates/rpc-types-txpool/src/txpool.rs

Some types are still using u128 for gas which is inconsistent. With this PR only gas price values are stored as u128

fix: use u64 for all gas values

---

crates/network-primitives/src/block.rs
crates/rpc-types-eth/src/block.rs

adds functions that make it easier to create these rpc in a builder like API.
this will allow more simplifications
https://github.com/paradigmxyz/reth/blob/d644900a8078db976cdbfb310a19df5df9b33125/crates/rpc/rpc-types-compat/src/block.rs#L114-L114

feat: add more builder style fns

---

crates/consensus/src/proofs.rs
crates/rpc-types-engine/src/payload.rs

ports reth's standalone fn 1:1
https://github.com/paradigmxyz/reth/blob/d644900a8078db976cdbfb310a19df5df9b33125/crates/rpc/rpc-types-compat/src/engine/payload.rs#L23-L93
additional V2.. conversions will follow to keep diffs low
this is additional simplification that will be unlocked by https://github.com/paradigmxyz/reth/pull/13518

feat: add tryfrom payloadv1 for block

---

crates/rpc-types-engine/src/payload.rs

feat: add tryfrom payload for block

---

crates/rpc-types-engine/src/payload.rs

ported from
https://github.com/paradigmxyz/reth/blob/d644900a8078db976cdbfb310a19df5df9b33125/crates/rpc/rpc-types-compat/src/engine/payload.rs#L227-L253

feat: misc payloadenvelopeinput conversions

---

crates/rpc-types-engine/src/payload.rs

ref
https://github.com/paradigmxyz/reth/blob/d644900a8078db976cdbfb310a19df5df9b33125/crates/rpc/rpc-types-compat/src/engine/payload.rs#L272-L275
no longer sure if the `try_into_block` fn isn't a potential footgun

feat: add try into block with sidecar

---

crates/eips/src/eip1898.rs

[Feature] update Display implementation on BlockNumberOrTag

---

crates/json-rpc/src/result.rs
crates/transport-http/src/hyper_transport.rs
crates/transport-http/src/reqwest_transport.rs

Review with whitespace disabled.

chore: simplify Service impls

---

crates/eips/src/eip2935.rs

chore: add history serve window

---

crates/consensus/src/block/mod.rs

forgot that we also need this for blockbody

chore: add arbitrary for blockbody

---

crates/consensus/src/block/mod.rs

we have this in reth's block type,
this seems reasonable, to prevent a ton of updates, but I'm not actually convinced

feat: add deref for block

---

crates/eips/src/eip7685.rs

we can prevent this entirely if we enforce this during serde, but having this check also doesn't hurt

fix: skip empty request objects

---

crates/network-primitives/src/block.rs
crates/rpc-types-eth/src/block.rs

these conversions were missing.
the rpc block to consensus has some caveats, but should be fine

feat: add conversions from rpc block to consensus

---

crates/eips/src/eip7685.rs

Closes https://github.com/alloy-rs/alloy/issues/1871
Adds more correctness for requests hashing

feat: sort and skip empty requests for hash

---

crates/consensus/src/block/header.rs
crates/consensus/src/block/mod.rs

useful helper fns when doing conversions

feat: add missing helper fns

---

crates/eips/src/eip1898.rs
crates/eips/src/eip2718.rs
crates/rpc-types-engine/src/error.rs

more core error impls
all of those could now use thiserror but I'd like to open a good first issue for this instead

chore: shift std::error impls to core

---

crates/signer-local/src/lib.rs

closes https://github.com/alloy-rs/core/issues/705

test: add parity test

---

crates/provider/src/provider/eth_call.rs
crates/provider/src/provider/trait.rs

DRY up some code a bit
- [n/a] Added Tests
- [n/a] Added Documentation

refactor: use the params struct in more places

---

crates/contract/Cargo.toml
crates/contract/README.md
crates/contract/src/call.rs
crates/contract/src/event.rs
crates/contract/src/instance.rs
crates/provider/src/builder.rs
crates/provider/src/ext/debug.rs
crates/provider/src/fillers/chain_id.rs
crates/provider/src/fillers/gas.rs
crates/provider/src/fillers/nonce.rs
crates/provider/src/layers/cache.rs
crates/provider/src/provider/trait.rs
crates/provider/src/provider/wallet.rs
crates/provider/src/utils.rs

Instantiate `RecommendedFillers` by default. 
- `RecommededFillers` are added when the `ProviderBuilder` is instantiated using `new()` i.e `ProviderBuilder::new()` will now return `FillProvider` with the recommended fillers instantiated.
- Users can opt-out of this behaviour using `.disable_recommended_fillers()`. 
For example, if a user want just wants `cached_nonce_management`. It can be achieved like so: 
```rust
let provider = ProviderBuilder::new()
.disable_recommended_fillers()
.with_cached_nonce_management()
.on_anvil();
```

feat(`provider`): instantiate recommended fillers by default

---

crates/consensus/src/block/mod.rs

adds a helper that provides the rlp length for the standalone header + body

feat: add rlp length helper

---

crates/consensus/src/transaction/mod.rs

Replaces magic numbers in impl of `Typed2718` for `TxEnvelope` with constants

chore(consensus): Replace magic numbers for tx type with constants

---

Cargo.toml
crates/provider/Cargo.toml
crates/provider/src/provider/trait.rs
crates/transport-http/Cargo.toml
crates/transport-http/src/hyper_transport.rs

Currently the `HyperTransport` uses the `HttpConnector` as the default connector making it impossible to use: `ProviderBuilder::new().on_builtin("https://..")` when the `hyper` feature is enabled as it will always throw "invalid URL, scheme is not http".
Use `HttpsConnector` from the `hyper_tls` lib as default in `HyperTransport`.

fix(`transport`): use `HttpsConnector` in `HyperTransport`

---

crates/transport-ipc/Cargo.toml
crates/transport-ipc/src/lib.rs

Right now this only reads a specific Json item, but it's trivial to make it read any json item. This would allow the logic to be reused for a server
Make the stream generic over `T: DeserializeOwned`, have the stream yield `Item`, set a default item to `PubSubItem` to avoid any breaking changes.

feat: make ReadJsonStream generic to allow reuse

---

crates/consensus-any/src/receipt/envelope.rs
crates/consensus/src/block/mod.rs
crates/consensus/src/constants.rs
crates/consensus/src/lib.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/pooled.rs
crates/consensus/src/transaction/recovered.rs
crates/consensus/src/transaction/typed.rs
crates/eips/Cargo.toml
crates/eips/src/eip2718.rs
crates/eips/src/lib.rs
crates/network/src/any/either.rs

Adds `Typed2718` as super trait to `Encodable2718` to remove redundancy

chore(eips): Add super trait `Typed2718` to `Encodable2718`

---

crates/rpc-types-mev/src/mev_calls.rs

Those are pretty much identical, and it is beneficial to unify so that it's possible to have something like
```rust
trait OverridableBlockEnv {
fn apply_overrides(&mut self, overrides: BlockOverrides);
}
```

chore: reuse `BlockOverrides` in `SimBundleOverrides`

---

crates/node-bindings/src/nodes/anvil.rs
crates/provider/src/provider/trait.rs

Currently, `AnvilInstance.child.stdout` is not being set again after initial parsing, resulting in `child.stdout` being always `None`. 
Set `child.stdout` after initial parsing has completed in `.spawn()`.

fix(`node-bindings`): reset `child.stdout` in `AnvilInstance`

---

crates/eips/src/eip1898.rs
crates/eips/src/eip7251.rs

alternative to 
https://github.com/alloy-rs/alloy/pull/1923
@DaniPopes

test: require serde features for tests

---

crates/json-rpc/src/error.rs
crates/json-rpc/src/lib.rs
crates/json-rpc/src/request.rs
crates/json-rpc/src/response/error.rs
crates/json-rpc/src/response/mod.rs
crates/json-rpc/src/response/payload.rs
crates/json-rpc/src/result.rs
crates/provider/src/ext/debug.rs
crates/provider/src/layers/cache.rs
crates/provider/src/provider/caller.rs
crates/provider/src/provider/eth_call.rs
crates/provider/src/provider/prov_call.rs
crates/provider/src/provider/root.rs
crates/provider/src/provider/trait.rs
crates/provider/src/provider/with_block.rs
crates/rpc-client/src/batch.rs
crates/rpc-client/src/call.rs
crates/rpc-client/src/client.rs
crates/rpc-client/src/poller.rs

Make the RPC trait system more clear and flexible, provide non-owned options requirements baked into the traits
* Rename `RpcParam` to `RpcSend` and `RpcReturn` to `RpcReceive` to make them clearer
* Add lifetimed versions of `RpcReturn` and `RpcObject` to allow borrowing from deserializers
* relax many bounds from `RpcObject` to either `RpcBorrow` or `RpcSend`, e.g. in `ResponsePayload::serialize_payload` we can relax to `RpcSend`
The implementation of `RpcRecv` is still **more** strict than `DeserializeOwned`, as it requires `+ 'static` rather than `for<'de> Deserialize<'de>`. This means that it is not iplemented on (e.g.) things that borrow from some non-deserializer context or environment during deserialization. Some parts of our future and streaming systems rely on this, and it seems …

refactor: change json-rpc trait names, relax bounds

---

crates/consensus/src/transaction/eip1559.rs

The `tx_type` method for `TxEip1559` is available only within the `consensus` crate, while it is available to external crates for all other `TxEip...` structs.
Change method to be available to external crates.

feat(consensus): make fn tx_type() public

---

README.md
RELEASE_CHECKLIST.md

Version number is out of date in documentation
Update to `0.10`, added updating the number as step into release process document

fix: version number of installation is out of date

---

crates/consensus/src/transaction/recovered.rs

we have certain tx traits implemented for references so `Recovered<&Tx>` can be useful,
this adds a helper just like `Option::cloned` to obtain a `Recovered<Tx>`

feat: add Recovered::cloned

---

crates/contract/src/call.rs

Contract calls like `contract.balanceOf` cannot be directly awaited despite the `IntoFuture` impl as it requires `Self: 'static`. Ref: https://github.com/rust-lang/rust/issues/63063.
Awaiting calls results in an ambiguous error for users. See https://t.me/ethers_rs/43016. 
```rust
let bal = contract.balanceOf(addr).await.unwrap()
// Error: argument requires that borrow lasts for `'static`
```
The appropriate way to call a contract is:
```rust
let bal = contract.balanceOf(addr).call().await.unwrap();
```
The above error doesn't suggest this. 
Remove the `IntoFuture` impl for `CallBuilder`. 
Users now *have* to use `.call()`. Moreover, using `.await` results in a slightly better error: `CallBuilder` is not a future.

fix(`contract`): rm IntoFuture for CallBuilder

---

crates/network-primitives/src/block.rs
crates/rpc-types-eth/src/block.rs

towards #1939
add calc tx root helper for the rpc response types
cc @Wollac

feat: add calc tx root fn for rpc types

---

crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/receipts.rs
crates/rpc-types-eth/src/log.rs
crates/rpc-types-eth/src/transaction/receipt.rs

towards #1939
adds helper conversion fn for the various receipt types to map logs and convert to primitives logs.
adds a from impl for the rpc txreceipt to convert the wrapped receipt envelope into an envelope with primitives logs
cc @Wollac

chore: add receipt conversion fns

---

crates/consensus/src/block/header.rs

Adds a couple convenience methods to check if hard forks are active in a given header

feat: couple convenience methods

---

crates/rpc-types-eth/src/block.rs

feat: add into sealed for rpc header

---

Cargo.toml
crates/provider/Cargo.toml
crates/provider/src/layers/cache.rs
crates/signer-gcp/Cargo.toml
crates/transport-ws/src/native.rs

Also remove schnellru as we already have lru

chore(deps): breaking bumps

---

crates/consensus/src/block/header.rs

now that we have configurable blobparams that are hardfork specific, this means we need to deal with a case where blobs are not active: `None`
https://github.com/paradigmxyz/reth/pull/14049
this adds helpers with default impl for this so that we don't need to use `maybe_params.map(|params| header.next_blob_fee(params))`

feat: introduce maybe helpers for blob calc

---

crates/consensus/src/block/mod.rs

adds missing generic for the ommers type, mirroring the block type:
https://github.com/alloy-rs/alloy/blob/69c424950caa23108942876af4f93e33e4bb4843/crates/consensus/src/block/mod.rs#L24-L24
otherwise we need an entirely new block+body type for things like:
https://github.com/paradigmxyz/reth/pull/13995

feat: add blockbody ommers generic

---

crates/consensus/src/block/mod.rs

we dont derive serde for tests by default to make test compile because we test serde only if serde feature is active

chore: dont enable serde in tests

---

crates/eips/src/eip7840.rs

silence warnings by feature gating helpers only needed for serde

chore: feature gate serde

---

crates/consensus/src/transaction/meta.rs

we settled on u64 for basefee.
this will remove some redundant casts in reth

chore!: use u64 for base fee in tx info

---

crates/provider/src/layers/cache.rs

closes #1940
inlines macro  and adds the required map

fix: map txcount resp

---

crates/rpc-types-mev/src/eth_calls.rs

Added missing `fast` option into `eth_sendPrivateTransaction` preferences.
Option is supported in flashbots and alchemy but missing in alloy. 
Nothing fancy, just added 1 optional boolean parameter.

Added fast option into PrivateTransactionPreferences

---

crates/provider/src/layers/cache.rs

chore: rm passthrough txcount request

---

crates/transport-http/src/hyper_transport.rs
crates/transport-http/src/reqwest_transport.rs

We currently only accept status code 200, whereas any code in 200..300 is a valid success code.

feat: use StatusCode::is_success instead of just OK

---

crates/pubsub/src/frontend.rs
crates/transport-http/src/hyper_transport.rs
crates/transport-http/src/reqwest_transport.rs
crates/transport/src/boxed.rs

Remove an unused and unusable layer of indirection, as we require `Transport: 'static`.

chore!: remove Service impls for &T

---

crates/provider/tests/it/ipc.rs
crates/provider/tests/it/main.rs
crates/provider/tests/it/ws.rs
crates/rpc-client/src/builder.rs
crates/rpc-client/src/client.rs

closes #1972
this is a bit cursed.
It described this in the docs but due to how:
https://github.com/alloy-rs/alloy/blob/bb77d2f8a2f587c9b220b8af2cd8cbcdd749c97d/crates/rpc-client/src/builder.rs#L44-L44
creates the transport service object if there's an additional layer, this downcast does not work:
https://github.com/alloy-rs/alloy/blob/bb77d2f8a2f587c9b220b8af2cd8cbcdd749c97d/crates/rpc-client/src/client.rs#L211-L212
the solution to this is a workaround that captures the Pubsubfrontend before we collapse the service builder.
this can still be bypassed manually via
https://github.com/alloy-rs/alloy/blob/bb77d2f8a2f587c9b220b8af2cd8cbcdd749c97d/crates/rpc-client/src/client.rs#L163-L163
but all the builtin transport fn should now capture the pubsubfrontend.
pubsubfrontend is just a channel …

fix: store pubsubfrontend clone in rpcinner

---

crates/node-bindings/src/nodes/anvil.rs

adds an option to configure the ipc path that anvil should use

feat: add avil ipc-path arg

---

crates/rpc-types-engine/src/payload.rs
crates/rpc-types-engine/src/sidecar.rs

this will make it easier on reth with generic H header type

chore: relax payload conversions with BlockHeader

---

crates/node-bindings/src/nodes/anvil.rs
crates/node-bindings/src/nodes/reth.rs
crates/provider/src/provider/trait.rs

fixes an issue introduced in #1920
closes #1983
what happens here is that, if stdout is not cleared the kernel buffer ends up blocking the program.
this makes keeping the stdout handle opt in

fix: opt-in to keep stdout

---

crates/alloy/Cargo.toml

Currently `full` doesn't enable most provider APIs and related rpc-types. 
Enable the trace, txpool, debug, anvil provider APIs, and rpc-types + pubsub feature.

feat(`meta`): enable pubsub,trace,txpool,debug,anvil apis via `full`

---

crates/provider/src/provider/trait.rs

While updating some stuff to 0.11.0 I noticed an outdated doc comment.
Removed the reference to a non existing generic.

fix(docs): update outdated Provider doc comment

---

crates/node-bindings/Cargo.toml
crates/node-bindings/src/nodes/anvil.rs
crates/provider/Cargo.toml
crates/provider/src/builder.rs

Currently, `AnvilInstance` doesn't expose `EthereumWallet` of its dev private keys.
One can create an `EthereumWallet` for the instance via `.keys()`, like:
```rust
let pk: PrivateKeySigner = anvil.keys()[0].into();
let wallet = EthereumWallet::new(pk);
```
This can be made simpler 
```rust
// Returns a wallet consisting of signers associated with all anvil private keys
let wallet = anvil.wallet().ok_or_eyre("No Keys Available")?;
```
Instantiate and store the `EthereumWallet` when anvil is spawned.

feat(`node-bindings`): expose anvil wallet

---

crates/provider/src/fillers/mod.rs

Although `FillProvider` isn't meant to be built directly, it's often used as return type of `ProviderBuilder::on_http`.
Since `Provider` uses this default, I think it makes sense to do the same for `FillProvider`.
Set the default `N = Ethereum` with `N: Network`.

chore(provider): default to `Ethereum` network in `FillProvider`

---

crates/transport/src/layers/retry.rs

closes #1999 
New `avg_cost` field added on the `RetryBackoffLayer` & `RetryBackoffService`. As issue suggests, `DEFAULT_AVG_COST` const was added to default to `17`
A setter `with_gas_cost` was added as well on `RetryBackoffLayer` to set the avg_cost if required
It made sense to me to create a const here for better maintainability and configure it on the layer level, lmk if another approach is to be followed here

feat(transport): made avg_cost to be configurable in retrybackoff

---

crates/eips/src/eip7840.rs

adds convenience fns for blob gas: `count * size`

feat: add helpers for the blob gas

---

crates/eips/src/eip1559/helpers.rs
crates/eips/src/eip1559/mod.rs
crates/provider/src/utils.rs

adds missing serde support to Eip1559Estimation type
moved to eips/1559 because seems useful there as well

chore: add serde support for Eip1559Estimation

---

crates/transport/src/error.rs

chore: nicer error message when HTTP body is empty

---

crates/eips/src/eip4844/env_settings.rs

chore: re-export kzgsettings

---

crates/rpc-types-engine/src/payload.rs

closing #2015
unsure about the following:
- maybe there is a way to do this in a less verbose way
- when adding a V4 struct in the future, a custom deserde for V2 will have to be added. maybe there is a solution that solves this more generally

custom deserde impl

---

crates/rpc-types-mev/src/common.rs
crates/rpc-types-mev/src/eth_calls.rs

Builder style functions for PrivateTransactionRequest
Added PrivateTransactionRequest's and inner properties implementation blocks containing builder fns

feat: builder fns for PrivateTransactionRequest and inner props (#1954)

---

crates/network/src/lib.rs
crates/network/src/transaction/mod.rs
crates/network/src/transaction/signer.rs

Closes: #2029 
This pr adds two unifying traits, `AnySigner` and `AnySignerSync`, to asynchronous (`Signer` + `TxSigner`) and synchronous (`SignerSync` + `TxSignerSync`) Ethereum signing functionalities, enabling dynamic dispatch (e.g., via `Box<dyn AnySigner>`).

feat: add dynamic dispatch helper trait for (`Signer` +`TxSigner`) and (`SignerSync` + `TxSignerSync`)

---

crates/provider/src/layers/anvil.rs

Some questions:
1. Not sure what kind of test to add for this
2. Does returning `&Arc<T>` feel right or should i return a cloned `Arc<T>`?
There is no way to access some of the `AnvilInstance` methods like `keys()`, `addresses()` right now when you spawn the anvil provider with `ProviderBuilder::on_anvil_XXX` methods.
Exposing a reference to inner `AnvilInstance` will allow to access those methods instead of writing a wrapper delegate method for all the underlying methods.

feat(provider): expose inner `AnvilInstance` from `AnvilProvider`

---

crates/contract/src/eth_call.rs
crates/provider/src/provider/eth_call/mod.rs

adds builder style fns to ethcall to configure account overrides

feat: add helpers for account overrides

---

crates/contract/src/eth_call.rs

This is being removed here: https://github.com/alloy-rs/core/pull/863
It causes valid data to be rejected: https://t.me/ethers_rs/43150.

fix: don't validate when ABI decoding

---

crates/contract/src/multicall.rs
crates/provider/src/provider/multicall/inner_types.rs
crates/provider/src/provider/multicall/mod.rs

1. We can't use `?` on a multicall `Result<(), Failure`> since `Failure` doesn't implement `StdError`.
2. `clear` should return an `Empty` multicall builder otherwise it's of no use.
1. Use `thiserror::Error` for `Failure`
2. Return `Empty` multicall builder on `multicall.clear()`

fix(`multicall`): impl Error for `Failure` +  clear returns `Empty` builder.

---

crates/eips/src/eip4844/sidecar.rs

makes it possible to create a sidecar from blobs encoded as hex or byte slice
this way we don't need to import c_kzg if we have hex test data for example

feat: add helpers to create a BlobSidecar

---

crates/consensus/Cargo.toml
crates/consensus/src/error.rs
crates/consensus/src/lib.rs
crates/network-primitives/src/block.rs

for consuming conversions, the
https://github.com/alloy-rs/alloy/blob/8ce1c76b94155d71b6aff75096fc7f0fd1fb58fa/crates/rpc-types-eth/src/transaction/error.rs#L5-L10
isn't super convenient.
this introduces a helper error that allows returning the value on an error but is also Error, which makes it useful for `?` propagation.
moved this into consensus because this will be very useful when doing consensus type conversion across network types

feat: introduce error helper and fallible conversion

---

crates/consensus/src/transaction/mod.rs

adds a helper to obtain the function selector if it's a call.
the additional .is_call could be optimized by overriding it, or we add function_selector_unchecked.

feat: add function selector helper

---

crates/consensus/src/transaction/envelope.rs

Useful helper to avoid unnecessary matching in applications that use both TypedTransaction and TxEnvelope types.

chore: add From<Signed<TypedTransaction>> for TxEnvelope

---

crates/provider/src/ext/debug.rs

Add new `debug_codeByHash` method from here https://github.com/paradigmxyz/reth/pull/14524 .
I need some advice about the CI integration test with reth. I thought I just try out what the result will be. (reth version, db state, etc.)

feat(provider): add debug_codeByHash method

---

crates/consensus/src/transaction/recovered.rs

Useful when operating with `Recovered<&Tx>`

feat: derive `Copy` for `Recovered`

---

crates/rpc-types-mev/src/eth_calls.rs

Sadly, mev-geth made the choice to encode the gas-related and state block number fields as JSON numbers instead of `QUANTITY`: https://github.com/flashbots/mev-geth/blob/fddf97beec5877483f879a77b7dea2e58a58d653/internal/ethapi/api.go#L2212-L2220
So to keep things backwards compatible I had to remove some of the `ally_serde::quantity` usage.
Also the unit tests wasn't really comparing the before and after, I was actually surprised to see that `alloy_serde::quantity` handles deserializing raw numbers, but they were in turn encoded as hex strings.
Examples of `reth` output before and after:
<details>
```
> cast rpc eth_callBundle '{"txs":["0x02f87382426802840337db58840337db6882b0199494373a4919b3240d86ea41593d5eba789fef3848872386f26fc1000080c080a040d920de9390a95442d0f44db365fa1673dbb67a80b5260 …
```

fix(rpc-types-mev): compatibility with mev-geth responses.

---

crates/contract/src/error.rs
crates/json-rpc/src/response/error.rs

Currently, we have a method for decoding `ErrorPayload`'s and `contract::Error`'s into one of the `SolError`'s present in the `SolInterface`.
`fn as_decoded_error<E: SolInterface>(data) -> Option<E>`.
We also want a method that attempts decoding to a specific `SolError` and returns a `Result`. 
- Add method `fn as_decoded_error<E: SolError>(data) -> Result<E, alloy_sol_types::Error>`
- [Breaking] Rename previous `as_decoded_error<E: SolInterface>` to `as_decoded_interface_error`. Avoidable but I think this naming is better, and breaking pre-1.0 makes sense.

feat(`contract`): decode as `SolError`

---

crates/rpc-types-eth/src/transaction/receipt.rs

Currently, we don't have any direct way to decode the receipt logs into a typed `SolEvent` log. See: https://t.me/ethers_rs/43321
- Add a `fn decoded_log<E: SolEvent>(&self) -> Option<Log<E>>` to `TransactionReceipt`. 
This enables users to do this:
```rust
let receipt = counter.increment().send().await.unwrap().get_receipt().await.unwrap();
let log = receipt.decoded_log::<Counter::Increment>();
assert!(log.is_some());
```
instead of 
```rust
let receipt = counter.increment().send().await.unwrap().get_receipt().await.unwrap();
let receipt = receipt.into_primitives_receipt();
let logs = receipt.logs();
let increment_log = Counter::Increment::decode_log(&logs[0], false).unwrap();
```

feat(`rpc-types`): decode log from receipt

---

crates/rpc-types-eth/src/transaction/request.rs

This PR adds a method to set the blob gas fee for a transaction following the same pattern as other tx fields.
This can currently be done via `tx.set_max_fee_per_blob_gas()` which doesn't use the same builder pattern.
there is a similar method name in [`TransactionBuilder4844`](https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types-eth/src/transaction/request.rs#L717), but it doesn't take the same parameter.

chore: add blob gas method to TransactionRequest impl

---

crates/rpc-types-mev/src/mev_calls.rs

The `mev_simBundle` RPC should return "rpc" log objects that contain `transactionHash`, `blockNumber` etc.  Currently we are using the "primitive" version that just contains the "consensus" fields.
Use `alloy_rpc_types_eth::Log` instead of `alloy_primitives::Log`.

fix(rpc-types-mev): SimBundleLogs should contain all logs fields.

---

crates/rpc-types-engine/src/error.rs

Hash values displayed in the message are swapped. We "want" the hash computed in execution but "got" the hash coming from consensus.

fix(engine): Fix BlockHash display message

---

crates/rpc-types-debug/src/debug.rs

Including the hashes gives callers an unnecessary reason to trust the client. They should just hash the returned preimages. Also saves on RPC bandwidth. Motivated by feedback on this geth PR: https://github.com/ethereum/go-ethereum/pull/30613#issuecomment-2531732780
reth PR: https://github.com/paradigmxyz/reth/pull/14503

feat: remove preimage hashes from execution witness

---

crates/consensus/src/transaction/mod.rs
crates/network/src/any/either.rs

this makes it possible to get an `Either` instance with two different tx types

feat: add conversions for UnknownTxEnvelope

---

crates/network/Cargo.toml
crates/network/src/any/mod.rs
crates/network/src/lib.rs
crates/rpc-types-eth/src/block.rs

feat: introduce dedicated types for Any type aliases

---

crates/consensus/src/lib.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs

we also need this because the status type uses flatten which isn't compatible with bincode 👍

feat: add bincode compat for receipt

---

crates/consensus/src/signed.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/recovered.rs
crates/network/src/any/mod.rs
crates/network/src/any/unknowns.rs
crates/rpc-types-eth/src/transaction/mod.rs

Adds helper `try_into_recovered` for `Signed` and integrates `Recovered` into RPC transaction response

feat: integrate `Recovered` into more types

---

Cargo.toml
crates/consensus/Cargo.toml
crates/consensus/src/signed.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/pooled.rs
crates/consensus/src/transaction/typed.rs

closes #1987
Lazily computes hash for the transaction in `Signed`. Methods relying on hash are now bounded by `T: RlpEcdsaTx` which works for all of the transactions we have but would likely get trickier for custom signature usecases

feat: use `OnceCell` for `Signed::hash`

---

crates/consensus/src/error.rs

this is commonly used as `ValueError<Self>`, we dont expect that the value will be accessed a lot so we can box this to keep the type smol

chore: box value

---

crates/provider/src/builder.rs
crates/provider/src/layers/mock.rs

Currently, `ProviderBuilder::mocked` returns `(MockProvider, Asserter)`.
Returning `Asserter` is redundant, since it can accessed via the provider, `provider.asserter()`.
We also don't have an easy way to build a mocked provider for a specific network.
- Remove `Asserter` from return type.
- Add `mocked_network<Net: Network>`

chore(`provider`): fix `mocked` ret type

---

crates/consensus/src/transaction/recovered.rs
crates/network/src/any/mod.rs
crates/network/src/any/unknowns.rs
crates/rpc-types-eth/src/transaction/mod.rs

`Recovered` can be used for any signed object not just transactions. 
- Renames the methods and changes docs slightly to indicate the above

chore(`consensus`)!: rename `Recovered` methods

---

crates/consensus/src/lib.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs

Renames `TypedTransaction` to `EthereumTypedTransaction` and makes it generic over `Eip4844` variant. `TypedTranaction` is still kept as a type alias making this change non-breaking
We can apply same approch to `TxEnvelope` and and de-duplicate it with `PooledTransaction` https://github.com/alloy-rs/alloy/blob/9442fefece4bd78587f3a5db8f6b871a2a426f7b/crates/consensus/src/transaction/pooled.rs#L32

feat: add Eip4844 variant generic to TypedTransaction

---

crates/eips/src/eip7685.rs

the filter function defined in the eip https://eips.ethereum.org/EIPS/eip-7685 is:
```
def compute_requests_hash(block_requests: Sequence[bytes]):
m = sha256()
for r in block_requests:
if len(r) > 1:
m.update(sha256(r).digest())
return m.digest()
```

fix: filter out requests with len 1

---

crates/eips/src/eip1559/constants.rs

Hi! I fixed broken links in the `constants.rs` file related to Optimism's transaction costs documentation.

fix: broken links `eip1559/constants.rs`

---

Cargo.toml
crates/provider/Cargo.toml
crates/provider/src/blocks.rs
crates/rpc-client/Cargo.toml
crates/rpc-client/src/poller.rs

Don't spawn poller in a task by default by using the stream! macro to yield responses instead.
Requirement for https://github.com/alloy-rs/alloy/issues/1318.
~~Unfortunately not spawning it means we lose the ".instrument" span attached to the spawned task future. I have not found a way to "instrument" a stream without writing a Stream utility ourselves.~~
Just decided to claude it.

feat: remove poller task indirection

---

crates/transport/Cargo.toml
crates/transport/src/layers/fallback.rs
crates/transport/src/layers/mod.rs

Having a provider be able to consume a list of transports can increase both availability and performance, both desirable features of many applications that need a connection to Ethereum.
Several issues such as https://github.com/alloy-rs/alloy/issues/1938 and https://github.com/alloy-rs/alloy/issues/1760 outline a feature like this in Alloy. 
Other libraries such as [Viem](https://viem.sh/docs/clients/transports/fallback.html) and [Ethers.js](https://docs.ethers.org/v5/api/providers/other/#FallbackProvider) also have something similar.
This PR implements `FallbackLayer` and `FallbackService`, following the usual `tower` abstractions. Most notably, the layer here works with a `Vec<S>` because this service is meant for managing a list of transports.
When sending a request to a provider …

feat: `FallbackLayer` transport

---

crates/consensus/src/transaction/envelope.rs

This is regarding the following [issue](https://github.com/alloy-rs/alloy/issues/2191)
Added `Encodable` and `Decodable` for `Signed<T>`

Add encodable and decodable for `Signed<T>`

---

crates/pubsub/src/frontend.rs

When attempting to increase the PubsubFrontend channel size to accommodate higher throughput, the current handling of channel_size turns out to be inaccessible. This is because it is stored as an AtomicUsize, but is not stored with an Arc making it independent for each PubsubFrontend during cloning.
This poses an issue when initializing a PubsubFrontend using WsConnect:
```rust
let mut ws_config = WebSocketConfig::default();
ws_config.max_frame_size = None;
ws_config.max_message_size = None;
let mut ws = WsConnect::new(self.ws_url.clone()).with_config(ws_config);
let client = ClientBuilder::default().ws(ws).await?;
client.set_channel_size(self.pubsub_channel_size);
let provider: _WsProvider = ProviderBuilder::new().on_client(client);
```
During the ClientBuilder.ws() initialization of …

fix(pubsub): wrap channel_size with Arc

---

crates/rpc-types-eth/src/account.rs

adds helper, ported from regular account type

feat: add EIP1186AccountProofResponse::is_empty

---

.config/zepter.yaml
crates/alloy/Cargo.toml
crates/consensus-any/Cargo.toml
crates/consensus/Cargo.toml
crates/rpc-types-eth/Cargo.toml
crates/rpc-types/Cargo.toml

Found when running cargo-semver-checks, which fails to build alloy-rpc-types-eth because of a missing propagation

chore: propagate arbitrary feature

---

crates/provider/Cargo.toml
crates/provider/src/fillers/mod.rs
crates/provider/src/layers/batch.rs
crates/provider/src/provider/erased.rs
crates/provider/src/provider/mod.rs
crates/provider/src/provider/subscription.rs
crates/provider/src/provider/trait.rs

The `GetSubscription` future type was introduced in https://github.com/alloy-rs/alloy/pull/2203
Remove it's reliance on `N: Network` by using `WeakClient`
- Remove `N: Network` generic from `GetSubscription` by using `WeakClient`

chore(`provider`): use `WeakClient` in `GetSubscription`

---

crates/provider/src/ext/admin.rs
crates/provider/src/fillers/mod.rs
crates/provider/src/provider/erased.rs
crates/provider/src/provider/trait.rs

Follow up on https://github.com/alloy-rs/alloy/pull/2203
Use `GetSubscription` type for subscription functions in Provider trait and refractor affected areas

feat(`provider`): apply `GetSubscription` to trait

---

crates/contract/src/call.rs

```rust
error[E0283]: type annotations needed
--> crates/contract/src/call.rs:838:29
|
838 |             max_fee_per_gas.to(),
|                             ^^ cannot infer type of the type parameter `T` declared on the method `to`
|
= note: multiple `impl`s satisfying `alloy_primitives::Uint<256, 4>: alloy_primitives::ruint::UintTryTo<_>` found in the `ruint` crate:
- impl<BITS, LIMBS, BITS_DST, LIMBS_DST> alloy_primitives::ruint::UintTryTo<alloy_primitives::Uint<BITS_DST, LIMBS_DST>> for alloy_primitives::Uint<BITS, LIMBS>
where the constant `BITS` has type `usize`, the constant `LIMBS` has type `usize`, the constant `BITS_DST` has type `usize`, the constant `LIMBS_DST` has type `usize`;
- impl<BITS, LIMBS, T> alloy_primitives::ruint::UintTryTo<T> for alloy_primitives::Uint<BITS, LIMBS> …
```

test: fix inference fail in test

---

crates/eips/src/eip7594.rs
crates/eips/src/lib.rs

Add PeerDAS constants necessary for sidecar validation. Defined in https://github.com/ethereum/consensus-specs/blob/9d377fd53d029536e57cfda1a4d2c700c59f86bf/specs/fulu/polynomial-commitments-sampling.md#cells. See https://github.com/ethereum/execution-apis/pull/630 for validation methods.

feat: eip7594 constants

---

crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/pubsub/src/managers/active_sub.rs

closes #2242
one more bincode helper type -.-

feat: add bincode compat for receipt envelope

---

crates/provider/src/utils.rs

This PR updates crates/provider/src/utils.rs to reference the correct MetaMask source file for gas fee estimation. The previous link pointed to a non-existent file (fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.ts#L56). It has been updated to GasFeeController.ts, which contains the correct gas fee estimation logic.
If there’s a better reference or an alternative approach, let me know, and I’ll update it.

docs: update reference to MetaMask gas estimation

---

crates/pubsub/src/service.rs

ref #2252
@yash-atreya I believe what's happening here is that the reconnect is also failing, in the context of #2252 this seems to happen if "Connection reset by peer" == os error 104 usually, which could indidate that the socket is unavailable.
there could be a race condition on the remote that then righout rejects the new attempt.
I think it would be reasonable to introduce a retry + sleep mechanism on reconnect as well

chore: add error message for reconnect failure

---

crates/pubsub/src/service.rs

Closes #2252 
- retry mechanism in `PubsubService`
- Retries at least 10 times before exiting
- Interval between retires is 3 seconds

fix(`pubsub`): retry connecting to backend

---

crates/consensus/src/transaction/envelope.rs

chore: hide input mut

---

crates/consensus/src/transaction/recovered.rs

Closes #2264 
Adds two helper methods to `Recovered` :
1. `into_encoded`
2. `into_encoded_with(self, Bytes)`

feat(`consensus`): WithEncoded helpers

---

crates/consensus/src/lib.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/mod.rs

This PR intends to close https://github.com/paradigmxyz/reth/issues/15377. At the moment, I could use some tips to see if the implementation is per intent.
Issue regarding why the test fails is noted in a comment below
- implement similar for `OpTxEnvelope`
- write additional test for `test_transaction_signed_bincode_roundtrip`

chore: port transaction envelope bincode compat function

---

crates/network-primitives/src/block.rs

these can be useful for if the format depends on a bool

feat: add conditional conversions for BlockTransactions

---

crates/network/src/ethereum/wallet.rs

We don't have a method to set the default signer (amongst existing signers) using the address after the `EthereumWallet` instantiation. One needs to use `register_default_signer` and pass the signer that may already exist.
- Add `set_default_signer` that set the default signer using provided address.
- Errors out if signer is not registered.

feat(`eth-wallet`): set default signer helper

---

crates/consensus/src/transaction/eip4844.rs

Implementations for `TxEip4844` have strict bounds to this type in cases where they only require a reference.
To allow implementing traits with bounds relaxed to any type that can extract reference to `TxEip4844`, the following standard trait implementations are added:
* `AsRef` for `TxEip4844`
* `AsMut` for `TxEip4844`

feat(eip4844): Implement `AsRef` and `AsMut` for `TxEip4844`

---

crates/rpc-types-engine/src/payload.rs

Each EIP-7594 style sidecar should contain `blobs.len() * CELLS_PER_EXT_BLOB` cell proofs.

fix: cell proofs in `BlobsBundleV2::take`

---

crates/provider/src/heart.rs

Using `Provider::watch_pending_transaction` to wait for 1 confirmation can be simpler if we allow you to write `provider.watch_pending_transaction(tx_hash.into())`
Impl `From<TxHash>` for `PendingTransactionConfig`

feat: add `From<TxHash>` for `PendingTxConfig`

---

crates/eips/src/eip4844/engine.rs

See https://github.com/ethereum/execution-apis/pull/630. It's supposed to be
```
{
blob: bytes,
proofs: bytes48[]
}
```

fix: `BlobAndProofV2`

---

crates/rpc-types-trace/src/otterscan.rs

The original link to the Otterscan custom JSON-RPC documentation was outdated and returned a 404.  
Replaced the broken link with the correct versioned URL pointing to [`v2.6.1`](https://github.com/otterscan/otterscan/blob/v2.6.1/docs/custom-jsonrpc.md).  
No code logic was changed.

chore: Fixed 404 link

---

crates/rpc-types-debug/src/debug.rs

This PR adds an `ancestor_headers` field to the ExecutionWitness. This allows one to use the execution witness to statelessly execute a block, by adding the headers needed to verify state reads and BLOCKHASH opcode executions.

chore!: Add `ancestor_headers` to `ExecutionWitness`

---

crates/pubsub/src/handle.rs
crates/pubsub/src/service.rs
crates/transport-ws/src/native.rs
crates/transport-ws/src/wasm.rs

Closes #2252 
- Adds `max_retries` and `retry_interval` param to `WsConnect`
- These are propagated to the `PubsubService` handling retries via the `ConnectionHandle`
- Default `max_retries: 10` and `retry_interval: 3s`

feat(`ws`): retry mechanism in WsConnect

---

crates/provider/src/provider/multicall/mod.rs

Closes #2306 
- Adds two new builder methods to the dynamic builder for adding `CallItem`'s to the builder

feat(`multicall`): add `CallItem` to dynamic builder

---

crates/json-rpc/README.md
crates/json-rpc/src/lib.rs

Small fix in `alloy-json-rpc` doc to link to `alloy-transport` crate after it was split in different crates.

fix(json-rpc): transport crate deadlinks in doc

---

crates/consensus/src/signed.rs
crates/consensus/src/transaction/envelope.rs

adds fn to obtain `Recovered<&>`

feat: add to recovered ref fns

---

crates/provider/src/provider/trait.rs
crates/transport-http/Cargo.toml

https://github.com/alloy-rs/alloy/pull/1899 added the `HttpsConnector` for hyper behind the `hyper-tls` feature. However, this feature isn't being enabled via the `hyper` feat. See: https://github.com/alloy-rs/examples/actions/runs/14471175068/job/40585218348?pr=212
- Enable the `hyper-tls` feature via `hyper`
- This makes the HttpsConnector the default which can be used with both http and https schemes

fix(`transport`): enable hyper-tls via hyper feature

---

crates/consensus-any/src/block/header.rs
crates/consensus/src/block/header.rs
crates/network/src/lib.rs
crates/provider/src/builder.rs

**Description:**
This pull request addresses several typographical errors in the documentation comments across multiple files. The changes include:
1. **File:** `crates/consensus-any/src/block/header.rs`
- Corrected "differencies" to "differences".
- Fixed "avaialble" to "available" in the comment for the `nonce` function.
2. **File:** `crates/network/src/lib.rs`
- Corrected "implment" to "implement" in the utility comment for `IntoWallet`.
3. **File:** `crates/provider/src/builder.rs`
- Fixed "reseting" to "resetting" in the comment for `disable_recommended_fillers`.
These changes improve the readability and professionalism of the code documentation.

docs: Fix Typos in Documentation Comments

---

crates/provider/src/ext/trace/with_block.rs
crates/provider/src/provider/with_block.rs
crates/rpc-types-engine/src/payload.rs
crates/transport-http/src/layers/auth.rs

This PR fixes several typos in the codebase:
- Corrects "accomodate" to "accommodate" in trace/with_block.rs
- Corrects "varous" to "various" in provider/with_block.rs
- Fixes string literal for "gasUsed" in payload.rs
- Corrects "perfom" to "perform" in layers/auth.rs

Fix typos in comments and string literals

---

crates/contract/src/eth_call.rs
crates/node-bindings/src/nodes/anvil.rs
crates/provider/src/layers/cache.rs
crates/provider/src/provider/eth_call/mod.rs

This PR corrects minor grammar mistakes in documentation comments across several files to improve readability:
In eth_call.rs, replaced duplicated the the with a single the.
In anvil.rs, fixed the the ipc server to the ipc server.
In cache.rs, removed duplicated the in the the maximum number.
In mod.rs, removed the unnecessary the before given in the given [AccountOverride].
These are small but meaningful changes that help maintain a clean and professional codebase. No functional code was affected.

Fix grammar typos in documentation

---

crates/consensus/src/receipt/envelope.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/tx_type.rs

extracts the txtype enum to its own mod.
this was a mess earlier

chore: move txtype to dedicated mod

---

crates/eips/src/eip4844/mod.rs
crates/eips/src/eip4844/sidecar.rs
crates/eips/src/eip7840.rs

mark constants deprecated and introduce new ones with _CANCUN suffix.
this should show a warning when the constants are used (most likely incorrectly)

chore: mark 4844 constants deprecated

---

crates/consensus/src/transaction/envelope.rs
crates/rpc-types-eth/src/call.rs
crates/rpc-types-eth/src/transaction/mod.rs
crates/rpc-types-eth/src/transaction/request.rs

we can relax those so that these work with all eip4844 variants

chore: relax rpc tx conversions

---

crates/rpc-types-eth/src/block.rs

adds smol helpers to return the header with a function

chore: add helpers to rpc block type

---

crates/pubsub/src/service.rs

closes #2361
we can't use 0 here because broadcast:.channel panics and this value can trigger a new channel

fix: use existing channel capacity for reconnect

---

crates/consensus-any/src/lib.rs
crates/consensus-any/src/receipt/envelope.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs

copying an entire bloom isn't super cheap especially when it's used to compute the logs bloom.
we can add this in a non breaking way by introducing bloom_ref -> Cow

feat: add bloom_ref

---

crates/provider/tests/it/ws.rs
crates/pubsub/src/service.rs

closes #2362
we don't track request ids in the service because this only dispatches raw requests, simply using 1 for the id here should be fine 
eth_unsubscribe requires an id because this is a regular request
```
{"jsonrpc":"2.0", "id": 1, "method": "eth_unsubscribe", "params": ["0x9cef478923ff08bf67fde6c64013158d"]}
```
ref https://docs.alchemy.com/reference/eth-unsubscribe

fix: send eth_unsubscribe with id

---

crates/rpc-types-eth/src/filter.rs
crates/rpc-types-trace/src/geth/mod.rs

It the filter is empty - If the filter is empty
is noop - is a noop
config are historically - config is historically

docs: minor correction

---

crates/rpc-types-debug/Cargo.toml
crates/rpc-types-debug/src/debug.rs
crates/rpc-types-debug/src/lib.rs

chore: Make `alloy-rpc-types-debug` `no_std` compatible

---

crates/provider/src/builder.rs

I changed the deprecated note for `on_mocked_client` which was pointing to `on_mocked_client` to the correct `connect_mocked_client`.
This change only makes documentation updates.

docs: Fix deprecated note

---

crates/rpc-types-beacon/src/requests.rs

on relay, these re often supplied as null so we should support this as well

fix: requests deserde nullable fields

---

crates/node-bindings/src/nodes/anvil.rs
crates/signer-local/src/private_key.rs

@yash-atreya we can use this to simplify some examples:
```
let alice: PrivateKeySigner = anvil.keys()[0].clone().into();
let bob: PrivateKeySigner = anvil.keys()[1].clone().into();
```

feat: some covenience signer impls

---

README.md

By integrating these badges, users can immediately see which versions are published without ever leaving GitHub. Because Shields.io updates badges automatically whenever a new version is released, we no longer need to maintain these by hand. In addition, including standardized version badges helps our project adhere to the conventions commonly used in the Rust ecosystem, giving our documentation a more professional and polished appearance.

docs (README.md): integrating crates.io badges

---

crates/rpc-types-engine/src/payload.rs

Use `BlobTransactionSidecarEip7594` in `BlobsBundleV2`.

fix(rpc-types-engine): use 7594 sidecar in `BlobsBundleV2`

---

crates/consensus/src/transaction/envelope.rs

removes the native recovery fn in favor of the trait impls

chore!: remove shadowed recovery fn

---

crates/consensus/src/transaction/eip1559.rs

This is a follow up from https://github.com/alloy-rs/eips/pull/37.
Under some conditions, Filecoin RPC providers return the details of EIP-1559 transactions with the `accessList` attribute set to `null` instead of `[]`, an empty array (see https://github.com/filecoin-project/lotus/issues/12214).
Example of such a transaction:
```bash
> curl -X POST \
-H "Content-Type: application/json" \
--data '{
"jsonrpc":"2.0",
"method":"eth_getTransactionByHash",
"params":["0x96ca611648da9a1cb430a9124491b97bbd6fc0e0d8851b1a6fb261fdd128b1c8"],
"id":1
}' \                                     
https://api.node.glif.io/rpc/v1 | jq
{
"id": 1,
"jsonrpc": "2.0",
"result": {
"chainId": "0x13a",
"nonce": "0xc94",
"hash": "0x96ca611648da9a1cb430a9124491b97bbd6fc0e0d8851b1a6fb261fdd128b1c8",
"blockHash": …
```

fix(`consensus`): Allow `"accessList": null` when deserializing EIP-1559 transactions.

---

crates/rpc-types-eth/src/transaction/request.rs

This is related to https://github.com/paradigmxyz/reth/issues/16231, to upstream `TxType` derive to `TransactionRequest`
This PR adds a new function in `TransactionRequest` with logic in https://github.com/paradigmxyz/reth/blob/3ac3e6ff11bac485272d023969bfd0377b820165/crates/optimism/rpc/src/eth/call.rs#L70-L80

chore: add a new fn for TxType derivation

---

crates/consensus/src/block/header.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/transaction/envelope.rs

This pull request addresses minor documentation and test name improvements across several consensus modules to enhance clarity and correctness:
Fixed multiple typos such as "compatibl" → "compatible", "evelope" → "envelope", and "whcih" → "which".
Updated a test function name to accurately reflect the struct it tests: test_receipt_evelope_bincode_roundtrip → test_receipt_envelope_bincode_roundtrip.
These changes are purely cosmetic and do not affect runtime behavior or logic.
This PR improves code readability and documentation accuracy, making the codebase more maintainable.

docs: Fix typos and improve documentation clarity in serde-related modules

---

crates/provider/src/builder.rs

towards #2478 
Introduces `new_with_network` constructor for the `ProviderBuilder`. This enables the provider to be built with the recommended fillers of the provided network via the `RecommendedFillers trait`

fix(`provider`): introduce `new_with_network` constructor

---

crates/rpc-types-eth/src/filter.rs

~~this would be an expensive workaround~~
instead of a lazy single bloom, this computes the original BloomFilter again, that was incorrectly changed in #2140 and stores that in a oncelock instead of the single bloom
ref https://github.com/paradigmxyz/reth/issues/16354

fix!: check each bloom

---

crates/eips/src/eip4844/sidecar.rs
crates/eips/src/eip7594/sidecar.rs

chore: rm redundant commitment copy

---

crates/eips/src/eip4844/sidecar.rs
crates/eips/src/eip7594/sidecar.rs

Fix issue #2481: Remove unnecessary collection into Vec in `versioned_hashes` method.
The `versioned_hashes` method in `BlobTransactionSidecarVariant` was unnecessarily collecting the iterator results into a Vec, which could impact performance. Both implementations of the underlying method were doing the same operation on commitments.
Created a common `VersionedHashIter` struct that implements the Iterator trait to handle versioned hash generation from commitments. This allows:
1. All related methods to return the same concrete type instead of `impl Iterator`
2. Removes the need for `.collect()` in `BlobTransactionSidecarVariant::versioned_hashes`
3. Maintains the same functionality while being more memory efficient

refactor: create VersionedHashIter to remove unnecessary collect()

---

crates/consensus/src/block/mod.rs
crates/eips/src/eip2718.rs

introduces a new default Encodable2718 trait functions that encodes the value directly into `WithEncoded` and map fn on the block type.

feat: Encodable2718:into_encoded

---

crates/eips/src/eip1898.rs
crates/eips/src/lib.rs

BlockNumberOrTag supports only:
- HEX String - an integer block number
- String "latest" - for the latest mined block
- String "finalized" - for the finalized block
- String "safe" - for the safe head block
- String "earliest" for the earliest/genesis block
- String "pending" - for the pending state/transactions
And EIP-1898 does not all calls that use `BlockNumber` like `eth_getBlockByNumber` and doesn't list raw integers as supported.
Added a module that deserializes either a BlockNumberOrTag, or a simple number

feat: Add lenient_block_number_or_tag to support raw integers

---

crates/rpc-types-eth/src/transaction/request.rs

missing from impl, allows us to get rid of some wrappers in foundry and can just call .into()

feat: from tx for withotherfields

---

crates/provider/src/provider/sendable.rs

I understand the doc was made `hidden` because as the doc comments suggest this should be considered an internal type. But this internal type is exposed in the `TxFiller` trait and `FillProvider` type and I think since it is already public type because being returned in public API the docs should still be accessible. The warning in the doc comment should be enough for the readers.

doc: unhide `SendableTx`

---

crates/signer-ledger/Cargo.toml
crates/signer-ledger/src/lib.rs
crates/signer-ledger/src/signer.rs
crates/signer-ledger/src/types.rs
crates/signer-ledger/src/utils.rs

EIP-7702 introduces a new delegation flow that lets an EOA authorize a separate delegate to act on its behalf.  
To support this, the Ledger signer needs to be able to encode the TLV-style payload and send it to the device for signing. 
- Add a new function `sign_auth` which does the following :
- Internally builds the TLV payload  
- Then streams it over the APDU `SIGN_EIP7702_AUTHORIZATION` instruction.

Adding support for signing 7702 authorizations

---

crates/consensus/src/receipt/envelope.rs

these are quite useful for doing type conversions

chore: add ReceiptEnvelope helpers

---

crates/provider/tests/it/mock.rs
crates/transport/src/mock.rs

When writing tests for complex logic with multiple JSON RPC calls it's hard to understand a response to what request is being expected from the mock provider.
Include request metadata in the error message displayed when the asserter queue is empty.

improve mock transport error messages

---

crates/rpc-types-eth/src/transaction/receipt.rs

these can be relaxed so that these can be called with different inner receipt types

chore: relax receipt fn bounds

---

crates/provider/src/blocks.rs
crates/rpc-client/src/poller.rs

Changes pollers and heartbeat to be more tolerant to errors returned from client. Right now node going down for several seconds would cause pollers or heartbeat tasks to get terminated after several retries which might be critical and thus forces any user reliying on those to implement handling of such cases.
With this PR we're now enver ending the task and keep querying the node indefinitely instead

fix: make pollers and `Heartbeat` more reliable

---

crates/eips/src/eip1559/helpers.rs

EIP1559: `max_fee_per_gas` is not `base_fee_per_gas` (proofs: [1](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md?plain=1#L212), [2](https://github.com/alloy-rs/alloy/blob/84bbfd79222361a07a8febc102e2844bb326e155/crates/provider/src/utils.rs#L119))

Fix misleading doc comment

---

crates/provider/src/provider/trait.rs
crates/rpc-types-mev/src/eth_calls.rs

When testing the struct with different builders I realized that only the block number is expected in hex representation, but all other number should be integers. This also reflects the example in https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint#eth_sendbundle
To increase it to maximum compatibility `block_number`, `min_timestamp`, `max_timestamp` and `refund_percent` accept hex + integer, but serialize to integer (except for `block_number`). I added tests to ensure this.

chore(rpc): `eth_sendBundle` allow hex and integer for input and output always integer

---

.config/zepter.yaml
crates/consensus/src/receipt/envelope.rs

crates/consensus/src/receipt/envelope.rs
type flag 2 → type flag 3
Why: EIP-4844 uses type ID 3. Docs were wrong, now fixed.
.config/zepter.yaml
expose → exposes
A it outside → A is outside
Why: Grammar fixes for clarity in CI config comments.

docs: fix incorrect type flag doc for EIP-4844 + minor grammar in CI config

---

crates/rpc-types-trace/src/geth/mod.rs

Add `as_str()` method to `GethDebugTracerType` that returns the tracer type as a string representation.
- For built-in tracers, returns their standard names (e.g., "callTracer", "prestateTracer")
- For JS tracers, returns the captured string which could be JavaScript code or a custom identifier
This method provides a convenient way to get the string representation of any tracer type for use in RPC calls or logging.

feat(rpc-types-trace): add as_str method to GethDebugTracerType

---

crates/provider/Cargo.toml
crates/provider/src/ext/anvil.rs

In Foundry the ERC20 endpoints return `()`.
Make the ERC20 endpoints in alloy also return `()`, otherwise you get an error `Error("invalid type: null, expected 32 bytes, represented as a hex string of length 64, an array of u8, or raw bytes", line: 1, column: 4)`
Added tests to make sure it passes.

fix: ERC20 endpoints return type

---

crates/rpc-types-eth/src/account.rs

- Add `is_empty_code_hash()` method to check if code hash is empty
- Add `code_hash()` method to compute the account's code hash
- Add `is_empty()` method to check if account is empty (zero balance, nonce, and empty code)

feat(rpc-types-eth): add helper methods to AccountInfo

---

crates/provider/src/provider/trait.rs

- Add `block_number_for_id` helper method to the Provider trait
- Returns block number directly for numeric BlockId values
- Fetches full block for hash and tag identifiers to extract the block number
- Returns None if block doesn't exist
This helper method provides a convenient way to resolve block numbers from any `BlockId`, which is useful when you need to work with block numbers but receive a `BlockId` as input (e.g., from user input or other APIs).

feat(provider): add block_number_for_id helper method

---

crates/rpc-types-mev/src/eth_calls.rs

Changes for `EthSendBundle`, `EthBundleHash` and removal of `SendBundleResponse`:
- `bundle_hash` in `EthBundleHash` is optional. Not all builders return such a bundle hash
- Remove duplicate struct `SendBundleResponse` in favor of `EthBundleHash`
- New `extra_fields` as known from `ChainConfig` allow the user to add builder specific fields 
Again a breaking change, but I have the feeling that it is worth it, for a better usability.
Update: Initially I replaced `Vec` with `HashSet` for fields like `reverting_tx_hashes`, but this would potentially lead to a non-deterministic bundle hash calculation. I reverted this change.

chore(rpc-types-mev): improve bundle API flexibility

---

crates/rpc-types-engine/src/payload.rs

Adds a `from_block_unchecked` method to `ExecutionData` that creates an instance directly from a block.
This follows the same pattern used in op-alloy's implementation and provides a convenient way to construct `ExecutionData` with both payload and sidecar extracted from the block in a single call.
The method delegates to `ExecutionPayload::from_block_unchecked` which handles the version detection and sidecar extraction internally.

feat: add from_block_unchecked to ExecutionData

---

.github/workflows/ci.yml

Pin nextest version to avoid CI failures from latest release, following the same approach as https://github.com/paradigmxyz/reth/pull/16887.
This prevents potential CI breakage from automatic updates to newer nextest versions.

ci: pin nextest to v0.9.98

---

crates/consensus/src/block/mod.rs

Adds a builder-style `with_header` method to the `Block` type that allows replacing the block's header.
- Added `pub fn with_header(mut self, header: H) -> Self` method to `Block<T, H>`
- The method follows the builder pattern, taking ownership of self and returning the modified block
- Only replaces the main block header, not ommer headers (documented in the method's doc comment)

feat: add with_header method to Block type

---

crates/pubsub/README.md
crates/rpc-client/src/client.rs

This PR corrects a minor spelling mistake, changing `implementor` to `implementer` in the documentation and code comments.
This change affects the following files:
- `crates/pubsub/README.md`
- `crates/rpc-client/src/client.rs`

docs: Correct typo 'implementor' to 'implementer

---

crates/consensus/src/transaction/envelope.rs
crates/tx-macros/src/expand.rs
crates/tx-macros/src/lib.rs
crates/tx-macros/src/parse.rs

Similarly to #2594 adds a way to feature-gate `arbitrary` implementation and applies it to the implementation for `EthereumTxEnvelope` to avoid the kona bug

feat(tx-macros): add `arbitrary_cfg` parameter

---

crates/rpc-client/README.md

The current example in alloy-rpc-clients README does not compile, with a "type must be known at this point" on the `batch.add_call` calls + a wrong argument type error, which creates friction for users wanting to get started.
* `batch` must be mutable: `let mut batch = ....`
* `block_number` must have explicit `U64` type
* `balance` must have explicit `U256` type
* second argument of add_call must be a reference

chore: update code example in rpc-client README

---

Cargo.toml

New version of alloy-trie was released https://crates.io/crates/alloy-trie/0.9.0
Bump alloy-trie to v0.9.0

deps: bump alloy-trie to 0.9.0

---

crates/rpc-types-eth/src/simulate.rs

The `TransactionRequest` is currently hard-coded to a concrete type. This means that the `SimBlock` and all components that depend on it will not work for custom transaction requests.
Add generic `TxReq` with `TransactionRequest` as a default.

feat(rpc): Add generic `TxReq` to `SimBlock`

---

crates/rpc-types-eth/src/call.rs

The `TransactionRequest` is currently hard-coded to a concrete type. This means that the `Bundle` and all components that depend on it will not work for custom transaction requests.
Add generic `TxReq` with `TransactionRequest` as a default.

feat(rpc): Add generic `TxReq` to `Bundle`

---

crates/network/src/any/builder.rs
crates/network/src/ethereum/builder.rs
crates/network/src/transaction/builder.rs

To remove reliance on concrete type `TransactionRequest` and use only the abstraction `TransactionBuilder` in its place, currently there is no way to remove the nonce.
This feature is required for RPC methods like `eth_call`. Lack of nonce makes the EVM set it.
Add methods to `TransactionBuilder` that take the nonce out of the transaction.

feat(network): Add method to remove nonce from transaction using `TransactionBuilder`

---

crates/consensus/src/signed.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/recovered.rs

Closes https://github.com/paradigmxyz/reth/issues/17068.
- Add `recover_signer_unchecked_with_buf` to `SignerRecoverable` 
- Add `recover_signer_unchecked_with_buf` impls for `Signed<T>` and `EthereumTxEnvelope<Eip4844>`

feat: add recover_signer_unchecked_with_buf to `SignerRecoverable` trait

---

crates/rpc-types-eth/src/simulate.rs

The `TransactionRequest` is currently hard-coded to a concrete type. This means that the `SimulatePayload` and all components that depend on it will not work for custom transaction requests.
Add generic `TxReq` with `TransactionRequest` as a default.

feat(rpc): Add generic `TxReq` to `SimulatePayload`

---

crates/rpc-types-eth/src/transaction/request.rs

Currently when I have `TransactionRequest` and I want to sign it using a LocalSigner:
```rs
let mut tx = tx_req
.build_typed_tx()
.unwrap() // TypedTransaction
.eip1559()
.unwrap() // &Tx1559
.clone();
let signature = wallet.sign_transaction_sync(&mut tx)?;
``` 
Could be simplified as
```rs
let mut tx = tx_req.build_1559(); // Tx1559
let signature = wallet.sign_transaction_sync(&mut tx)?;
```

make tx build fns public

---

crates/consensus/Cargo.toml
crates/consensus/src/crypto.rs

One motivation for this is to allow downstream users to plug in their own implementation of certain functions. The downstream user we have in mind are zkVM guest program implementers where they could add precompiles using this strategy.

feat: Add dynamic crypto backend for ecrecover

---

crates/consensus/src/receipt/envelope.rs

adds a new helper to create an envelope from a raw receipt + txtype

feat: from_typed to envelope

---

crates/node-bindings/src/nodes/anvil.rs

Added builder-style methods to set custom environment variables when spawning anvil instances.
This PR adds `env()` and `envs()` methods to the `Anvil` builder, following the same pattern as the existing `arg()` and `args()` methods. This allows users to configure anvil's behavior through environment variables.
- Added `envs: Vec<(OsString, OsString)>` field to store environment variables
- Added `env(key, value)` method to set a single environment variable
- Added `envs(pairs)` method to set multiple environment variables at once
- Applied environment variables in `try_spawn()` using `cmd.envs()`
```rust
let anvil = Anvil::new()
.env("RUST_LOG", "debug")
.env("CUSTOM_VAR", "value")
.envs([("VAR1", "value1"), ("VAR2", "value2")])
.spawn();
```
This maintains consistency with the existing …

feat: add environment variable support to Anvil builder

---

crates/node-bindings/src/nodes/anvil.rs

chore: set NO_COLOR for anvil

---

crates/rpc-types-eth/src/call.rs
crates/rpc-types-eth/src/simulate.rs

The `Default` bound on `TxReq` is given by the derive macro for the trait. But since `TxReq` is only in a vector, there is no need to have this bound.
Implement `Default` manually for types with `TxReq` generic without `Default` bound.

feat(rpc): Implement `Default` for types with `TxReq` generic without `Default` bound

---

crates/rpc-types-engine/src/payload.rs

For SSZ when using `SubmitBlockRequest::from_ssz_bytes(...)`, the enum default to `Fulu` without the custom deserialization for an `Electra` payload. Same as for the serde it compares the amount of proofs/commits to determine the version.
https://github.com/alloy-rs/alloy/blob/fe4bfe2be3d78345d32c8bbd542123e2c099a146/crates/rpc-types-beacon/src/relay.rs#L205-L209
Test with `#[cfg(not(debug_assertions))]` are not executed in the CI, locally they are fine. Same concept as the serde tests. Run:
`cargo test -p alloy-rpc-types-engine --features ssz ssz_blobsbundlev2 --release`

feat(rpc-types-engine): custom ssz decode to distinguish Fulu and Electra payload

---

crates/consensus/src/transaction/eip2930.rs

The documentation for the `access_list` field in `TxEip2930` has been improved to provide better context and developer experience.
- A direct link to the EIP-2930 specification is now included in the documentation for the `access_list` field.
- The comment has been reformatted to follow standard Rustdoc style, with a concise summary line followed by a more detailed explanation.
This change makes it easier for developers to find the relevant specification and understand the purpose of the access list.

Add EIP-2930 link and clarify access_list docs

---

crates/rpc-types-eth/src/filter.rs

Adds a new `filter_receipts` method to `Filter` that creates an iterator for filtering logs from nested receipt structures. This addresses the request in paradigmxyz/reth#17344 for a helper iterator type.
- Added `FilterReceiptsIter` struct that implements `Iterator<Item = Log>`
- Added `filter_receipts` method to `Filter` that returns the iterator
- The iterator accepts any nested iterator structure (e.g., `Vec<Vec<Receipt>>`)
- Properly handles iteration over blocks → receipts → logs with filtering
```rust
let filter = Filter::new()
.address(some_address)
.event_signature(some_topic);
let logs: Vec<_> = filter.filter_receipts(receipts).collect();
```
This provides a clean, composable way to extract and filter logs from multiple blocks of receipts without manually iterating through the …

feat: add filter_receipts iterator for filtering logs from receipts

---

crates/provider/src/ext/mev/mod.rs
crates/rpc-types-mev/src/eth_calls.rs

Adding support for `eth_sendBlobs` even with PeerDAS ahead.
See for details: https://docs.titanbuilder.xyz/api/eth_sendblobs

feat(mev): add support for `eth_sendBlobs` method to mev api

---

crates/provider/src/ext/mev/mod.rs
crates/rpc-types-mev/src/mev_calls.rs

Support for `mev_sendBundle`. As always not all builder return a hash.
I renamed it here to `MevSendBundle` to match the method name as for all others before.  In the docs it is called `MevSendBundleParams`, but I would stick now to that pattern. `SendBundleRequest` is marked as deprecated.
https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint#mev_sendbundle

feat(mev): implement `send_mev_bundle` method

---

crates/provider/src/provider/multicall/inner_types.rs

accepting bool is a bit weird most of the time because false is always default so this ends up being called with true all the time
cc @joshieDo

feat: add with_failure_allowed

---

crates/provider/README.md
crates/rpc-client/src/poller.rs

Adds a new check in the filter poller to see if the server has dropped 
FilterPoller will error indefinitely if the server reboots or drops the filter for any reason
- Add a new finished state
- move to finished when the server's error response method includes `filter not found`
- I have checked that the string `filter not found` is used by reth, geth, and nethermind
- drive-by: implement fused stream

fix: poller breaks if server drops the filter

---

crates/provider/Cargo.toml
crates/provider/src/builder.rs

Quick fix for some missing API
Includes drive-by fix for a lint issue with http dep spec

feat: allow ProviderBuilder to use TransportConnect and PubSubConnect

---

crates/rpc-client/src/batch.rs

Replace "CallState" with "BatchFuture" in the panic! message for invalid poll state to match the enum name

fix(batch.rs): reference BatchFuture in panic message

---

crates/rpc-types-trace/src/geth/mod.rs

To import `CallKind` like `use alloy_rpc_types_trace::geth::CallKind` same as other public types such as `CallFrame`

chore(rpc-types-trace): Re-export `CallKind`

---

.github/workflows/ci.yml

Node 24 compatibility: switch all jobs to actions/checkout@v5. Requires runner v2.327.1+. Pure maintenance, behavior unchanged.
Ref: https://github.com/actions/checkout/releases/tag/v5.0.0

ci: bump actions/checkout to v5

---

crates/rpc-types-trace/src/parity.rs

Added missing helper methods to `Delta<T>` for accessing inner values. These methods follow the same pattern as the existing `is_*` methods and match the pattern used in other enums like `Action` and `TraceOutput` in the same file.
Added three new const methods to `Delta<T>`:
- `as_added()` - Returns `Option<&T>` for the `Added` variant
- `as_removed()` - Returns `Option<&T>` for the `Removed` variant  
- `as_changed()` - Returns `Option<&ChangedType<T>>` for the `Changed` variant
Note: `as_unchanged()` was intentionally not added since the `Unchanged` variant contains no data.

feat: add as_* helper methods to Delta<T>

---

crates/consensus/src/transaction/typed.rs

missing convenience fn that does the same as `into_signed().into()` but nicer

chore: add into_envelope helper

---

Cargo.toml
crates/consensus/Cargo.toml
crates/consensus/src/crypto.rs
crates/transport/Cargo.toml
crates/tx-macros/Cargo.toml

Breaking bumps for internal deps, not a breaking API change.
Remaining:
```
alloy-hardforks   0.2.0   -> 0.3.0 
gcloud-sdk        0.27    -> 0.28.1
tokio-tungstenite 0.26    -> 0.27.0
rand              0.8     -> 0.9.2 
jsonrpsee         0.25    -> 0.26.0
jsonrpsee-types   0.25    -> 0.26.0
coins-ledger      0.12    -> 0.13.0
coins-bip32       0.12    -> 0.13.0
coins-bip39       0.12    -> 0.13.0
```

chore(deps): internal dep bumps

---

README.md

Update the version number in the README installation example to match the current workspace version (1.0.27) instead of the outdated 1.0.1.

docs: update version in installation example from 1.0.1 to 1.0.27

---

crates/rpc-client/src/builtin.rs

Adds a new convenience method `connect` to `BuiltInConnectionString` that combines parsing a connection string and connecting to it in a single async call.
- Added `connect` async method that:
- Takes a connection string as `&str`
- Parses it using `from_str`
- Immediately connects using `connect_boxed`
- Returns `Result<BoxTransport, TransportError>`
This simplifies the common pattern:
```rust
// Before
BuiltInConnectionString::from_str(s)?.connect_boxed().await?
// After
BuiltInConnectionString::connect(s).await?
```

feat(rpc-client): add connect convenience method

---

Cargo.toml
crates/tx-macros/src/serde.rs

- ref https://github.com/serde-rs/serde/pull/2980
- closes https://github.com/alloy-rs/alloy/issues/2885

fix: use serde private mod patch notation

---

crates/rpc-types-engine/src/jwt.rs

When I'm running `cargo test` locally, this test sometimes failed:
```
failures:
---- jwt::tests::validation_error_iat_out_of_window stdout ----
thread 'jwt::tests::validation_error_iat_out_of_window' (35216979) panicked at crates/rpc-types-engine/src/jwt.rs:395:9:
assertion failed: matches!(result, Err(JwtError::InvalidIssuanceTimestamp))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
jwt::tests::validation_error_iat_out_of_window
test result: FAILED. 40 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```
After reviewing the test code, seems there's a time gap between the test creation and the validation, so change the diff to a larger time to avoid the flaky.

fix(jwt): jwt iat offset test flaky

---

.github/workflows/ci.yml

This PR introduces CodeQL code scanning as part of `ci.yml` initially just focused on Github actions as it is fast to run.
https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql
Results are reported privately in the `security` tab.
This workflow was derived from the default workflow example Github provides enhanced with concurrency cancel in progress, updated cron to run daily and allow workflow dispatch. Trigger on cron, pull requests and pushes to master.
This can later be expanded to cover Rust (currently in preview mode & will require custom build / caches to run efficiently).

chore(`ci`): enable CodeQL as part of `ci.yml`

---

crates/alloy/Cargo.toml

in https://github.com/alloy-rs/alloy/pull/2865 we removed tls by default because this was always enabling openssl by default with no easy way to opt out.
this restores tls support by default

chore: enable rustls by default

---

crates/consensus/Cargo.toml
crates/consensus/src/lib.rs
crates/tx-macros/src/serde.rs

Removes dependency on serde `Content` in favor of `serde_json::Value`. This allows to avoid usage of private APIs but means that we can't deseraize non-json data anymore

fix: don't use serde private API

---

crates/signer-local/src/lib.rs
crates/signer-local/src/mnemonic.rs

Adds convenience methods and iterator support to `MnemonicBuilder` for easier signer generation from mnemonic phrases.
- Added `from_phrase_nth` and `try_from_phrase_nth` for creating signers at specific derivation indices
- Added `from_phrase_first` and `try_from_phrase_first` convenience methods for the first signer (index 0)
- Implemented `IntoIterator` for `MnemonicBuilder` to generate multiple signers with incrementing indices
- Added `MnemonicSignerIter` iterator type that yields signers for derivation paths `m/44'/60'/0'/0/{index}`
```rust
// Create signer at specific index
let signer = MnemonicBuilder::from_phrase_nth(phrase, 5);
// Create first signer (index 0)
let signer = MnemonicBuilder::from_phrase_first(phrase);
// Iterate over multiple signers
let builder = …
```

feat(signer-local): add mnemonic builder helpers and iterator

---

crates/rpc-types-engine/src/jwt.rs

The CreateDir error in JwtSecret::try_create_random used the target file path instead of the parent directory, producing misleading diagnostics (“failed to create dir <file-path>”). Since the error variant and message explicitly refer to a directory, the path should be the actual directory that failed to be created. This change improves error clarity without affecting behavior or APIs.

fix(jwt): report parent directory path in try_create_random

---

crates/consensus/src/error.rs
crates/network/src/any/error.rs

The `UnsupportedTransactionType` error lacks a constructor and conversions except into `TransactionBuilderError`, which is untested.
Add a constructor and more conversions for `UnsupportedTransactionType`.
Test display of `UnsupportedTransactionType` error and its conversion into `TransactionBuilderError`

test: Test display of `UnsupportedTransactionType` error and its conversion into `TransactionBuilderError`

---

crates/rpc-types-eth/src/filter.rs
crates/rpc-types-eth/src/pubsub.rs

Remove serde(deny_unknown_fields) from SubscriptionKind and FilterId. This attribute has no effect at the enum container level (it applies to structs or struct-like enum variants), so keeping it is misleading. Behavior is unchanged; improves clarity and consistency.

chore(rpc-types-eth): remove useless serde deny_unknown_fields on enums

---

crates/transport-http/src/layers/auth.rs

Critical logical error in JWT token validation that could lead to authentication vulnerabilities.
- **Before**: Old tokens were considered valid, new tokens were rejected
- **After**: Tokens are properly validated based on time difference within latency buffer
- **Before**: Tokens created with future timestamp (`iat = now + 60s`)
- **After**: Tokens created with current timestamp (`iat = now`)
- Added clear English comments explaining validation logic
- Enhanced method documentation for better maintainability

fix: JWT Token Validation Logic in AuthService

---

crates/rpc-client/src/call.rs

The panic! macro is used directly without needing to import core::panic.
This fixes an unused import warning.

chore: remove unused core::panic import

---

crates/rpc-types-beacon/src/payload.rs

- Remove #[serde_as(as = "DisplayFromStr")] from ExecutionPayloadHeader.block_number (type String).
- For String this adapter is a no-op: serde already serializes/deserializes JSON strings natively. Keeping it adds noise and suggests a conversion that does not occur.
- All other DisplayFromStr uses remain on numeric/bignum types to enforce beacon “quoted decimal” semantics.

chore(beacon): remove redundant DisplayFromStr on header.block_number

---

crates/consensus/src/transaction/hashable.rs

both traits have the same name fn name so we should be explicit here

chore: use fqs for tx_hash_with_type forwarding

---

crates/provider/src/provider/multicall/inner_types.rs

Change MulticallError::DecodeError formatting from “could not decode” to “could not decode: {0}” to surface the underlying alloy_sol_types::Error.

feat(provider): include inner cause in DecodeError message

---

crates/signer-gcp/src/signer.rs

Drop redundant fmt::Debug from imports in signer.rs.
Aligns with actual usage (custom Debug impl) and reduces noise.

chore(signer-gcp): remove unused fmt::Debug import

---

crates/consensus/src/transaction/recovered.rs

Fix deprecated attribute references in `Recovered<T>` that pointed to non-existent methods

fix(consensus): correct deprecated method references in Recovered<T>

---

crates/rpc-types-beacon/src/relay.rs

- Change IncorrectGasLimit.actual and IncorrectGasUsed.actual from B256 to u64, and update variant docs to reference gas limit/used.
- Gas fields are u64 across execution payloads and beacon serde (e.g., rpc-types-engine ExecutionPayloadV1/V2/V3), so using B256 was inconsistent and misleading.
- This prevents downstream type mismatches and makes error reporting accurate.

fix(beacon): use u64 for gas equality errors

---

crates/consensus/src/crypto.rs

Remove redundant cfg branches; both OnceLock and OnceBox expose get() -> Option<&T>, so a single implementation is sufficient. Keep cfg in install_default_provider due to differing set signatures.

refactor(consensus): unify try_get_provider body across std/no_std

---

crates/provider/src/provider/trait.rs

- cargo doc in CI was failing because the [`TxFiller`] link pointed to crate::TxFiller
- the type lives under crate::fillers, so every PR was hitting a rustdoc::broken-intra-doc-links error
- updated the doc comment so the doc job turns green again
- cargo doc --workspace --all-features --no-deps --document-private-items

fix(provider): correct TxFiller rustdoc link

---

crates/rpc-client/src/poller.rs

Remove misleading TODO in crates/rpc-client/src/poller.rs claiming lack of current-thread spawning.
PollerBuilder::into_stream already polls on the current thread as documented.

chore: remove outdated TODO about current-thread polling

---

crates/provider/src/layers/cache.rs

- Add .with_block_id(block) when building RequestType for eth_getBlockReceipts.
- Without setting block_id, has_block_tag() always returned false, causing tag-based requests (latest/pending/safe/finalized) to be cached and potentially serve stale data.
- This change aligns get_block_receipts with the layer’s documented policy and existing macros that avoid caching for non-deterministic block identifiers.

fix(cache): prevent caching for tag-based BlockId in get_block_receipts

---

crates/signer/src/signer.rs

cfg_attr already expands to async_trait, so the extra attribute was redundant and removed

chore: deduplicate Either async_trait attribute

---

crates/eips/src/eip4844/mod.rs
crates/eips/src/eip4844/sidecar.rs
crates/rpc-types-beacon/Cargo.toml
crates/rpc-types-beacon/src/sidecar.rs

`eth/v1/beacon/blob_sidecars` endpoint is now [deprecated](https://github.com/ethereum/beacon-APIs/pull/546) in favor of `eth/v1/beacon/blobs` which only returns blob bytes. This PR adds `GetBlobsResponse` type for it.
Not sure if `BeaconBlobBundle` is used for anything else but we might want to deprecate it as well

feat(beacon-types): `GetBlobsResponse`

---

crates/serde/src/lib.rs

Description
- What: Replace serialize_str(&format!("{x:x}")) with collect_str(&format_args!("{x:x}")) in crates/serde/src/lib.rs.
- Why: Eliminates an intermediate String allocation on a hot serialization path, improving performance and reducing allocator pressure.
- How: Use Serializer::collect_str with format_args! to write directly to the serializer without allocating.

perf(serde): avoid allocation in B256 hex serialization

---

crates/eip7547/src/summary.rs

The custom Serialize for InclusionListStatusV1 emits exactly two entries: status and validationError, but the serializer was initialized with serialize_map(Some(3)). This mismatch is incorrect and may cause unnecessary allocations. Aligning the size hint to 2 matches the actual output and mirrors patterns used elsewhere (e.g., PayloadStatus, JSON-RPC Response), ensuring accurate serialization behavior and clearer intent.

fix(eip7547): InclusionListStatusV1 serialize_map size hint
