alloy-rs/alloy

crates/rpc-types/src/eth/transaction/access_list.rs
crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/signature.rs
crates/rpc-types/src/eth/transaction/tx_type.rs
crates/rpc-types/src/eth/transaction/typed.rs

We need RLP encoding and decoding in the transaction related types.
Add them. Follows `reth-primitives`'s and foundry's anvil rlp implementation as closely as possible, using alloy rlp.

feat(`rpc-types`): RLP encoding/decoding for transaction types

---

crates/providers/src/provider.rs

We need a way to issue raw requests for the `rpc` cheatcode in foundry.
Add a `raw_request` function to `TempProvider` that allows sending arbitrary requests, with arbitrary params, expecting an arbitrary result. Of course, this function isn't object safe though.

feat(`TempProvider`): `raw_request`

---

README.md
crates/transport/README.md

The original crate name was "alloy-transport," but in several places in the documentation, it was written as "alloy-transports." 
Also, it was causing broken links.

fix: Modify the transport crate name in documents and fix the link

---

crates/json-rpc/src/packet.rs
crates/json-rpc/src/request.rs

Current implementation will serialize the request twice: `Reqeust<Params>` -> `SerializedRequest` -> `hyper/reqwest request's json body`.
Replace `RequestPacket::serialize(&self)` with  `RequestPacket::serialize(self)`, we can avoid the second serialize for hyper client.

avoid unnecessary serialize for RequestPacket.

---

.github/scripts/install_test_binaries.sh
.github/workflows/ci.yml
Cargo.toml
crates/json-rpc/src/response/error.rs
crates/json-rpc/src/response/mod.rs
crates/rpc-client/Cargo.toml
crates/rpc-client/src/client.rs
crates/rpc-client/src/lib.rs
crates/rpc-client/tests/it/ipc.rs
crates/rpc-client/tests/it/main.rs
crates/rpc-types/src/eth/filter.rs
crates/transport-ipc/Cargo.toml
crates/transport-ipc/README.md
crates/transport-ipc/src/connect.rs
crates/transport-ipc/src/lib.rs
crates/transport-ipc/src/mock.rs
deny.toml

Adds interprocess-based IPC pubsub backend.

feature: interprocess-based IPC

---

crates/rpc-types/src/eth/block.rs
crates/rpc-types/src/eth/mod.rs
crates/rpc-types/src/eth/other.rs
crates/rpc-types/src/eth/transaction/receipt.rs

Right now we don't have support for additional fields on both `Block` and `TransactionReceipt`, and we need support for these as foundry and other projects make use of the equivalent field on ethers types. This specifically makes supporting L2 blocks/receipts easier, as we can accomodate their additional field.
Add the `OtherFields` struct which can be transparently deserialized, and add it to `Block` and `TransactionReceipt`.

feat: support for additional fields on TransactionReceipt and Block

---

crates/rpc-types/src/eth/transaction/mod.rs

Also needed for this type, see #67.

feat: add `other` fields support in `Transaction`

---

crates/rpc-types/src/eth/block.rs

Mirroring https://github.com/paradigmxyz/reth/pull/5732. mix hash is not always set on other networks, so it should be an optional field.
Make it optional.

chore(`rpc-types`): make mix hash optional

---

crates/pubsub/src/ix.rs
crates/pubsub/src/managers/active_sub.rs
crates/pubsub/src/managers/in_flight.rs
crates/rpc-client/src/call.rs
crates/rpc-types/src/eth/block.rs
crates/transport/src/boxed.rs

chore: clean up fmt::Debug impls

---

crates/rpc-types/src/eth/block.rs
crates/signer-aws/src/signer.rs

feat: improve block transactions iterator

---

crates/rpc-types/src/eth/trace/parity.rs

this pr is to remove missdocs in parity.rs file

removed missdocs in parity.rs

---

crates/rpc-types/src/eth/log.rs
crates/rpc-types/src/eth/mod.rs

Came across the following use case:
- Retrieve logs with `Provider::get_logs()` that returns a `Vec` of `alloy_rpc_types::Log`
- Then decode logs using `SolEvent::decode_log_object()` that accept a `alloy_primitives::Log`
So I needed to convert `alloy_rpc_types::Log` to `alloy_primitives::Log`, hence this PR.

Impl TryFrom<alloy_rpc_types::Log> for alloy_primitives::Log

---

crates/json-rpc/src/notification.rs

fix: deserialize EthNotification from params field

---

crates/rpc-types/src/eth/transaction/mod.rs

Need to expose this type to migrate reth to use alloy types.

chore: expose op receipt fields

---

crates/rpc-types/src/eth/block.rs

When fetching uncle blocks, these blocks never contain a `transactions` field. This means that normal serialization into a `Block` can fail as `BlockTransactions` doesn't have a default and therefore will just not be added to the `Block` struct at all, causing a serde failure.
In the case the field is missing, simply include the field as default with an `BlockTransactions::Uncle` instance.

fix(`rpc-types`): set Uncle as default for BlockTransactions

---

crates/consensus/src/lib.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/network/src/lib.rs
crates/network/src/transaction/common.rs
crates/network/src/transaction/mod.rs
crates/signer-ledger/src/signer.rs
crates/signer-trezor/Cargo.toml
crates/signer-trezor/src/signer.rs
crates/signer-trezor/src/types.rs
crates/signer/src/lib.rs
crates/signer/src/signer.rs
crates/signer/src/wallet/private_key.rs

feat: implement sign_transaction on Trezor

---

crates/providers/src/provider.rs

The formats of parameters in the `eth_sendRawTransaction`, `trace_block`, and `eth_getBlockReceipts` methods are invalid.
```diff
- self.inner.prepare("trace_block", block).await
+ self.inner.prepare("trace_block", (block, )).await
```
```diff
{
"method": "trace_block",
- "params": "latest",
+ "params": [
+   "latest"
+ ],
"id": 0,
"jsonrpc": "2.0"
}
```
```rust
use alloy_providers::provider::{Provider, TempProvider};
use alloy_rpc_types::BlockNumberOrTag;
use anyhow::Result;
#[tokio::main]
async fn main() -> Result<()> {
let provider = Provider::try_from("https://rpc.ankr.com/eth/")?;
let traces = provider.trace_block(BlockNumberOrTag::Latest).await?;
for trace in traces {
println!("{:?}", trace)
}
Ok(())
}
```
```plaintext
Error: Server returned an error response: ErrorPayload code …
```

fix(providers): some methods have invalid formats for parameters

---

crates/rpc-types/src/eth/call.rs
crates/rpc-types/src/eth/transaction/request.rs

unblocks further alloy migration on anvil (foundry), as we need extra fields on rpc tx requests.
Add them

feat(`rpc-types`): add support for other fields in call/txrequest

---

crates/rpc-types/src/eth/call.rs

CallRequest needs to be hash for anvil, and it doesn't actually need the additional fields for now. We can always re-add them later if so.
Make it hash, remove other fields.

chore(`rpc-types`): make CallRequest hash

---

crates/providers/src/provider.rs

The provider cannot distinguish between non-existent blocks and blocks without transactions when using the `eth_getBlockReceipts` method.
- The block exists, but there are no transactions.
```json
{
"jsonrpc": "2.0",
"id": 0,
"result": []
}
```
- The block does not exist.
```json
{
"jsonrpc": "2.0",
"id": 0,
"result": null
}
```
Use `Option` to distinguish between `[]` and `null`.

fix(providers): receipts of unmined blocks should be null

---

crates/json-rpc/src/packet.rs
crates/json-rpc/src/response/payload.rs

Add some helper functions to ResponsePacket

chore: add helper functions to ResponsePacket

---

crates/rpc-trace-types/src/parity.rs

I think this part was copied over from reth so I'm not sure if this is a bug we've had or not, but `is_create` for Parity traces currently check if the `Action` is a call, not a create.

bug: correct `is_create` condition

---

crates/rpc-engine-types/src/payload.rs
crates/rpc-types/src/eth/transaction/blob.rs
crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/request.rs

this should be in a separate module

chore: move blob tx sidecar

---

crates/rpc-types/src/eth/filter.rs

helper function to check if the filter configured to match pending block
originally from: https://github.com/paradigmxyz/reth/pull/6108

feat: helper function to check pending block filter

---

crates/providers/src/provider.rs

fix (maybe) https://github.com/foundry-rs/foundry/issues/6855
See links in comments

fix: use U256 for eth_getStorageAt

---

crates/consensus/src/transaction/legacy.rs

The chain id was not being populated when decoding a signed legacy tx, leading to decoding issues.
Closes #125
Populate the chain id param when decoding.

fix(`consensus`): populate chain id when decoding signed legacy txs

---

crates/consensus/src/transaction/envelope.rs

The `Encodable2718` implementation for `TxEnvelope` uses the wrong type flag for EIP-1559 transactions.

fix(consensus): correct TxType flag in EIP-2718 encoding

---

crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/optimism.rs
crates/rpc-types/src/eth/transaction/receipt.rs
crates/rpc-types/src/eth/transaction/request.rs

We should have the op types as a separate module. Closes #113
Add a separate module for op types and their from impls.

feat(`rpc-types`): add optimism module and refactor types

---

crates/consensus/src/transaction/envelope.rs
crates/eips/src/eip2718.rs

Closes #141.
TxEnvelope wasn't able to properly decode txs due to a few issues with the eip-2718 `network_decode` impl. Namely, as the issue says:
- The original buffer was getting modified when decoding the header instead of being copied, leading to issues decoding legacy txs.
- The last check was wrong—we should only perform the check if we have a header.
Correct the checks.

fix(`eips`/`consensus`): correctly decode txs on `TxEnvelope`

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs

Closes #144. 
This ensures that, at the time of combining the signature with the tx, the correct format is applied for 2930/1559 txs, removing any eip-155 application.

fix(`consensus`): ensure into_signed forces correct format for eip1559/2930 txs

---

crates/network/src/transaction/signed.rs
crates/signer-aws/src/signer.rs
crates/signer-gcp/src/signer.rs
crates/signer-ledger/src/signer.rs
crates/signer/src/wallet/private_key.rs

closes #126.
Passes B256s by value, solving some compiler complaints,

chore(`signers`): fix errors from primitives upgrade, avoid passing `B256` by val

---

crates/rpc-types/src/eth/block.rs

chore: add missing helpers to BlockTransactions

---

crates/transport-ipc/src/lib.rs

The StreamSerializer returns an EOF error in some cases, I believe this happens if the last byte is a terminating byte " } ]
```
2024-01-29T13:20:01.196631Z ERROR alloy_transport_ipc: IPC response contained invalid JSON. Buffer contents will be logged at trace level e=EOF while parsing an object at line 1 column 674
2024-01-29T13:20:01.196647Z TRACE alloy_transport_ipc: IPC response contained invalid JSON. NOTE: Buffer contents do not include invalid utf8. buffer={"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x3a5f25f7fe9d8c21cc1a34e941623c73","result":{"hash":"0x8f02502ae22a869f00d8faaf1038bd12ff1d19864e788b4fde44879ff13ff044","parentHash":"0xa831d7ab24f5808a43ecfb2dc0106ae3f46f95cd7093c8facf1532f0c8723a9e","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b9 …
```

fix: skip ipc eof error on deserialize

---

.gitignore
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/legacy.rs
crates/network/src/transaction/mod.rs
crates/signer-ledger/Cargo.toml
crates/signer-ledger/src/signer.rs
crates/signer/src/lib.rs
crates/signer/src/signer.rs

Added tests for all tx types, discovered a few bugs. signing a legaxy tx still doesn't work for me:
```
failures:
signer::tests::test_sign_tx_legacy
test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 19.72s
```
Edit: it looks like it's that exact encoded call that fails, still not sure why.

fix: add encode_for_signing to Transaction, fix Ledger sign_transaction

---

crates/transport-ipc/src/lib.rs

This handles the case when the ipc socket is no longer readable and poll read returns Ready(0), in which case we can terminate the stream.
This happens when the node is terminated.

fix: handle IPC unreadable socket

---

crates/pubsub/src/frontend.rs
crates/transport/src/lib.rs

Remove unnecessary async in unsubscribe and box in send
Closes https://github.com/alloy-rs/alloy/issues/163

chore: simplify PubsubFrontend

---

crates/genesis/Cargo.toml
crates/genesis/src/lib.rs

missing pk support.
Adds missing private key support to alloy genesis, see https://github.com/foundry-rs/foundry/pull/6970#pullrequestreview-1856796777.

feat(`alloy-genesis`): pk support

---

crates/genesis/src/lib.rs

We were also lacking support for this, only for tests.
Add optional block number support

feat(`alloy-genesis`): support optional block number

---

crates/json-rpc/src/request.rs
crates/pubsub/Cargo.toml
crates/pubsub/src/frontend.rs
crates/pubsub/src/ix.rs
crates/pubsub/src/lib.rs
crates/pubsub/src/managers/active_sub.rs
crates/pubsub/src/managers/sub.rs
crates/pubsub/src/service.rs
crates/pubsub/src/sub.rs
crates/rpc-client/Cargo.toml
crates/rpc-client/src/client.rs

Adds the following types:
- `RawSubscription`
- `SubscriptionItem<T>`
- `Subscription<T>`
Lay groundwork for RAII subscriptions and subscription configuration.
Add `Subscription` type around the raw `tokio::broadcast::Receiver`

feat: subscription type

---

crates/providers/src/provider.rs

These provider methods were missing.
Add them.

feat(`alloy-providers`): additional missing methods

---

crates/rpc-types/src/eth/fee.rs

Related to reth task: https://github.com/paradigmxyz/reth/issues/6330
according to: https://github.com/ethereum/execution-apis/pull/486

feat: extend FeeHistory type with eip-4844 fields

---

crates/contract/src/call.rs
crates/providers/src/provider.rs
crates/rpc-trace-types/src/tracerequest.rs
crates/rpc-types/src/eth/call.rs
crates/rpc-types/src/eth/mod.rs
crates/rpc-types/src/eth/transaction/blob.rs
crates/rpc-types/src/eth/transaction/request.rs

`CallRequest` and `TransactionRequest` are basically the same type, with very few differences:
- `TransactionRequest` was missing an optional chain ID
- `TransactionRequest` was missing `max_fee_per_blob_gas`
- `CallRequest` and `TransactionRequest` had different blob fields
Since they also serve the same purpose, this PR dedupes them, to make sure there is only one tx request type, which is important for the network abstraction.
Dedupe them, porting over fields missing from either.
I removed the blob transaction sidecar, but only because I didn't really know if it is actually a part of the spec. As far as I could tell, only `blob_versioned_hashes` and the gas field is. I asked @mattsse for direction in case he knew, but ultimately we didn't land on anything.
This is a breaking change for …

refactor: dedupe `CallRequest`/`TransactionRequest`

---

crates/rpc-types/src/eth/transaction/request.rs

We were explicitly denying unknown fields on `TransactionRequest`.
Support them, as we already use `OtherFields`.

fix(`rpc-types`): do not deny additional fields

---

crates/rpc-types/src/eth/transaction/optimism.rs

Related to https://github.com/paradigmxyz/reth/issues/6547
In op-geth l1FeeScalar is represented as a float and is serialized to string
```go
FeeScalar  *big.Float `json:"l1FeeScalar,omitempty"` // always nil after Ecotone hardfork
```
```go
if receipt.FeeScalar != nil { // removed in Ecotone
fields["l1FeeScalar"] = receipt.FeeScalar.String()
}
```
This introduces a breaking change in reth and need to be synchronized with https://github.com/paradigmxyz/reth/pull/6575

fix: make l1_fee_scalar f64

---

crates/rpc-types/src/eth/block.rs

This was missing, and there were no tests for block id.
Adds a `FromStr` impl for `BlockId` and some tests.

chore(`rpc-types`): add FromStr impl for BlockId

---

crates/pubsub/src/connect.rs
crates/pubsub/src/frontend.rs
crates/pubsub/src/managers/in_flight.rs
crates/pubsub/src/service.rs
crates/rpc-client/src/batch.rs
crates/rpc-client/src/builder.rs
crates/rpc-client/src/client.rs
crates/transport-ipc/src/connect.rs
crates/transport-ws/src/native.rs
crates/transport-ws/src/wasm.rs
crates/transport/Cargo.toml
crates/transport/src/connect.rs
crates/transport/src/lib.rs

Closes https://github.com/alloy-rs/alloy/issues/200

chore: use `impl Future` in `PubSubConnect`

---

crates/transport-http/src/reqwest.rs

reqwest::Response::text decodes the body with the "utf-8" charset 
we can ignore this step and instead decode from the raw response directly.
this is also how `Response::json` is implemented

perf: use raw http response bytes

---

crates/json-rpc/src/error.rs
crates/transport-http/src/reqwest.rs

currently all deserde failures are returned as `deser_error`
this adds a check for error payload if deserialization failed

fix: map deserde error to ErrorResp if it is an error payload

---

crates/rpc-engine-types/src/optimism.rs

Towards https://github.com/paradigmxyz/reth/pull/6871
Adds specific type for `OptimismExecutionPayloadV3` to be used in `BuiltPayload`. Very similar to `ExecutionPayloadV3`, adds optimism-specific field `parent_beacon_block_root`

feat: add OptimismExecutionPayloadV3

---

crates/rpc-engine-types/src/optimism.rs

As suggested here https://github.com/alloy-rs/alloy/pull/242#discussion_r1509636060

chore: add missing doc link for parent_beacon_block_root

---

crates/transport-http/src/hyper.rs
crates/transport-http/src/reqwest.rs

Currently non-200 responses proceed to JSON deser. This causes them to be treated as `TransportError::custom` variants.
Closes #253 
Prevent server errors from being treated as JSON
Capture the errors

Convert non-200 http responses into errors

---

crates/transport-http/Cargo.toml

Reqwest has `default-tls` as a default feature (https://docs.rs/reqwest/latest/reqwest/#optional-features), however alloy crates import dependencies with `default-features = false`.
The `alloy` metadata crate has `default-tls` as its default feature, which in turn enables this feature in reqwest, so connections using tls via https work fine when using the `alloy` crate.
However, `alloy-providers`, `alloy-rpc-client`, and `alloy-transport-http` also depend on reqwest, but provide no option to enable `default-tls`. So if these crates are used directly (instead of eg `alloy::alloy_providers`) then it will panic when trying to connect to a https url.
The simplest fix was to add this to the reqwest feature (default) in the `alloy-transport-http` cargo toml.
Both `alloy-providers` and …

fix: enable reqwest default-tls feature in transport-http

---

crates/rpc-types/src/serde_helpers/storage.rs

Solves the serialization issue for the `JsonStorageKey` type which serializes the 0 key to `0x`. As per the hive tests, it should serialize to `0x0` (https://github.com/ethereum/execution-apis/blob/main/tests/eth_getProof/get-account-proof-with-storage.io).
Add an early return on the conversion of the storage key to a String, in order to manually return `0x0`. This is similar to the implementation found in `geth` (https://github.com/ethereum/go-ethereum/blob/b87b9b45331f87fb1da379c5f17a81ebc3738c6e/internal/ethapi/api.go#L727-L729).

fix: early return for `JsonStorageKey` to `String`

---

crates/providers/src/builder.rs
crates/providers/src/heart.rs
crates/providers/src/lib.rs
crates/providers/src/signer.rs

Enable the const fn lint
Add missing const fns

chore: const fns

---

crates/provider/src/new.rs

Closes https://github.com/alloy-rs/alloy/issues/225
Adds the methods
Unsure how to test this given this is unsupported by Anvil

feat: `trace_call` and `trace_callMany`

---

crates/network/src/ethereum/builder.rs
crates/network/src/transaction/builder.rs

Closes #268
We can't use `async fn` because we need the `Send` bound for `NetworkSigner`

refactor: remove `async_trait` in tx builder

---

crates/consensus/Cargo.toml
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/typed.rs

This is needed for some caches in Foundry
This was previously blocked by KZG types not being `Hash`

feat: derive `Hash` for `TypedTransaction`

---

crates/provider/src/chain.rs
crates/provider/src/provider.rs
crates/rpc-client/src/client.rs
crates/rpc-client/src/poller.rs
crates/rpc-client/tests/it/http.rs
crates/rpc-client/tests/it/ipc.rs
crates/rpc-client/tests/it/ws.rs

Closes https://github.com/alloy-rs/alloy/issues/270

chore: rename `RpcClient::prepare` to `request`

---

crates/provider/src/builder.rs
crates/provider/src/layers/nonce.rs
crates/provider/src/layers/signer.rs

Ref https://github.com/alloy-rs/alloy/issues/263

feat: default to Ethereum network in `ProviderBuilder`

---

CONTRIBUTING.md
crates/rpc-types/src/eth/filter.rs
crates/transport/src/error.rs

A common RPGF farming strategy is to open PRs to fix grammar/typos with a bot
Don't allow it

docs: do not accept grammar prs

---

crates/provider/src/provider.rs
crates/provider/src/utils.rs

Current estimator version is not flexible and will always return 3 gwei priority fee if base fee is less than 100 gwei which is not correct for L2s (and often pretty high even for Mainnet).
New impl was inspired by Metamask estimator and introduces following changes:
1. We no more use `EIP1559_FEE_ESTIMATION_THRESHOLD_MAX_CHANGE` because it could've resulted in overestimated gas prices. Let's consider `rewards` with following contents: `[100, 1, 1, 1, 1]`, in this case we'd filter out all 1's because of spike caused by a single 100 price, and the resulted priority fee estimate will be 100 gwei which is incorrect. Using median should be enough for a fair estimate filtering out potential anomalies.
2. We now simply multiply base fee by 2 to calculate max base fee instead of using …

feat: update priority fee estimator

---

crates/consensus/src/lib.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip4844/builder.rs
crates/consensus/src/transaction/eip4844/utils.rs
crates/consensus/src/transaction/mod.rs
crates/eips/src/eip4844.rs

There is currently no convenient way to construct valid sidecars from data
Add a sidecar builder that ingests arbitrary data, blobs it, and builds into a sidecar

Feat: 4844 SidecarBuilder

---

crates/json-rpc/README.md
crates/json-rpc/src/request.rs
crates/provider/src/provider.rs
crates/pubsub/src/managers/in_flight.rs
crates/rpc-client/src/batch.rs
crates/rpc-client/src/client.rs
crates/rpc-client/src/poller.rs

This allows dynamic method names in the type representation.

feat(json-rpc): use `Cow` instead of `&'static str` for method names

---

crates/rpc-types/src/eth/transaction/receipt.rs

closes #327
this simply returns 0x0 for legacy, see also geth:
https://github.com/ethereum/go-ethereum/blob/ba2dd9385c2a51134e520083dc732787a813b107/internal/ethapi/api.go#L1701-L1701
https://github.com/ethereum/go-ethereum/blob/ba2dd9385c2a51134e520083dc732787a813b107/core/types/tx_legacy.go#L95-L95

docs: update incorrect comment

---

crates/provider/src/provider.rs
crates/rpc-types/src/eth/block.rs

Some RPC Providers (Alchemy and Reth were tested) don't have the "uncles" field in their newHeads subscription, this breaks the subscribe_blocks() stream.
Providing the serde(default) flag on the uncles field allows graceful handling of both existing and missing uncle fields in the subscription response.

Fix subscribe blocks

---

crates/signer/src/signer.rs

Same as https://github.com/alloy-rs/alloy/pull/274#discussion_r1520531754:
> TIL this is necessary for `dyn Provider` to work, because otherwise `auto_impl` puts `U: Provider + Sized` bounds on the generic implementations if `Self: Sized` methods are not marked with `keep_default_for`. I added a test for this in this file

fix: Signer implementations for object-safe smart pointers

---

.github/workflows/ci.yml

Prevent future random CI breakage
Set clippy to stable in CI
there may be a better way to achieve this, but this way is straightforward

fix: force clippy to stable

---

crates/provider/src/layers/signer.rs
crates/provider/src/provider.rs
crates/rpc-types/src/eth/transaction/receipt.rs

Option initially came from Reth, but it should be mandatory
Ref https://github.com/ethereum/go-ethereum/blob/ba2dd9385c2a51134e520083dc732787a813b107/core/types/receipt.go#L62-L62

fix: make `TransactionReceipt::transaction_hash` field mandatory

---

crates/node-bindings/src/anvil.rs

Fixes: https://github.com/alloy-rs/alloy/issues/285
- add `block_time_f64` method for `Anvil`.
- change block_time to be f64.

add `block_time_f64` to `Anvil`

---

crates/contract/src/call.rs
crates/genesis/src/lib.rs
crates/network/src/ethereum/builder.rs
crates/network/src/transaction/builder.rs
crates/provider/src/layers/nonce.rs
crates/provider/src/layers/signer.rs
crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/request.rs

Closes #335 
Uses Serde's `with =` attribute and the existing `u64_hex` / `u64_hex_opt` to make sure RPC structs stay compliant.
~~Opening this PR as a draft first to get initial feedback.~~ ~~If implementation is correct I can add the other fields (`chain_id`, `transaction_type`, u128 native fields?)~~ (largely implemented in #338)

Fix: change nonce from `U64` to `u64` 

---

crates/rpc-types/src/eth/transaction/request.rs

Support HEX TransactionRequest.chain_id` as per Ethereum JSON-RPC specification. 
While switching between node clients (GETH and RETH) there was an inconsistency in the `TransactionRequest.chain_id` implementation. 
To support the behavior, specified in Ethereum JSON-RPC specification the `chain_id` serialization was extended to support
**hex** input. 
Specs: https://ethereum.github.io/execution-apis/api-documentation/
Reuse custom serializer, already implemented for `nonce` field to support **hex** input for `chain_id` field.

fix(transaction-request): Support HEX `TransactionRequest.chain_id`

---

crates/signer-trezor/src/lib.rs

Closes #292 + #332 
Updates the name and includes a deprecation notice

Fix: change `TrezorHDPath` to `HDPath` to mirror Ledger's `HDPath`

---

crates/provider/src/provider.rs
crates/provider/src/utils.rs

Closes #348 
Create a Struct housing `max_fee_per_gas` and `max_priority_fee_per_gas`, this is the type that is returned by `estimate_eip1559_fees` fn.

modification: Eip1559Estimation return type

---

crates/alloy/src/lib.rs

There's ProviderBuilder and other ways to instatiate providers rather than type aliases

chore: remove stale todos

---

crates/provider/src/heart.rs
crates/provider/src/provider.rs

Clarify naming on pending transaction and associated structs
rename `confirmations` to `reqd_confs`

refactor: rename to reqd_confs

---

crates/node-bindings/Cargo.toml
crates/node-bindings/src/anvil.rs
crates/node-bindings/src/geth.rs

The existing methods such as `endpoint()` and `ws_endpoint()` would return the URLs as a `String`. One would have to parse the String as a URL and then pass it to the provider. 
Adds two methods `endpoint_url()` and `ws_endpoint_url()`  which return the `HTTP` and `WS` urls respectively for both `anvil` and `geth` instances.

feat(node-bindings): add methods for returning instance urls

---

crates/provider/src/layers/fill_tx.rs
crates/provider/src/layers/gas.rs
crates/provider/src/layers/mod.rs

Ref: #323 
Implement a `layer` that populates the `gas_price`, `gas`, `max_fee_per_gas` and `max_priority_fee_per_gas`.

feat(layers): GasEstimationLayer

---

crates/rpc-engine-types/README.md

Realized the readme title did not actually refer to the same name as the crate
Changed the `alloy-rpc-engine-types` readme to refer to the crate name

fix(rpc-engine-types): use proper crate name in README.md

---

crates/consensus/src/transaction/eip4844.rs
crates/network/src/ethereum/builder.rs

Per https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md#blob-transaction:
> The field `to` deviates slightly from the semantics with the exception that it MUST NOT be `nil` and therefore must always represent a 20-byte address. This means that blob transactions cannot have the form of a create transaction.
Change `TxKind` to `Address`

fix: mandatory `to` on `TxEip4844`

---

crates/rpc-types/src/eth/transaction/mod.rs

WIthout `serde(default)` legacy transactions without chainId field can't be deserialized right now

fix: correctly process chainId field

---

crates/json-rpc/src/error.rs
crates/provider/src/heart.rs
crates/provider/src/layers/gas.rs
crates/provider/src/provider.rs
crates/provider/src/utils.rs
crates/transport/src/error.rs

TransportError should capture `Transport`-layer errors, not application or RPC semantics errors. RPC semantics errors should be captured by `RpcError` (note that `TransportErrorKind` instantiates an `RpcError<TransportError>`, not a `TransportError`). Application errors should be captured by either RpcError (e.g. when the application expects a non-null response) or by an ErrResp
- Remove usages of `TransportErrorKing::custom_str`
- Remove `MissingReceipt` variant from TransportError
- Add `NullResp` variant to `RpcError`

fix: remove app-layer usage of transport error

---

Cargo.toml
crates/signer-aws/Cargo.toml

~~@DaniPopes CI fails with this error: https://github.com/alloy-rs/alloy/actions/runs/8392690542/job/22985932109?pr=361~~
~~Looks like the cause is disabled `std` feature of `spki` in #367~~
enabled it for signer-aws, didn't know exact no_std subset

chore: bump core

---

Cargo.toml
crates/consensus/Cargo.toml
crates/rpc-client/Cargo.toml
crates/rpc-client/src/builder.rs
crates/transport-http/Cargo.toml
crates/transport-http/src/hyper.rs
crates/transport-http/src/lib.rs
crates/transport-http/src/reqwest.rs
crates/transport/src/boxed.rs

chore(deps): update to hyper 1.0

---

crates/consensus/Cargo.toml
crates/consensus/src/transaction/eip4844.rs

versioned hashes can be calculated without using c_kzg, just with sha2.
- Add methods for accessing versioned hashes to the BlobTransactionSidecar
- take feature cfg off kzg_to_versioned_hash, and make it operate on byte arrays

feat: versioned hashes without kzg

---

crates/consensus/Cargo.toml
crates/consensus/src/lib.rs
crates/consensus/src/transaction/eip4844/builder.rs

Quality of life improvement post #349 
- re-export `EnvKzgSettings` from alloy-consensus to allow easy use with `SidecarBuilder`
- refactor `SidecarBuilder::build` to use default settings
- add `SidecarBuilder::build_with_settings`

feat: re-export EnvKzgSettings

---

crates/rpc-types/src/eth/fee.rs

Adds helpers to get the base and blob base fee for `latestBlock + 1`

chore: add helpers for next block

---

Cargo.toml
crates/consensus/Cargo.toml
crates/consensus/src/transaction/eip4844.rs
crates/eips/Cargo.toml
crates/eips/src/eip4844/env_settings.rs
crates/eips/src/eip4844/trusted_setup_points.rs
crates/eips/src/lib.rs

The current implementation uses an Arc so it can never be no-std, and the `MAINNET` static is unnecessary as `EnvKzgSettings::Default.get` should be used instead.
cc @developeruche we should switch out `MAINNET` static usage in Reth to the enum

chore: clean up kzg and features

---

crates/provider/src/builder.rs
crates/provider/src/layers/gas.rs
crates/provider/src/layers/nonce.rs

feat: convenience functions for nonce and gas on `ProviderBuilder`

---

crates/provider/src/heart.rs

Current logic was not treating `confirmations` in the expected way (tx being included = 1 confirmation)
Also `split_off` splits off keys including the one at which split is being performed, thus we actually notified `TxWatcher` about txses one block later
Two open questions:
1. Currently if tx is sent, included into block and one more block is mined (basically tx included into block X and latest block is X+1), then call to `watch_pending_transaction` will indefinitely wait for a block with targeted tx. Is this expected? Feels like a footgun, especially considering that we don't have a default timeout
2. It feels like `watch_pending_transaction` users specifying `confirmations > 1` would also be interested in ensuring that no reorg has happened and that tx is actually on-chain, should we …

fix: correctly treat `confirmation` for `watch_pending_transaction`

---

Cargo.toml
crates/consensus/Cargo.toml
crates/consensus/src/signed.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/typed.rs
crates/eips/src/eip2930.rs
crates/serde/src/num.rs

Adds `Serialize` and `Deserialize` impls for `TypedTransaction`, `TxEnvelope`, etc.
Bumps core
I don't really like the way we manage `type` on tagged tx enums, current version is from ethers, perhaps there is a way we can do better here?

feat: serde for consensus tx types

---

crates/network/src/ethereum/builder.rs
crates/network/src/transaction/builder.rs

this makes it possible to configure an EIP-4844 transaction through the builder API
this also unlocks setting missing blobfee in the gasestimator layer, because we need to check if `get_blob_sidecar` exists to identify an 4844 tx

feat: extend TransactionBuilder with BlobTransactionSideCar setters

---

crates/rpc-types/src/eth/block.rs

adds helpers to create a `BlockId` more easily.

feat: add some BlockId helpers

---

crates/provider/src/layers/gas.rs
crates/rpc-types/src/eth/block.rs

~~blocked by https://github.com/alloy-rs/alloy/pull/411~~
ref #403
closes #377
This is not ideal but this at least sets a blob fee value for 4844 txs (txs with a sidecar)
This is not ideal for a few reasons:
* This does not estimate an appropriate blob fee and instead uses the value of the next block, if blob space is congested this will not result in timely inclusion (to do this we really need eth_feeHistory)
* Once all clients serve blob fee data in eth_feeHistory this can all be done with one eth_feeHistory request
I think we should consider customizing the gas layer so a custom estimator can be configured
cc @anna-carroll

feat: handle 4844 fee

---

crates/rpc-trace-types/src/lib.rs
crates/rpc-trace-types/src/otterscan.rs

Move Otterscan types to alloy
https://github.com/paradigmxyz/reth/issues/7372

Move Otterscan types to alloy

---

crates/rpc-trace-types/src/geth/mod.rs

rearrange field order to match geth's order, makes it easier to compare output
https://github.com/ethereum/go-ethereum/blob/767b00b0b514771a663f3362dd0310fc28d40c25/eth/tracers/logger/logger.go#L423-L437

chore: rearrange field order

---

crates/provider/src/provider.rs
crates/rpc-types/src/eth/fee.rs

the basefee of the "Latest" block is the second last entry in the vec, if the feeHistory response is correct then we don't need to fetch the block.
this keeps the block request as fallback but perhaps we should just error here?
see MM for ref:
https://github.com/MetaMask/core/blob/main/packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.ts#L62

perf: remove getBlock request in feeHistory

---

crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs
crates/consensus/src/transaction/envelope.rs
crates/contract/src/event.rs
crates/provider/src/layers/gas.rs
crates/rpc-types/Cargo.toml
crates/rpc-types/src/eth/log.rs
crates/rpc-types/src/eth/transaction/receipt.rs
crates/serde/src/bool.rs
crates/serde/src/lib.rs

Supersedes #395, closes #399
Prevent accidental divergence of consensus and rpc types by embedding the consensus type in the RPC type

feature: embed primitives Log in rpc Log and consensus Receipt in rpc Receipt

---

crates/consensus/src/transaction/envelope.rs
crates/eips/src/eip2718.rs

In `network_decode` the decoded bytes are not correctly consumed in the buffer which makes decoding break for anything that requires more decoding afterwards, and also makes it possible for the decoding to hang.

fix: infinite loop while decoding a list of transactions

---

crates/rpc-types/src/eth/log.rs

Fixes #422
Adds optional u64 `blockTimestamp` to `Log`.

feat(rpc): add `blockTimestamp` to Log

---

crates/alloy/Cargo.toml

Enables the `ws` and `ipc` flags on the `provider` crate through the `alloy` prelude to enable `on_ws` and `on_ipc` available on the `ProviderBuilder`.
This was missed in #391 as the examples did not use the methods.
The `ws` and `ipc` flag enable the `pubsub` flag internally, no change in behaviour is expected.

Fix: enable `ws` flag for `provider-ws` and `ipc` flag for `provider-ipc` in `alloy` prelude crate

---

crates/genesis/src/lib.rs
crates/rpc-types/src/eth/admin.rs
crates/serde/src/lib.rs
crates/serde/src/ttd.rs

JsonU256 was never valuable in alloy, it was just copy/pasted
remove it

chore: remove redundant JsonU256 from ethers

---

crates/rpc-types/src/eth/transaction/mod.rs

makes it possible to create a rpc receipt without importing additional crate

chore: reexport receipt types

---

crates/consensus/src/lib.rs
crates/consensus/src/receipt/any.rs
crates/consensus/src/receipt/mod.rs
crates/serde/src/num.rs

adds `AnyReceiptEnvelope` type that is the `ReceiptEnvelope` but with a type field.

feat: add AnyReceiptEnvelope

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs
crates/contract/src/call.rs
crates/network/src/any/builder.rs
crates/network/src/ethereum/builder.rs
crates/network/src/transaction/builder.rs
crates/provider/src/layers/gas.rs
crates/provider/src/layers/nonce.rs
crates/provider/src/layers/signer.rs
crates/provider/src/provider.rs
crates/provider/src/utils.rs
crates/rpc-types/src/eth/fee.rs
crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/receipt.rs
crates/rpc-types/src/eth/transaction/request.rs
crates/rpc-types/src/eth/transaction/tx_type.rs
crates/serde/src/num.rs
crates/signer-trezor/src/signer.rs

Ref #433
* `gas_limit` -> `u128`
* `gas` -> `u128`
* `gas_price` -> `u128`
* `max_fee_per_blob_gas` -> `u128`
* `transaction_type` -> `u8`
* `max_fee_per_gas` -> `u128`
* `max_priority_fee_per_gas` -> `u128`
* Consequently, changed fn args and return values accordingly.
* Satisfies clippy, tests will fail.

Numeric type audit: network, consensus, provider, rpc-types

---

crates/transport-http/src/lib.rs
crates/transport-http/src/reqwest.rs

close https://github.com/alloy-rs/alloy/issues/387

feat: add Http::new for reqwest::Client

---

crates/network/Cargo.toml
crates/network/src/lib.rs
crates/rpc-types/src/eth/block.rs

Ref #440 and #441
Removed `TransactionList` from alloy_network

dedup: TransactionList and BlockResponse

---

crates/consensus/src/receipt/envelope.rs
crates/consensus/src/transaction/envelope.rs
crates/rpc-types/src/eth/transaction/receipt.rs

consensus: mark envelopes non-exhaustive

---

crates/rpc-types/src/eth/block.rs

This pull request adds a default implementation for the rpc `Block` struct.

Derive default implementation for rpc `Block`

---

crates/serde/src/num.rs

Implement `is_zero` method for `U64HexOrNumber`.

Implement `is_zero` method for `U64HexOrNumber`

---

crates/signer-wallet/README.md

The name of the crate is [alloy-signer-wallet](https://github.com/alloy-rs/alloy/blob/89f14f9db5afb98d13d9d760b0615f4b10c5b6c4/crates/signer-wallet/Cargo.toml#L2) but it was named here as "alloy-signer-wallets"
Changed the name so that when users import it to their projects they directly have the right name.
Not breaking changes

Update typo in README

---

crates/consensus/src/signed.rs
crates/consensus/src/transaction/typed.rs
crates/network/src/lib.rs
crates/rpc-types/Cargo.toml
crates/rpc-types/src/eth/transaction/request.rs
crates/rpc-types/src/with_other.rs

Ref #438 
Add `From` bounds to `UnsignedTx` and `TransactionRequest` types in `Network`.
Satisfy bounds by implementing the following:
- `From<TypedTransaction> for TransactionRequest`
- `From<TxEnvelope> for TransactionRequest`
- `From<TypedTransaction> for WithOtherFields<TransactionRequest>`
- `From<TxEnvelope> for WithOtherFields<TransactionRequest>`
To accomplish the above, implemented
- `From<TxLegacy> for TransactionRequest`
- `From<TxEip2930> for TransactionRequest`
- `From<TxEip1559> for TransactionRequest`
- `From<TxEip4844Variant> for TransactionRequest`

TypeTransaction conversion trait impls

---

crates/network/src/ethereum/builder.rs

`to` is required to be Some only for EIP-4844 txses

fix: allow empty `to` field in `can_build`

---

crates/rpc-types/src/with_other.rs

Ref https://github.com/serde-rs/serde/issues/1909
ref #493
Currently deserializing `WithOtherFields<T>` where `T` is a struct with multiple levels of fields with `serde(flatten)`, the resulted object would have fields of the `inner` struct duplicated in `other`. Example of this behavior is a deserialization of `AnyTransactionReceipt`:
<details>
<summary>resulted receipt</summary>
```rust
WithOtherFields {
inner: TransactionReceipt {
inner: AnyReceiptEnvelope {
inner: ReceiptWithBloom {
receipt: Receipt {
status: true,
cumulative_gas_used: 1586930,
logs: [
Log {
inner: Log {
address: 0x13b82c379e4209acc43005f0b2b661945557f56e,
data: LogData {
topics: [
0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0,
0x00000000000000000000000045fa3ec833b6a0bf1ab27c8dd33ae03baacc3aa4, …
```

fix: workaround for `WithOtherFields`

---

crates/json-rpc/Cargo.toml
crates/json-rpc/src/lib.rs
crates/json-rpc/src/result.rs
crates/rpc-client/src/call.rs

There is currently no way of knowing what raw data we are sending and receiving.
Add `trace!` calls around the `RpcClient` future for this, as well as a simpler `debug!` for just the method and ID, as the raw data could be very verbose.
Running `test_send_tx` with `alloy=debug`, I think this verbosity is fair for debug:

feat(rpc): trace requests and responses

---

crates/eips/src/eip4895.rs

Add arbitrary derive for Withdrawal, so we can do proptest in codec implementation.

Add arbitrary derive for Withdrawal

---

crates/provider/src/utils.rs

ref https://github.com/foundry-rs/foundry/issues/7620
currently we are not accounting for an edge case when estimated priority fee is higher than base fee. baseFee*2 is usually enough, but in the mentioned PR anvil was started with 0 baseFee, thus baseFee was always estimated as zero

fix: eip1559 estimator

---

crates/provider/src/builder.rs

Reverts alloy-rs/alloy#510
License is not outdated, it applies to code in the file which was copy-pasted from the tower project and reproducing the license text is necessary to comply with the license terms

Revert "chore: remove outdated license"

---

crates/eips/src/eip2930.rs

prep for https://github.com/paradigmxyz/reth/pull/7554
adds a few helpers, could use a closer API review, perhaps some aren't even useful.

feat: port helpers for accesslist

---

crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/receipt.rs
crates/rpc-types/src/eth/txpool.rs

these can be null, or missing entirely
https://github.com/ethereum/go-ethereum/blob/767b00b0b514771a663f3362dd0310fc28d40c25/core/types/receipt.go#L69-L73

fix: tx receipt inclusion context

---

crates/rpc-client/src/builtin.rs

IPC sockets return `false` for all `is_*` metadata queries.

fix: correctly parse IPC sockets in builtin connections

---

Cargo.toml
crates/rpc-types-anvil/Cargo.toml
crates/rpc-types-anvil/README.md
crates/rpc-types-anvil/src/lib.rs

adds a crate for rpc types used by anvil
there are only a handful types, it's easier to maintain these in this workspace, and we could also an anvil provider trait for specific dev functions,
and this would also make it possible to define server API traits:
https://github.com/paradigmxyz/reth/pull/7495

feat: add rpc-types-anvil

---

crates/rpc-client/src/builtin.rs

silences warning if ipc feature not enabled

chore: rm PathBuf import

---

crates/provider/src/heart.rs

closes https://github.com/foundry-rs/foundry/issues/7652
SelectNextSome over `Fuse` will panic
Fuse will return 
```rust
if *this.done {
return Poll::Ready(None);
}
```
but selectsome will panic if the underlying stream already returned None once
```rust
if let Some(item) = ready!(self.stream.poll_next_unpin(cx)) {
Poll::Ready(item)
} else {
debug_assert!(self.stream.is_terminated());
cx.waker().wake_by_ref();
Poll::Pending
}
```

fix: dont use fuse::select_next_some

---

README.md

Currently, the README uses relative paths rather than absolute paths. This leads to 404s in two places:
On https://alloy-rs.github.io/alloy/, where a link to e.g. alloy goes to https://alloy-rs.github.io/alloy/alloy/crates/alloy instead of https://github.com/alloy-rs/alloy/tree/main/crates/alloy
On the Alloy crate at https://github.com/alloy-rs/alloy/tree/main/crates/alloy, where a link to e.g. alloy-signer goes to https://github.com/alloy-rs/alloy/blob/main/crates/alloy/crates/signer instead of https://github.com/alloy-rs/alloy/tree/main/crates/signer
This commit fixes both of these 404s by switching from relative paths to absolute paths. It also follows the same usage of absolute paths as [lib.rs](https://github.com/alloy-rs/alloy/blob/037dd4b20ec8533d6b6d5cf5e9489bbb182c18c6/crates/allo …

docs: fix 404s on docs site via absolute paths

---

crates/rpc-types/src/eth/transaction/error.rs

The `ConversionError` enum was incomplete until now, not allowing to handle all errors that could arise from converting Block and Header rpc to Block and Header primitives respectively.
Indeed, other errors can arise and are added here as conversion impossibilities or missing fields.

Add new variants to `ConversionError`

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/legacy.rs

Exports a few of the `Tx*` types' inner encoding & decoding functions for use in the `op-alloy-consensus` wrapper. Doing so allows us to re-use all of these types in the expanded transaction envelope enum.

feat: Export inner encoding / decoding functions from `Tx*` types

---

crates/contract/src/call.rs
crates/provider/src/fillers/gas.rs
crates/provider/src/fillers/nonce.rs
crates/provider/src/provider.rs

This issue #514 
Make the `BlockId` optional and use the default value if it's `None`.

refactor: make optional BlockId params required in provider functions

---

crates/rpc-types/src/eth/transaction/request.rs

The `to` builder method for `TransactionRequest` takes `Option<Address>` as arg. This is inconsistent with other builder methods. 
Use `Address` type for arg and wrap it in `Some` inside the method

fix(rpc-types): accept `Address` in `to` builder method for TxReq

---

crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/typed.rs
crates/network/src/any/builder.rs
crates/network/src/any/mod.rs
crates/network/src/ethereum/builder.rs
crates/network/src/ethereum/mod.rs
crates/network/src/lib.rs
crates/network/src/transaction/builder.rs
crates/network/src/transaction/mod.rs
crates/network/src/transaction/signer.rs
crates/provider/src/provider.rs
crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/request.rs

feat: refactor request builder workflow

---

crates/transport/src/trait.rs

Transport is implemented generically on any T that is a service with the required packets, the sealed trait does nothing here

chore: remove Sealed in Transport definition

---

crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/request.rs

this is part of the spec and should remain, was removed in https://github.com/alloy-rs/alloy/pull/431
https://ethereum.github.io/execution-apis/api-documentation/
this could also be used to determine the preferred txtype but would like to fix that separately

fix: add back transaction type

---

crates/provider/src/heart.rs

As discussed, try to fetch receipt before passing transaction to heartbeat

fix: tmp fix for `PendingTransactionBuilder::get_receipt`

---

crates/eips/src/eip6110.rs
crates/eips/src/lib.rs
crates/rpc-types-engine/Cargo.toml
crates/rpc-types-engine/src/exit.rs
crates/rpc-types-engine/src/lib.rs
crates/rpc-types-engine/src/payload.rs

adds payload v4 type for https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#depositreceiptv1
also adds https://eips.ethereum.org/EIPS/eip-6110 Deposit type
This does not yet enable V4 as supported variant to the payload enum, this will follow once reth is ready for this
ref https://github.com/paradigmxyz/reth/issues/7363

feat: add prague engine types

---

crates/consensus/src/receipt/any.rs
crates/consensus/src/receipt/receipts.rs
crates/rpc-types/src/eth/log.rs

Closed #538 
Add generics to more impl blocks for `AnyReceiptEnvelope` and `ReceiptWithBloom`
Followup work to review receipt trait and maybe make a `Log` trait or similar 🤔

fix: add more generics to any and receipt with bloom

---

crates/network/src/ethereum/builder.rs
crates/network/src/transaction/builder.rs

Followup to #552 
We don't want to rely on users to set the correct tx type pre-submission. We assume that other tx characteristics are more important than tx type, and essentially treat the tx type as a computed property
Modify `prep_for_submission` to override user-specified `tx_type`

fix: override txtype during submission prep

---

crates/contract/src/call.rs

Added a clarifying comment in regards to how state overrides are applied in `call` and `call_raw`.
Closes #517 as it is not necessary to implement a new method.

chore: document how state overrides work in `call` and `call_raw`

---

crates/network/src/ethereum/signer.rs
crates/network/src/transaction/signer.rs
crates/provider/src/fillers/join_fill.rs
crates/provider/src/fillers/mod.rs
crates/provider/src/fillers/signer.rs
crates/provider/src/lib.rs
crates/provider/src/wallet.rs

Adds a trait that allows users to access the `NetworkSigner` in a signing fill + provider stack.
Allow users to view keys and add signing credentials after building the provider stack. 
Add a trait that exposes the underlying signer via borrows and mut borrows, and includes convenience functions for the useful `NetworkSigner` functions
Note: 
This trait is implemented only when both of the following are true:
- the signer is the `R` filler on the joinfill, 
- the fillprovider is the outermost layer
These conditions are true for all stacks constructed by the builder. This is a bit non-intuitive, but is necessary to avoid conflicting impls when both L and R are signer provider and when multiple signers are present in a stack. While neither of those cases are expected ever, the type system …

feature: WalletProvider

---

crates/provider/src/debug.rs

`debug_trace_call` was taking the `GethDebugTracingOptions` as `trace_options` whereas it should be `GethDebugTracingCallOptions`
closes https://github.com/alloy-rs/alloy/issues/579
Replace with `GethDebugTracingCallOptions`

fix(provider/debug): arg type in debug_trace_call

---

crates/provider/src/provider.rs

`get_uncle` and `get_uncle_count` failed when `BlockId::Hash` was passed as the tag as the `RpcBlockHash` was being passed to the params directly instead of only the actual `block_hash`.
Pass actual `block_hash` and not the type.
Also, changed `idx: U64` -> `u64`.

fix(provider): uncle methods for block hash

---

crates/provider/src/provider.rs

Passing the primitive type for the `idx` leads to the following error:
```bash
server returned an error response: error code -32602: invalid argument 1: json: cannot unmarshal non-string into Go value of type hexutil.Uint
```
in the anvil integration test: https://github.com/yash-atreya/foundry/blob/cfeffd5f5cd7c4225ddd3f35ab1c2618648200db/crates/anvil/tests/it/fork.rs#L852
Temp fix is to rollback to non-primitive type `U64`.

Temp get_uncle fix

---

crates/provider/src/fillers/mod.rs

This PR follows a discussion in the tg channel about the need to apply all fillers to a transaction request without sending it, for instance to be able to build a Flashbot bundle.
Adds a fill() method on `FillProvider` that just call inner filler prepare_and_fill().

feat: allow to only fill a transaction request

---

crates/consensus/src/transaction/envelope.rs

TxEnvelope does not expose many passthrough methods, when it really should
Add a couple more useful methods

feature: passthrough methods on txenvelope

---

crates/contract/src/event.rs

Fix for #595 
changed:
```rust
#[doc(hidden)]
impl<'a, T: Transport + Clone, P: Provider<T, N>, E: SolEvent, N: Network> Event<T, &'a P, E, N> {
// `sol!` macro constructor, see `#[sol(rpc)]`. Not public API.
// NOTE: please avoid changing this function due to its use in the `sol!` macro.
pub fn new_sol(provider: &'a P, address: &Address) -> Self {
Self::new(provider, Filter::new().address(*address))
}
}
```
to:
```rust
#[doc(hidden)]
impl<'a, T: Transport + Clone, P: Provider<T, N>, E: SolEvent, N: Network> Event<T, &'a P, E, N> {
// `sol!` macro constructor, see `#[sol(rpc)]`. Not public API.
// NOTE: please avoid changing this function due to its use in the `sol!` macro.
pub fn new_sol(provider: &'a P, address: &Address) -> Self {
// keccak256 hash of the event signature needed for the …
```

fix: sol macro generated event filters were not filtering

---

Cargo.toml
crates/transport-ipc/Cargo.toml
crates/transport-ipc/src/lib.rs

the json stream deserializer has issues with partial objects.
this continues the stream on data errors as long as the internal buffer does not exceed the configured capacity

fix: continue reading ipc on data error

---

crates/pubsub/src/frontend.rs
crates/rpc-client/src/client.rs

The `channel_size` for the pubsub frontend defaulted to `16` with no way to set from the `RpcClient` level. 
Change `channel_size: usize` to `channel_size: AtomicUsize` in `Pubsub<Frontend>` and add setter method in `RpcClientInner<PubsubFrontend>`

feat(pubsub): set channel size

---

crates/rpc-types/src/eth/filter.rs

This pull request adds implementations for the `From` trait for the `FilterChanges` enum, allowing conversion from various types to each variant of the enum.

Improve `FilterChanges` implementation

---

crates/rpc-types-engine/Cargo.toml
crates/rpc-types-engine/src/jwt.rs
crates/rpc-types-engine/src/lib.rs

Closes #599 
Implements JSON Web Token utilities in the `rpc-types-engine` crate. Only focuses on JWT token generation and validation, not the auth layer as the generated token is used as a string in bearer auth.
Largely uses the JWT secret implementation by Reth with some enhancements to documentation and using built-in `get_current_timestamp`. Notably does not implement loading from file, reading from file or writing to file as that is out of scope for Alloy I feel. 
Regarding the defined limitations on the algorithm and length, I've kept that 1:1 with the Reth implementation to make sure it can be used in that context and the limitations seem reasonable enough for a more general case.
See for reference: https://github.com/paradigmxyz/reth/blob/79452eadaf4963f1e8d78a18b1f490d7c560aa54/cr …

feat(engine): Add JSON Web Token (JWT) token generation and validation support

---

.github/scripts/install_test_binaries.sh
crates/rpc-types/src/eth/admin.rs

Fixes https://github.com/alloy-rs/alloy/issues/619
See https://github.com/ethereum/go-ethereum/pull/26804

fix: admin_peerInfo, bump geth

---

crates/provider/src/heart.rs

we still encounter issues with low block times (arbitrum) resulting in hanging requests.
this provides a slightly better mitigation that keeps polling for the receipt based on an interval while also awaiting the pending res from the heartbeat
https://github.com/foundry-rs/foundry/issues/7642

fix: better tx receipt mitigation

---

crates/provider/src/builder.rs
crates/provider/src/fillers/gas.rs
crates/provider/src/fillers/nonce.rs
crates/provider/src/fillers/signer.rs
crates/provider/src/layers/anvil.rs
crates/provider/src/layers/mod.rs
crates/provider/src/lib.rs
crates/provider/src/wallet.rs

Closes #578 
Make an anvil layer that configures and spawns a shared anvil instance
Refactor existing `on_anvil` code to use new provider

feature: AnvilProvider

---

.github/scripts/install_test_binaries.sh
crates/node-bindings/src/geth.rs

Clique support was removed, see https://github.com/ethereum/go-ethereum/releases/tag/v1.14.0

chore: update to geth 1.14

---

CONTRIBUTING.md

I was unable to run the tests for alloy (Cf #626) it was due to missing the `geth` and `Anvil` software.
I have added the requirements in the `Contributing.md` file so that other developers can directly see that they are needed.
I specified `geth v1.13.x` because testsuite doesn't work for now on latest geth version: `geth v1.14.0`
But the testsuite may work in future geth release, I am not sure that fixing the version to `1.13.x` is a good idea because we will have to change it manually every time we upgrade. And anyways, when we run `cargo test` with `geth v1.14.0` it tells us to use `geth v1.13.x
Only Text modification no code change

docs: add required softwares to run tests in Contributing.md

---

crates/genesis/Cargo.toml
crates/genesis/src/lib.rs
crates/serde/src/lib.rs

Towards https://github.com/paradigmxyz/reth/issues/7702
Currently fields specific to chains different from mainnet Ethereum (like those related to OP forks) are not being deserialized into ChainConfig. 
Adds an `extra_fields` field to ChainConfig to gather the additional chain-specific information without polluting the top-level object.

feat: add extra_fields to ChainConfig

---

crates/network/src/transaction/builder.rs
crates/provider/src/fillers/mod.rs
crates/provider/src/fillers/nonce.rs
crates/provider/src/fillers/signer.rs

Followup to #431 
Signer now uses the tx builder to give lists of missing keys

fix: signer filler now propagates missing keys from builder

---

crates/eips/Cargo.toml
crates/eips/src/eip1898.rs
crates/eips/src/lib.rs
crates/rpc-types/src/eth/block.rs

Closes #633.
* removed `thiserror::Error` derive for `ParseBlockHashOrNumberError` since other errors in `alloy-eips` doesn't rely on `thiserror` it at all.

Move block hash types to alloy-eips

---

crates/network/src/ethereum/builder.rs
crates/rpc-types/src/eth/transaction/request.rs

Fixes the bug documented in: https://github.com/alloy-rs/alloy/issues/634
Added EIP1559 gas checks on the EIP2930 check.

fix: checking if the eip1559 gas fields are not set on eip2930 check

---

crates/rpc-types-engine/src/payload.rs

There is currently no way to access the inner `B64` of the `PayloadId` type.
This means you cannot reuse the computation that derives the payload bytes.
My use case is a custom payload builder on top of `reth` that attaches additional payload builder attributes beyond what the Engine API provides: https://github.com/ralexstokes/mev-rs/blob/main/mev-build-rs/src/payload/builder_attributes.rs#L71-L77
I would like to use the same `PayloadId` that `reth` natively provides and simply mix in new data into the payload id by mixing in new data, e.g. https://github.com/ralexstokes/mev-rs/blob/0d283373445c36a6287f1c51599ddd662fbe7c2a/mev-build-rs/src/payload/builder_attributes.rs#L47
Without this, I have to locally vendor the same computation as `reth` and also pass around the bytes along with the …

`alloy_rpc_types_engine`: expose inner `B64` from `PayloadId`

---

crates/network/src/ethereum/builder.rs

wrong order
first set sidecar, then populate hashes

fix: populate hashes after setting sidecar

---

crates/provider/src/provider/trait.rs
crates/rpc-types/src/eth/block.rs

Closes #665, lays groundwork for re-use of `BlockTransactions` by other networks
Propagate generic over T wherever possible, add fallible casting convenience methods
includes a drive-by doctest fix

fix: more abstraction for block transactions

---

crates/rpc-types-engine/src/payload.rs

Towards https://github.com/paradigmxyz/reth/pull/7993
During the checks for well-formed payload the existence of hardfork-specific fields is missing.
Adds `PayloaError` variants to allow signaling failed checks for the existence of hardfork-specific fields.

feat: add PayloadError variants

---

crates/consensus/Cargo.toml
crates/consensus/src/transaction/eip4844.rs
crates/eips/src/eip4844/mod.rs
crates/eips/src/eip4844/sidecar.rs

closes #675
this makes it easier to reuse blob validation, for example in reth.
the `MissingSidecar` error variant no longer fits, but it's also not worth rolling an additional error type for this case imo

chore: move blob validation to sidecar

---

crates/consensus/src/header.rs
crates/rpc-types/src/eth/block.rs

Adds EIP-7685 header fields to both the consensus and RPC `Header` types.

feat: add eip-7685 requests root to header

---

crates/transport-http/Cargo.toml
crates/transport-http/src/hyper.rs
crates/transport-http/src/reqwest.rs

debugging zenith builder errors, encountered some missing tracing surface area
- remove several differences in hyper and reqwest handling
- add debug and trace level logging of request dispatch and response characteristics

feat: tracing for http transports

---

crates/consensus/src/transaction/eip4844/builder.rs

Resolves #682
Since even things like [Paradigm's ExEx Rollup](https://github.com/paradigmxyz/reth/blob/main/examples/exex/rollup/src/main.rs) rely on `SimpleCoder` in `examples`, it makes sense to add extra checks against potential attackers who might allocate too much memory.

fix: add check before allocation in `SimpleCoder::decode_one()`

---

crates/rpc-types-engine/src/cancun.rs

Towards https://github.com/paradigmxyz/reth/pull/7993
When using `MaybeCancunPayloadFields` to check the existence of cancun fields, calling `inner` consumes self and forces to clone the container under some circumstances.
Add an `as_ref` that doesn't consume self and returns a reference to the inner fields.

feat: add MaybeCancunPayloadFields::as_ref

---

crates/provider/src/provider/trait.rs

closes https://github.com/foundry-rs/foundry/issues/7867
should be hex according to spec

fix: use U64 for feeHistory blocknumber

---

crates/eips/src/eip6110.rs
crates/rpc-types-engine/src/lib.rs
crates/rpc-types-engine/src/payload.rs

Similar to #672, EIP-6110 has been changed to work with EIP-7685, which also included changes to the engine API spec, renaming deposit receipts to deposit requests.
- Rename `DepositReceipt` to `DepositRequest`
- Re-export `DepositRequest` as `DepositRequestV1` in line with the engine API spec

chore: rename `DepositReceipt` to `DepositRequest`

---

crates/rpc-types-engine/src/payload.rs

We want to transform `ExecutionPayloadV4` into `ExecutionPayload`
Impl `From` like we did the other payload versions

feat: impl `From` for exec payload v4

---

crates/eips/src/eip4844/sidecar.rs

should prevent stackoverflows on sidecar deserde, ref https://github.com/foundry-rs/foundry/actions/runs/8968170602/job/24627087079?pr=7868
I assume this could be improved further by implementing a custom visitor, but will followup separately

feat: manual blob deserialize

---

README.md

When I stumbled upon this repository after seeing that ethers-rs was being deprecated I struggled for a couple of hours trying to understand why my installation was failing when doing `cargo install`. Had it been clear in the repo documentation that the crates are not available on the Rust package repository I would have saved myself some time. 
In the telegram chat I also received a pastebin link for all the different features that are available in the crate. Personally, I think that sharing pastebin links is not a good practice given that they can be used by malicious actors to spread malware etc. Therefore it is better to clearly state this in the main repo for clarity purposes.
I added a section explaining that the repo is currently not available on crates.io and how a developer can …

Clarify installation instructions for alloy

---

crates/alloy/Cargo.toml

This fixes the compilation of the following code:
```rust
let my_event_filter = contract.MyEvent_filter().subscribe().await?;
```
```toml
alloy = { git = "https://github.com/alloy-rs/alloy", branch = "main", features = ["contract", "pubsub"] }
```

fix: include `alloy-contract?/pubsub` in `pubsub` feature

---

crates/consensus/src/header.rs

I forgot to add `requests_root` to `Header::size`

fix: account for requests root in header mem size

---

crates/eips/src/eip7685.rs
crates/eips/src/lib.rs

[EIP-7685](https://eips.ethereum.org/EIPS/eip-7685) adds an EL → CL request list. The list items are requests, which are encoded as `type ++ request_data`, where `request_data` is an opaque byte buffer. The meaning of the bytes is up to each request, which are defined in separate EIPs.
Add traits for encoding and decoding requests. This follows the same overall design as our traits for EIP-2718, with the difference being that EIP-2718 also has special handling for legacy transactions.
The expected usage is to define something a la `TxEnvelope`, e.g. `RequestsEnvelope`, which is an enum that internally holds each legal request type. The requests themselves are decoded and encoded according to their own EIPs, e.g. with RLP.

feat: add eip-7685 enc/decode traits

---

crates/consensus/src/lib.rs
crates/consensus/src/request.rs
crates/eips/src/eip6110.rs
crates/eips/src/eip7002.rs

Adds a 7685 envelope for mainnet EL request types. The current ones for Prague are EIP-6110 deposits and EIP-7002 withdrawals.
Depends on #704 and #705

feat: add eth mainnet EL requests envelope

---

crates/transport-http/src/hyper_transport.rs
crates/transport-http/src/lib.rs
crates/transport-http/src/reqwest_transport.rs

Supersedes #715 
Re-export reqwest and hyper for downstream user convenience. Add type aliases for

feat: re-export and more http aliases

---

crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/receipt.rs
crates/rpc-types/src/eth/txpool.rs

this reverts incorrect changes introduced in https://github.com/alloy-rs/alloy/pull/523
in transaction info (for example `eth_getTransactionByHash`), these fields [are required](https://github.com/ethereum/execution-apis/blob/c4e7da7e486f6cb6ff6281c3ff28bb37445d5415/src/schemas/transaction.yaml#L334-L339)
```yaml
required:
- blockHash
- blockNumber
- from
- hash
- transactionIndex
```
in transaction receipts, there fields [are required](https://github.com/ethereum/execution-apis/blob/c4e7da7e486f6cb6ff6281c3ff28bb37445d5415/src/schemas/receipt.yaml#L40-L50).
```yaml
required:
- blockHash
- blockNumber
- from
- cumulativeGasUsed
- gasUsed
- logs
- logsBloom
- transactionHash
- transactionIndex
- effectiveGasPrice
```
moreover, the original justification is also incorrect, as the author has …

fix: required fields for transactions and receipts

---

crates/rpc-types-beacon/src/sidecar.rs

Iterator for new beacon EIP4844 type
Motivation
This will alllow us to grab n blobs for a given tx from the CL
it will also unblock https://github.com/paradigmxyz/reth/pull/7443

feature: beacon sidecar iterator

---

crates/rpc-types/src/eth/transaction/common.rs

For situation where `TransactionInfo` is built from `Transaction`, `base_fee` field is set to `None`. As a result, it is interesting to have a `with_base_fee` method implemented in order to consume the created `TransactionInfo` instance and populate its `base_fee` field.

add `with_base_fee` for `TransactionInfo`

---

crates/rpc-types/src/eth/fee.rs

We are not using correct serde impl for `base_fee_per_blob_gas`, thus any `FeeHistory` requests to client impls which have this field in response are failing to get deserialized

fix: `FeeHistory` deserialization

---

crates/consensus/src/constants.rs
crates/eips/src/eip4788.rs
crates/eips/src/eip7002.rs

[EIP-7002](https://eips.ethereum.org/EIPS/eip-7002) system contract
This PR adds the address of the [EIP-7002](https://eips.ethereum.org/EIPS/eip-7002) system contract, its code and an [EIP-7685](https://eips.ethereum.org/EIPS/eip-7685) withdrawal request type, as well as moves around the [EIP-7488](https://eips.ethereum.org/EIPS/eip-4788) constants.

feat(consensus, eips): EIP-7002 system contract

---

crates/contract/src/call.rs

Missing important setters on CallBuilder: https://github.com/alloy-rs/alloy/issues/534
> According to [this post](https://ethereum.stackexchange.com/questions/94412/valueerror-code-32000-message-only-replay-protected-eip-155-transac) we need to specify the chain-id field, but I can't specify the chain-id in the [CallBuilder](https://github.com/alloy-rs/alloy/blob/8cb0307b9bdb6cef9058d2d1a2219c8d212a7421/crates/contract/src/call.rs#L191)
_Originally posted by @mattsse in https://github.com/alloy-rs/alloy/issues/527#issuecomment-2054062261_
Add important setters functions of `TransactionBuilder` in `CallBuilder`

feat: add important setters functions of `TransactionBuilder` in `CallBuilder`

---

crates/consensus/src/transaction/eip4844.rs

**Pull Request Description:**
This pull request updates the method name `into_tx` to simply `into` for the `TxEip4844WithSidecar` struct. This change aligns the naming convention with Rust idiomatic usage and enhances code readability.
**Changes Made:**
- Renamed the method `into_tx` to `into` in the `TxEip4844WithSidecar` implementation.

replace `into_tx` by `into`

---

crates/consensus/src/receipt/receipts.rs

This pull request replaces the method `into_receipt` with the more idiomatic and concise `into` in the `ReceiptWithBloom<T>` struct.
- Replaced the method `into_receipt` with `into` in the `ReceiptWithBloom<T>` struct.
The method `into` is a common convention in Rust for consuming a value and converting it into another type. By using `into`, the code becomes more idiomatic and aligns with Rust's conventions. This change also improves readability and reduces verbosity.

replace `into_receipt` by `into`

---

crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/envelope.rs
crates/rpc-types/src/eth/transaction/mod.rs

Summary of the refactors made:
- Use `Self` instead of `TxEip4844Variant` where possible
- Use `From` implementation where possible

refactor around `TxEip4844Variant`

---

crates/rpc-types-engine/src/optimism.rs

there's no OP spec for this yet, but this does follows the same pattern as for v3

feat: add op payload type

---

crates/eips/src/eip2935.rs
crates/eips/src/lib.rs

[EIP-2935](https://eips.ethereum.org/EIPS/eip-2935)
Add history storage contract address and bytecode.

feat(eips): EIP-2935 history storage contract

---

crates/genesis/src/lib.rs

Parse deposit contract address in the chain config instead of the Genesis struct, since this is the devnet-0 format

fix: parse deposit contract in chain config

---

crates/consensus/src/request.rs

the EIP was a bit ambigious here, apparently we are not supposed to also RLP encode the result of the
EIP-7685 encoding. instead, to compute the request root, we should just stuff the EIP-7685 encoded request
into a list and RLP encode that list
this simply removes the unneeded RLP encoding. we could also have kept it around and simply do a `self.encode_7685(buf)`, but I think that would break expectations around how RLP works (geth does this)

chore: remove rlp encoding for `Request`

---

crates/genesis/src/lib.rs

BSC uses Parlia consensus engine. To support BSC genesis, Parlia config is added.
Update genesis config to support Parlia.

feat: add Parlia genesis config for BSC

---

crates/provider/src/provider/with_block.rs

feat: block id convenience functions

---

crates/rpc-types-engine/Cargo.toml
crates/rpc-types-engine/src/jwt.rs

Adding `from_file` and `try_create` methods to `JwtSecret`. These method allow the caller to read and write from the filesystem. This change should help fully deprecate and remove the `JwtSecret` struct defined in Reth (see https://github.com/paradigmxyz/reth/issues/8276). 
The implementation and tests are ported over from Reth into Alloy.

feat: Add methods to JwtSecret to read and write from filesystem

---

crates/provider/src/provider/call.rs

Closes #761 
- Ensure the option is propagated to the internal `RpcCall` future params
- drive-by improvements
- remove redundant inner type
- add polling state to simplify taking ownership of data
- remove unnecessary nesting in future creation
- `is_*` functions to remove weird inline `matches!`

refactor: improve eth_call internals

---

crates/rpc-types-trace/src/geth/mod.rs
crates/rpc-types-trace/src/geth/mux.rs

1. Simpler conversion from specific tracer config to GethDebugTracerConfig
2. Single config build method on GethDebugTracingOptions that covers all configs 
1. Impl From for CallConfig, PreStateConfig, MuxConfig
2. Introduce generic build method for trace configs on GethDebugTracingOptions

Specific Configs to GethDebugTracerConfig + generic config build method for GethDebugTracingOptions

---

crates/rpc-client/src/lib.rs

Export the `Waiter` struct to enable specifying it as a return type. e.g. a helper function that adds requests via the `BatchRequest<_, _>::add_call` function and returns a `Vec<Waiter<_>>`. The response can then be awaited using `join_all`. 
Export the `Waiter` struct from the "rpc-client/src/lib.rs" file

export batch waiter

---

Cargo.toml
crates/provider/Cargo.toml
crates/provider/src/builder.rs
crates/provider/src/layers/chain.rs
crates/provider/src/layers/mod.rs
crates/provider/src/provider/trait.rs
crates/rpc-client/src/client.rs

Closes https://github.com/alloy-rs/alloy/issues/604
Add `with_chain()` method to `ProviderBuilder`. The `ChainLayer` will fetch the average block time for the chain and set client's poll interval

feat: set poll interval based on connected chain

---

crates/rpc-client/src/call.rs

transforms the separate CallState::poll_ functions into a single poll loop.
this effectively replaces a waker call with a loop so the response is polled (started) right await without going through the scheduler

style: use poll loop for CallState

---

crates/rpc-client/README.md
crates/rpc-client/src/lib.rs
crates/transport/README.md

Closes #775 
- Move docs to rpc client readme
- Write new alloy-transport readme
- add ReqwestClient type alias for user convenience

docs: move rpc client from transport readme

---

crates/rpc-types/src/eth/filter.rs

Facilitate the iteration of `FilterSet` without the need to first convert it to a `ValueOrArray`.
Implement `IntoIterator` using the underlying `HashSet`.

feat: add iter on FilterSet

---

crates/transport-http/src/hyper_transport.rs
crates/transport-http/src/lib.rs
crates/transport-http/src/reqwest_transport.rs

Close #397 
- Add `HttpConnect` to `alloy_transport_http`
- Add `TransportConnect` impls
- Add type aliases

Feat: HttpConnect

---

crates/rpc-types-engine/src/jwt.rs

Re-creating a `Client` when the claims are out of date is necessary if a custom transport using jwt will be used for more than 60 seconds. To do this, the transport could re-create only if the current claims are within the time window. However, this method is private, so no such custom transport can be created without pasting the existing methods and constants.
Expose `is_within_time_window`

chore: expose Claims is_within_time_window as pub

---

crates/consensus/src/account.rs

Closes https://github.com/alloy-rs/alloy/issues/780

feat(consensus) implement RLP for Account information

---

crates/rpc-types/src/eth/log.rs

Currently there is not an elegant way of accessing the event signature in the `Log` as returned by the `SubscriptionStream`, which is useful for matching against when one subscribes to all (or multiple) contract events.
For context: https://github.com/alloy-rs/examples/blob/dbe65d8ca96348ffa64720ea566079e7c1e87fbf/examples/subscriptions/examples/subscribe_all_logs.rs#L45-L62
~~Adds simple getter for 0-indexing into `topics`, mirrors the `event_signature` syntax used for setting `topic0` on the `Filter` instance. I don't see a good reason to add getters for the other topics.~~
Adds simple getter for `topic0`, checking for existence.

feat(rpc-types): add topic0 (alias `event_signature`) getter to `Log`

---

crates/provider/src/ext/engine.rs

GetPayloadV3 returns a V3 execution payload, not a V2 execution payload
Return a v3 execution payload from get_payload_v3

fix: return ExecutionPayloadV3 from get_payload_v3

---

crates/contract/src/call.rs
crates/contract/src/eth_call.rs
crates/provider/src/provider/call.rs
crates/provider/src/provider/trait.rs

Close https://github.com/alloy-rs/alloy/issues/785
Add `Resp`, `Output`,  and `Map` generic type parameters to EthCall to allow it to return `u128`.

feat: Add overrides to eth_estimateGas

---

crates/provider/src/ext/engine.rs

I messed up the previous fix (https://github.com/alloy-rs/alloy/pull/803), the get payload v2 and v3 call should not actually return `ExecutionPayloadV2` / `ExecutionPayloadV3` at all, instead they need to return the envelope.
Use the envelope as the return value.

fix: use envelopes in get_payload API

---

crates/provider/src/fillers/gas.rs
crates/provider/src/utils.rs

ref https://github.com/foundry-rs/foundry/issues/7806
It seems that some of the chains always require non-zero priority fee.
Enforce minimum 1 wei priority fee in default estimator. In ethers we had similar constant set to 3 gwei so this shouldn't cause any issues.

fix: set minimal priority fee to 1 wei

---

crates/provider/src/ext/mod.rs
crates/provider/src/ext/trace.rs
crates/provider/src/lib.rs
crates/provider/src/provider/mod.rs
crates/provider/src/provider/trait.rs

This comment above some trace methods
`// todo: move to extension trait`
Moved trace related methods, types and tests from `provider/trait.rs` to `ext/trace.rs`

chore: move trace methods from `Provider` to `TraceApi`

---

crates/rpc-types-engine/src/lib.rs

This PR moves engine API v4 capabilities from reth to alloy (https://github.com/paradigmxyz/reth/issues/8565).
Adds new capabilities to array.

chore: add engine api v4 capabilities

---

crates/rpc-types-engine/src/lib.rs

smol followup to #822
adds engine_getClientVersionV1 to CAPABILITIES

chore: add engine_getClientVersionV1

---

crates/provider/src/builder.rs
crates/provider/src/fillers/mod.rs

Closes #821 
- Changes `RecommendFiller` -> `RecommendedFiller`
- Groups the export with the other fillers so it is accessible on `fillers::RecommendedFiller` in the `alloy` meta-crate

feature: re-export `RecommendedFiller` in `alloy` meta-crate

---

crates/provider/src/provider/trait.rs
crates/rpc-types/src/eth/block.rs

closes #805
this changes the deserialization order, so empty response is deserialized as `Full`
this adds an additional check to get_block_by calls to enforce hashes

feat: full block ambiguity

---

crates/signer-gcp/Cargo.toml

`0.24.7` [released](https://github.com/abdolence/gcloud-sdk-rs/releases/tag/v0.24.7) in the last hour throws a deep build issue that is breaking the CI
```
error[E0412]: cannot find type `Operation` in module `super::super::super::super::longrunning`
--> /home/zerosnacks/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gcloud-sdk-0.24.7/src/../genproto/google.cloud.kms.v1.rs:1432:70
|
1432 |             tonic::Response<super::super::super::super::longrunning::Operation>,
|                                                                      ^^^^^^^^^ not found in `super::super::super::super::longrunning`
For more information about this error, try `rustc --explain E0412`.
```
Pin to `=0.24.6`

Bug(upstream): pin `gcloud-sdk` to `0.24.6`

---

crates/signer-gcp/Cargo.toml

Undoes #836, upgrades to `0.24.7`
Adds the `google-longrunning` feature flag, now required.
See: https://github.com/abdolence/gcloud-sdk-rs/issues/144

Fix: unpin `gcloud-sdk` to `0.24`, reverting #836

---

crates/provider/src/provider/trait.rs
crates/rpc-types/src/eth/block.rs

Closes #834 
Implements change as suggested, including the inverse `From` impl
Changes `full` to `kind` and uses the enum

feature(rpc): use `BlockTransactionsKind` enum instead of bool for full arguments

---

crates/network/src/transaction/builder.rs

adds helper function that makes it possible to use builder style chained calls that need to check builder fields like `builder.apply(|b| {if b.blob_sidecar.is_none() {} else {}})`
cc @allnil

feat: add TransactionBuilder::apply

---

crates/provider/src/builder.rs
crates/provider/src/fillers/chain_id.rs
crates/provider/src/fillers/gas.rs
crates/provider/src/fillers/join_fill.rs
crates/provider/src/fillers/mod.rs
crates/provider/src/fillers/nonce.rs
crates/provider/src/fillers/signer.rs

Closes #830 
Ensure that `from` is set before gas estimation occurs
Ensure that all properties that can be filled entirely locally are filled BEFORE any network requests are made
This will set `from` and `chain_id` synchronously locally
Potential followup:
- change to sync mutex in noncefiller

[feat] Synchronous filling

---

crates/rpc-types-anvil/src/lib.rs

Foundry needs the default value of `NodeForkConfig`. 
ref: https://github.com/foundry-rs/foundry/blob/7e6ebaf09dcb1ca6f7087d87d20d8ef9435a3ec6/crates/anvil/src/eth/api.rs#L1766-L1776
Also, the original `NodeForkConfig` on the foundry side implements `Default`.
ref: https://github.com/foundry-rs/foundry/blob/7e6ebaf09dcb1ca6f7087d87d20d8ef9435a3ec6/crates/anvil/core/src/types.rs#L185-L192
related to: https://github.com/foundry-rs/foundry/issues/8084, https://github.com/alloy-rs/alloy/issues/838, and https://github.com/foundry-rs/foundry/pull/8098
Adds `Default` derive to `NodeForkConfig` struct

rpc-types-anvil: Implement `Default` to `NodeForkConfig`

---

crates/consensus/src/lib.rs
crates/consensus/src/receipt/any.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/receipt/mod.rs
crates/consensus/src/receipt/receipts.rs
crates/consensus/src/receipt/status.rs
crates/rpc-types/src/eth/transaction/receipt.rs

Closes #630 
Support receipts from 2017 and earlier
- Add an enum that covers the pre- and post-Eip658 values
- impl serde and rlp for that enum
- change receipt to manual serialize impl to allow for naming `root` or `status`
- add docs warning of incorrect status behavior for old receipts
- 
Open question
- when serializing, should the unused field be set to `null` by serializing a `None`?

Fix: Support pre-658 status codes

---

crates/provider/src/provider/trait.rs

Add a shortcut function for sending a `TxEnvelope`
Don't make users call encoded_2718 on their own
Add a provider method to send_envelopes

feat: send_envelope

---

crates/provider/src/ext/engine.rs

Prague introduces v4 methods for `newPayload` and `getPayload`
Added `engine_newPayloadV4` and `engine_getPayloadV4` to the `EngineApi` trait, which uses the existing `ExecutionPayloadV4` and `ExecutionPayloadEnvelopeV4` types.

feat: add engine API v4 methods

---

crates/consensus/src/account.rs
crates/consensus/src/receipt/any.rs
crates/consensus/src/receipt/receipts.rs
crates/consensus/src/receipt/status.rs
crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/legacy.rs
crates/eip7547/src/summary.rs
crates/eips/src/eip1559/basefee.rs
crates/eips/src/eip4895.rs
crates/eips/src/eip6110.rs
crates/eips/src/eip7002.rs
crates/genesis/src/lib.rs
crates/rpc-types-anvil/src/lib.rs
crates/rpc-types-engine/src/optimism.rs
crates/rpc-types-engine/src/payload.rs
crates/rpc-types-trace/src/filter.rs
crates/rpc-types-trace/src/otterscan.rs
crates/rpc-types/src/eth/block.rs
crates/rpc-types/src/eth/fee.rs
crates/rpc-types/src/eth/log.rs
crates/rpc-types/src/eth/transaction/mod.rs
crates/rpc-types/src/eth/transaction/optimism.rs
crates/rpc-types/src/eth/transaction/receipt.rs
crates/rpc-types/src/eth/transaction/request.rs
crates/rpc-types/src/eth/txpool.rs
crates/serde/src/bool.rs
crates/serde/src/lib.rs
crates/serde/src/quantity.rs

Highlights that this is Ethereum JSON-RPC `quantity` encoding, removes `ruint` from the name, and makes it generic
Unfortunately `#[deprecated]` does not emit any warnings for `serde(with = "...")` invocations

feat(serde): deprecate individual num::* for a generic `quantity` module

---

crates/provider/src/provider/trait.rs

Closes https://github.com/alloy-rs/alloy/issues/371
Adds notice on `Provider` trait

chore(provider): document privileged status of EIP-1559

---

crates/contract/src/call.rs
crates/provider/src/lib.rs
crates/provider/src/provider/mod.rs
crates/provider/src/provider/root.rs
crates/provider/src/provider/trait.rs

Closes #450 
Add `fn builder() -> ProviderBuilder` in the `Provider` trait. 
@prestwich @mattsse ptal

feat(provider): expose `ProviderBuilder` via `fn builder()`

---

crates/consensus/Cargo.toml
crates/consensus/src/transaction/envelope.rs

cargo t requires eips arbitrary

fix: make test compile

---

crates/network/src/any/mod.rs
crates/network/src/ethereum/mod.rs
crates/network/src/lib.rs

from: https://github.com/alloy-rs/alloy/issues/845
It would be helpful to know the tx status from the receipt gotten by `get_receipt` method in `PendingTransactionBuilder` or by `get_transaction_receipt` in `Provider`.
Define `status` method in `ReceiptResponse` trait and implement it in `TransactionReceipt` for each network

network: Add `status` method to `ReceiptResponse` trait

---

crates/provider/src/provider/trait.rs
crates/rpc-types-eth/src/transaction/receipt.rs

To ensure that the fields present in the tx receipt for Arbitrum and Optimism are captured correctly
from: https://github.com/alloy-rs/alloy/issues/424

rpc-types-eth: Add receipt deserialize tests for `AnyTransactionReceipt`

---

crates/consensus/src/receipt/any.rs
crates/consensus/src/receipt/envelope.rs
crates/consensus/src/transaction/envelope.rs
crates/eips/src/eip2718.rs

closes #283 and more!
Turns out we weren't even using the 2718 error type.
Change Decodable2718 to use the error type.
Add docs about network encoding vs 2718 encoding
remove erroneous references to RLP in 2718 docs

[Fix] use Eip2718Error, add docs on different encodings

---

.github/ISSUE_TEMPLATE/BUG-FORM.yml
.github/ISSUE_TEMPLATE/FEATURE-FORM.yml

Make it easier for (new) users to select the component category or `other` if they are not sure and report issues with exports in the `alloy` meta-crate.
- add `meta-crate`, `serde` and `other` as categories
- nodes -> `node-bindings`

chore(general): update issue templates

---

crates/transport-http/src/hyper_transport.rs
crates/transport-http/src/reqwest_transport.rs
crates/transport/src/error.rs

Ref #288 
Add `HttpError` struct with `status` and `body`. Add congruent `HttpError` enum to `TransportErrorKind`

feat(transport): HttpError

---

Cargo.toml
crates/provider/src/provider/trait.rs
crates/transport-ws/Cargo.toml
crates/transport-ws/src/lib.rs

closes #874
~~tmp rolls back tungstenite before tls backend is disabled.
Update:
enable rustls/ring as the default backend instead

fix: downgrade tokio-tungstenite

---

crates/alloy/Cargo.toml
crates/provider/src/lib.rs

Closes #876 
- Makes sure to enable `rpc-client` when enabling `rpc-client-ws` so that you do not also need to add the `rpc-client` flag if you if `rpc-client-ws`. This behavior is in line with the other feature flags.
- For easy of access make select `rpc-client` features (`WsConnect`) and (`IpcConnect`) directly available (if defined as flag) on the provider. Previously this required separately defining the `rpc-client` flag and importing it from the `rpc::client` namespace.
Related PR (see impact of proposed changes): https://github.com/alloy-rs/examples/pull/106

feat(alloy): add `"full"` feature flag

---

crates/eips/src/eip7002.rs

There was an update on the naming of the `validatorPublickey` field for EIP-7002:
https://github.com/ethereum/execution-apis/pull/549/files
`s/validator_public_key/validator_pubkey`

chore: update EIP7002 withdrawal requests based on spec

---

crates/rpc-types-eth/src/transaction/error.rs

https://github.com/paradigmxyz/reth/pull/8763 implements conversion of Alloy transaction to Reth transaction for Optimism deposit transactions. In the conversion process, additional errors are required.
[EDIT] Originally, this PR added new errors for the three situations that were not already covered.
After additional discussion, the PR was revised to add a single `Custom(String)` error type that could be used in situations that were not already covered, rather than enumerating all possibilities.
The plan is to remove the whole enum in the future. From @prestwich:
> yeah, let's move this to custom and then plan to delete the whole enum when we embed the tx envelope in the rpc response

add custom conversion error to handle additional situations (such as optimism deposit tx)

---

README.md

As requested in https://github.com/alloy-rs/alloy/issues/791#issuecomment-2154482019
Adds missing links to book and examples in the Alloy's meta-crate so users can more easily find it.
Removes notice about `ethers-rs` maintenance in preparation for the release. 
Once the crates are published (or just before) we can update the `installation` section: https://github.com/alloy-rs/alloy/blob/main/README.md#installation (cc @DaniPopes)

chore(alloy): add link to book and alloy

---

crates/consensus/src/header.rs

we also have serde support for other consensus types.
this can be useful when we want to store these as json: https://github.com/foundry-rs/foundry/pull/8160
cc @samlaf

feat: derive serde for header

---

crates/provider/src/ext/trace.rs

Add `trace_replay_transaction` method.
Example usage:
```rust
use alloy_primitives::{b256};
use alloy_provider::{ext::TraceApi, ProviderBuilder};
use alloy_rpc_types_trace::parity::TraceType;
#[tokio::main]
async fn main() {
let url = std::env::var("ETH_MAINNET_HTTP").expect("$ETH_MAINNET_HTTP must be set.");
let node_url = url::Url::parse(url.as_str()).unwrap();
let provider = ProviderBuilder::new().on_http(node_url);
let result = provider
.trace_replay_transaction(
b256!("45162e66a30e64c5a23c5cee2180874b72322d28ee05439d2dff8d1f6a100417"),
&[TraceType::Trace, TraceType::StateDiff],
)
.await
.unwrap();
println!("{:#?}", result);
}
```

feat: Add trace_replay_transaction

---

crates/rpc-types-eth/src/state.rs

To replace https://github.com/paradigmxyz/reth/blob/c694433675c3fed05fbe72c50476f4a195acafc6/crates/rpc/rpc/src/eth/revm_utils.rs#L30-L41

feat: integrate `EvmOverrides` to rpc types

---

crates/genesis/src/lib.rs

this fixes a serde default issue wheere the previous serde default attribute was bypassed if the entire object was missing

fix: remove bad serde default and replace with manual default for chainconfig

---

crates/eips/src/eip1898.rs

Consider the case where we need to convert a `BlockId` into a `u64`. Currently, this is achievable by the following:
```rust
fn block_id_to_u64(block_id: BlockId) -> Option<u64> {
if let BlockId::Number(number_or_tag) = block_id {
number_or_tag.as_number()
} else {
None
}
}
```
This works but given that the `BlockId::as_block_hash` method already exists, this seems like a logical inclusion into Alloy itself.
https://github.com/alloy-rs/alloy/blob/060de7871a76e99863917e62717c97423c37cadf/crates/eips/src/eip1898.rs#L275-L281

Convenience method for conversion from `BlockId` to `u64`

---

crates/provider/src/ext/trace.rs

Add methods for `trace_raw_transaction` and `trace_replay_block_transactions` to the trace api.
Example:
```rust
use std::str::FromStr;
use alloy_chains::{Chain};
use alloy_network::{EthereumWallet, TransactionBuilder};
use alloy_network::eip2718::Encodable2718;
use alloy_primitives::{Address, U256};
use alloy_provider::{ext::TraceApi, Provider, ProviderBuilder};
use alloy_rpc_types::{BlockNumberOrTag, TransactionRequest};
use alloy_rpc_types_trace::parity::TraceType;
use alloy_signer_local::PrivateKeySigner;
#[tokio::main]
async fn main() {
let url = std::env::var("ETH_MAINNET_HTTP").expect("$ETH_MAINNET_HTTP must be set.");
let node_url = url::Url::parse(url.as_str()).unwrap();
let provider = ProviderBuilder::new().on_http(node_url);
// trace_replay_block_transactions
let result = …
```

feat: Add trace_raw_transaction and trace_replay_block_transactions

---

crates/eips/CHANGELOG.md
crates/eips/src/eip2935.rs

See https://github.com/ethereum/EIPs/blob/45587bd019487b0bd59bec941bc0e2d708811cc8/EIPS/eip-2935.md
Ref https://github.com/paradigmxyz/reth/issues/8379
- Update the history storage address
- Update the history storage system contract bytecode

chore: update eip-2935 bytecode and address

---

crates/rpc-types-anvil/src/lib.rs

Closes: https://github.com/alloy-rs/alloy/issues/838
Required for: https://github.com/foundry-rs/foundry/issues/8084
Related PR in Foundry: https://github.com/foundry-rs/foundry/pull/8186
Adds `Index`, previously missing from the `rpc-types-anvil`
Fixes deserialization issue in `MineOptions`
Also added some tests for `Forking`, `Index` and `MineOptions` serialization as this was giving trouble in Foundry

feat(rpc-types-anvil): add `Index`, fix compatibility

---

Cargo.toml

https://github.com/crate-ci/cargo-release/blob/f0b5af40b903aedd103992366d0875fe2b9f2f99/docs/faq.md?plain=1#L133-L137
> ## How do I do a release when there is dependency cycle in my workspace?
> 
> If this is for dev-dependencies, just declare your dev-dependency with only a path, no version, and it should work out.
> 
> If you have other cycles, open an issue, we'd love to hear about your use case and see how we can help!
This should be equivalent since we pin to latest version anyway.

chore: relax version in workspace dependencies

---

crates/rpc-types-anvil/src/lib.rs
crates/rpc-types-eth/src/index.rs

Noticed that `Index` was already defined in `rpc-types-eth`, removing the need to define it again in `rpc-types-anvil`.
See: https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types-eth/src/index.rs

chore(rpc-types): remove duplicate `Index` definition in `rpc-types-anvil` in favor of the one in `rpc-types-eth`

---

crates/rpc-types-trace/CHANGELOG.md
crates/rpc-types-trace/Cargo.toml
crates/rpc-types-trace/src/geth/mod.rs

Fixes #929 
For me it feels more rust like to use `{variant}::try_from(geth_trace)` instead of `geth_trace.try_into_{variant}()`. How do you feel about that @mattsse?
Example:
```rust
use alloy_primitives::b256;
use alloy_provider::{ext::DebugApi, ProviderBuilder};
use alloy_rpc_types_trace::geth::{
GethDebugBuiltInTracerType, GethDebugTracerConfig, GethDebugTracerType, GethDebugTracingOptions, GethDefaultTracingOptions,
PreStateConfig, PreStateFrame, TraceResult,
};
use std::convert::{TryFrom, TryInto};
#[tokio::main]
async fn main() {
let url = std::env::var("ETH_MAINNET_HTTP").expect("$ETH_MAINNET_HTTP must be set.");
let node_url = url::Url::parse(url.as_str()).unwrap();
let provider = ProviderBuilder::new().on_http(node_url);
let tracer_opts = GethDebugTracingOptions {
tracer: …
```

feat: add TryFrom for GethTrace for all inner variants

---

crates/provider/src/ext/trace.rs
crates/provider/src/provider/trait.rs

this should mark trace_filter as done here https://github.com/alloy-rs/alloy/issues/926

feat: add trace_filter method

---

Cargo.toml
crates/provider/src/provider/trait.rs

Closes https://github.com/alloy-rs/alloy/issues/951

fix: enable tls12 in rustls

---

crates/eips/src/eip2930.rs
crates/serde/src/lib.rs
crates/serde/src/optional.rs

We recently adopted the `AccessList` and `AccessListItem` types for EDR/Hardhat. This fixes an issue when deserializing an `AccessListItem` where the `null` value for storage keys was not accepted.
Added a custom serde deserialization handler.

fix: deserialization of null storage keys in AccessListItem

---

crates/transport-ipc/src/lib.rs

This PR closes #957 . On large non continuous IPC data, current code will drop the buffer.
Remove the check for CAPACITY

fix: continue reading ipc on large data

---

crates/contract/src/event.rs
crates/rpc-types-eth/src/filter.rs

Resolves #824 
This PR adds builder methods to `alloy_contract::Event` that mirror `Filter`'s builder methods, forwarding calls such that you can customize the filter from the event.
Tbh, I don't like copy-pasting all of this, but I think the DX improvement is worth it.
Adds a single test, since the inner methods are tested in Filter's tests.

feat(contract): implement Filter's builder methods on Event

---

crates/alloy/Cargo.toml
crates/consensus/Cargo.toml
crates/eips/Cargo.toml
crates/eips/README.md
crates/eips/src/eip6110.rs
crates/eips/src/eip7251.rs
crates/eips/src/eip7702/auth_list.rs
crates/eips/src/eip7702/constants.rs
crates/eips/src/eip7702/mod.rs
crates/eips/src/lib.rs
crates/rpc-types-eth/Cargo.toml

EIP-7702 is up for inclusion in Prague.
Adds helpers and some types specified in [EIP-7702](https://eips.ethereum.org/EIPS/eip-7702).
The transaction type itself will be added in another PR as it is not relevant right now (for example, the RPC spec has not been updated yet).
This also adds a `k256` feature to `alloy_eips` since authority recovery requires signature recovery which is only possible with `k256` enabled in `alloy_primitives`

feat: add eip-7702 helpers

---

crates/eips/src/eip7702/auth_list.rs

Small PR that adds serde to new types.
And adds `Eq, PartialEq` for `SignedAuthorization`

chore(eips): Add serde to Authorization types

---

crates/contract/src/call.rs

When using a StateOverride with a CallBuilder to estimate_gas, the state overrides were not being applied.
i.e.
`contract.function(args).state(state).estimate_gas().await;`
If the state property has been set, apply the overrides when calling the provider estimate_gas method.

hotfix(contract): support state overrides for gas estimation

---

crates/alloy/Cargo.toml

Closes #965 
In support of the suggested feature as people often express their preference for one over the other
Avoids introducing breaking changes, adds two new flags: `reqwest-rustls-tls` and `reqwest-native-tls`
If a breaking change were permitted I would add the flag like this: 
https://github.com/alloy-rs/alloy/blob/7c1df0fc4a5aafa5d3cceedc58d103ae04047a3a/crates/alloy/Cargo.toml#L67-L103

feat(alloy): forward `rustls` & `native` reqwest TLS configuration to Alloy's metacrate

---

crates/network/src/any/mod.rs
crates/network/src/ethereum/mod.rs
crates/network/src/lib.rs

It would be nice to have a method to get input data from `TransactionResponse`.
During my development, there was a situation in which I wanted to know what method was being called and with what arguments from `TransactionResponse`.
Adds `input` method to `TransactionResponse` and implements it to `TransactionResponse` type for each `Network`

feat(network): Add `input` method to `TransactionResponse`

---

crates/rpc-types-eth/src/filter.rs

Currently there are no checks in the `with_from_block` and `with_to_block` methods to ensure the validity of the given block numbers and thus avoid false ranges.
This pull request adds unit tests for the `FilterBlockOption` struct, specifically focusing on the `with_from_block` and `with_to_block` methods. These tests ensure that the methods correctly handle various scenarios, including valid and invalid block ranges.
- **`with_from_block`**: Added a check to ensure that the `from_block` value is not greater than the `to_block` value. If this condition is violated, the method will panic with an appropriate error message.
- **`with_to_block`**: Added a check to ensure that the `to_block` value is not less than the `from_block` value. If this condition is violated, the method will panic …

add range test in `FilterBlockOption`

---

crates/alloy/Cargo.toml
crates/alloy/src/lib.rs

Closes https://github.com/alloy-rs/alloy/issues/973
Don't import reqwest or hyper, just enable the relevant sub features with question mark syntax.

chore(deps): remove reqwest and hyper from meta crate

---

crates/rpc-types-mev/src/eth_calls.rs

ref https://github.com/paradigmxyz/reth/issues/9112
add missing (undocumented) fields

feat: add missing eth bundle args

---

crates/provider/src/fillers/nonce.rs

Removes dependency on tokio mutex and make the map smaller.

chore(provider): simplify nonce filler

---

crates/eips/src/eip1898.rs

Useful to switch between `BlockHashOrNumber` hash and `BlockId` hash.

feat: impl `From<RpcBlockHash>` for `BlockHashOrNumber`

---

crates/rpc-types-trace/src/parity.rs

feat: add helpers for trace action

---

crates/contract/src/call.rs

Sometimes we don't want to `send()` a transaction created with `CallBuilder`, but instead convert it to `TransactionRequest`, in order to later include it in a bundle.
`CallBuilder::as_ref()` could be used, but it would require to clone the resulting `&TransactionRequest` to call `FillProvider::fill()`.
Adding `into_transaction_request()` to `CallBuilder`.
Cc @igorline

Allow to convert CallBuilderTo TransactionRequest

---

crates/provider/src/ext/debug.rs

Adds the missing `debug_*` methods in https://github.com/alloy-rs/alloy/issues/926
Note that even though the issue says that we want to achieve full compatibility with reth, some of these methods are not implemented, like [`debug_getBadBlocks`](https://github.com/paradigmxyz/reth/blob/5416adf97b8e333c9a04ed9f3a18cdffd1a4f5f2/crates/rpc/rpc/src/debug.rs#L713).
Also note that the tests are dummies because:
- Proper tests should probably live in the node implementations. 
- These methods are not supported by anvil.

feat: add missing debug_* rpc methods

---

crates/rpc-types-eth/src/index.rs

makes it easier to access the value and use it as a wrapper

chore: make wrapped index value pub

---

crates/alloy/Cargo.toml
crates/provider/Cargo.toml
crates/provider/src/ext/mod.rs
crates/provider/src/ext/net.rs

Adds the `net` namespace to the json-rpc methods supported. Work towards completing #926.
Decided to convert from `PeerCount` to `u64` since it's more convenient for the end-user, but lmk if this is not expected.
There was no need for an `rpc-types-net` crate, so decided not to add one.

feat: add net rpc namespace

---

.github/workflows/ci.yml

``warning: the `wasm32-wasi` target is being renamed to `wasm32-wasip1` and the `wasm32-wasi` target will be removed from nightly in October 2024 and removed from stable Rust in January 2025``

ci: fix wasi job

---

crates/provider/src/ext/trace.rs

Adds the missing trace_get method in https://github.com/alloy-rs/alloy/issues/926
Currently trace_get returns null if queries with multiple indices (params example: "params":["0x346b152d421c095a2eab383d9c5d0309bb28c31e8c5b84fdc6a4f38e2194558d", ["0x0", "0x1"]]) https://github.com/paradigmxyz/reth/pull/3852
Because of this, i choose to use param `index` with type u64, to remove footgun.
Usage example. Replace RETH_ENDPOINT with endpoint
```
use alloy_primitives::{b256};
use alloy_provider::{ext::TraceApi, ProviderBuilder};
#[tokio::main]
async fn main() {
let url = String::from("RETH_ENDPOINT");
let node_url = url::Url::parse(url.as_str()).unwrap();
let provider = ProviderBuilder::new().on_http(node_url);
let result = provider
.trace_get( …
```

feat: Add trace_get

---

crates/rpc-types-beacon/src/relay.rs

currently only one query value is supported, but having a container type for this is more convenient

feat: add submit block request query

---

crates/rpc-types-trace/src/otterscan.rs

the response of `ots_getContractCreator` from https://github.com/otterscan/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_getcontractcreator as below:
> object containing the following attributes, or null if the address does not contain a contract.
hash - The tx hash of the transaction who created the contract.
creator - The address who directly created the contract. Note that for simple transactions that directly deploy a contract this corresponds to the EOA in the from field of the transaction. For deployer contracts, i.e., the contract is created as a result of a method call, this corresponds to the address of the contract who created it.
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"hash": "0xe881c43cd88063e84a1d0283f41ee5348239b259c0d17a7e2e4552da3f4b2bc7",
"creator": …
```

fix: ots_getContractCreater has field hash instead of tx

---

crates/eips/src/eip7702/auth_list.rs

We've updated EIP-7702 to use the same RLP encoding order throughout the EIP, so the helper struct we have now is no longer necessary.
Ref https://github.com/ethereum/EIPs/pull/8679

chore: clean up 7702 encoding

---

crates/rpc-types-trace/src/otterscan.rs

Add `output` for the response of `ots_traceTransaction` 
ref https://github.com/ledgerwatch/erigon/blob/15d922368f520b3d67035f5012c93bc266a2a638/turbo/jsonrpc/otterscan_trace_transaction.go#L32-L40

feat(otterscan): add output for TraceEntry

---

crates/network/src/any/mod.rs
crates/network/src/ethereum/mod.rs
crates/network/src/lib.rs

Ref #1002 
Add `block_hash` and `block_number` to `ReceiptResponse`

feat(network): block context in ReceiptResponse

---

crates/provider/src/ext/admin.rs
crates/rpc-types-admin/src/admin.rs

Adds missing `admin_*` RPC methods. Work towards completing #926.

feat: add missing admin_* methods

---

crates/eips/src/eip1559/basefee.rs
crates/eips/src/eip1559/constants.rs
crates/eips/src/eip1559/helpers.rs

Related https://github.com/paradigmxyz/reth/issues/9275

test: add missing unit test for op `calc_next_block_base_fee`

---

README.md

The `rpc-types-mev` crate is not listed in the crates list on the README

chore(docs): Add the missing crate `rpc-types-mev`

---

crates/consensus/src/transaction/envelope.rs

When operating on RLP-encoded transactions it's useful to access this data without the need to convert `TxEnvelope` into `TypedTransaction`.

feat: impl Transaction for TxEnvelope

---

crates/rpc-types-eth/src/block.rs

There are currently multiple Block Header types (@mattsse told me it's because of legacy naming).  
This PR adds a way to convert one into the other. I needed that in order to then RLP encode the Header. I added tests at the bottom to make sure the RLP encoding is correct and correctly recomputes the block hash

chore: convert rcp-types-eth block Header to consensus Header

---

crates/rpc-types-eth/src/transaction/request.rs

https://github.com/foundry-rs/foundry/issues/7764
some node impls still only accept the legacy data field...
this makes it easy to set both

feat: add helper to set both input and data fields

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs

I noticed that TxEnvelope::encode/decode didn't produce the same TxEnvelope. The difference was the hash only.
I fixed the issue for TxEip1559, TxEip2930, TxEip4844, TxEip4844WithSidecar and TxEip4844Variant.
Related to: https://github.com/alloy-rs/alloy/pull/150
Fixes https://github.com/alloy-rs/alloy/issues/897

Remove signature.v parity before calculating tx hash

---

Cargo.toml
crates/contract/src/eth_call.rs
crates/network/src/any/mod.rs
crates/network/src/lib.rs
crates/provider/src/fillers/mod.rs
crates/provider/src/lib.rs
crates/provider/src/provider/call.rs
crates/provider/src/provider/with_block.rs
crates/pubsub/src/lib.rs
crates/rpc-client/src/batch.rs
crates/rpc-client/src/lib.rs
crates/rpc-types-eth/src/lib.rs
crates/serde/src/other/arbitrary_.rs
crates/serde/src/quantity.rs
crates/signer-local/src/lib.rs
crates/transport/src/error.rs
crates/transport/src/lib.rs

Great new rustc lint
Supersedes https://github.com/alloy-rs/alloy/pull/1028

chore: fix unnameable types

---

crates/consensus/src/transaction/eip2930.rs
crates/eips/src/eip7702/auth_list.rs

eip7702 AuthorizationList rlp format is not correct.
The format that gets encoded is: `0xf85ed801940000000000000000000000000000000000000006c101f8431ba048b55bfa915ac795c431978d8a6a992b628d557da5ff759b307d495a36649353a0efffd310ac743f371de3b9f7f9cb56c0b28ad43601b4ab949f53faa07bd2c804`
That decoded is:
`[["0x01","0x0000000000000000000000000000000000000006",["0x01"]],["0x1b","0x48b55bfa915ac795c431978d8a6a992b628d557da5ff759b307d495a36649353","0xefffd310ac743f371de3b9f7f9cb56c0b28ad43601b4ab949f53faa07bd2c804"]]`
https://toolkit.abdk.consulting/ethereum#rlp
There are two inner lists that should not be there.
Removed Generic over `SignedAuthorization` as it seems it is not needed. We default to Signature (can revert back if this is not the case)

fix(eip7702): Add correct rlp decode/encode

---

crates/eips/src/eip7702/auth_list.rs

adds `Hash` support for auth types
hashing r+s+v should be appropriate for all signature forms

feat: add hash for 7702

---

crates/eips/src/eip7702/auth_list.rs

closes #1031
note we don't have an easy way to generate random valid k256 sigs, so this just uses a hardcoded one

feat: add arbitrary to auth

---

Cargo.toml
crates/consensus/Cargo.toml
crates/consensus/src/request.rs
crates/eips/Cargo.toml
crates/eips/src/eip1898.rs
crates/eips/src/eip2930.rs
crates/eips/src/eip4844/sidecar.rs
crates/eips/src/eip4895.rs
crates/eips/src/eip6110.rs
crates/eips/src/eip7002.rs
crates/eips/src/eip7251.rs
crates/eips/src/eip7702/auth_list.rs
crates/rpc-types-eth/Cargo.toml
crates/rpc-types-eth/src/log.rs
crates/rpc-types-eth/src/transaction/receipt.rs
crates/rpc-types-trace/Cargo.toml
crates/serde/Cargo.toml
crates/serde/src/other/arbitrary_.rs
crates/serde/src/other/mod.rs

This was only required because reth required these types to implement `proptest::Arbitrary`. This is no longer the case, and `arbitrary::Arbitrary` is already usable.
Remove ~~almost~~ all proptest derives, remove unused proptest dependencies.
~~There is a single `proptest!` left, which is for other fields, would like to know whether that's necessary or not.~~

chore: remove proptest in all crates and Arbitrary derives

---

crates/alloy/Cargo.toml

The `rpc-types-mev` feature is missing in `alloy` crate.

feat: add `rpc-types-mev` feature to meta crate

---

crates/eips/Cargo.toml
crates/eips/src/eip7702/auth_list.rs

This makes it so the auth list signature is not hard coded, although this gates the arbitrary implementation behind the k256 feature
Just generate a hash, based on the auth, and sign it

feat: generate valid signed auth signatures

---

crates/node-bindings/src/geth.rs
crates/provider/src/ext/admin.rs
crates/rpc-types-admin/src/admin.rs

Return the same response type as geth's, ref https://github.com/ethereum/go-ethereum/blob/v1.14.0/p2p/server.go#L1078-L1079

fix(admin): id in NodeInfo is string instead of B256

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/legacy.rs

That will be needed for https://github.com/paradigmxyz/reth/issues/9484

feat: impl `arbitrary` for tx structs

---

crates/eips/src/eip7702/auth_list.rs

optional authority if recovery failed doesn't make sense.
this should always be Address

chore: make auth mandatory in recovered auth

---

crates/provider/src/chain.rs

I started to work on handling reorgs in `ChainStreamPoller`, but noticed a few adjacent problems that probably should be fixed first.
Here, I noticed that we don't check whether we've reached the LRU cache capacity. As a result, if a lot of blocks are created in a short time (e.g. via `anvil_mine`), some blocks may be skipped.
This PR fixes that, and also adds a few basic tests for `ChainStreamPoller`.
Only add new items to the cache if we don't reach capacity.

fix(provider): Do not overflow LRU cache capacity in ChainStreamPoller

---

crates/consensus/src/constants.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/mod.rs
crates/eips/src/eip7702/auth_list.rs

adds consensus 7702 tx type
this is the same as 1559, just with an additional field.

feat: add 7702 tx type

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/legacy.rs

Needed for https://github.com/paradigmxyz/reth/issues/9484

feat: expose encoded_len_with_signature()

---

crates/rpc-types-eth/src/transaction/request.rs

`max_fee_per_blob_gas` field is not necessary for Eip1559 tx type, but `trim_conflicting_keys` does not trim the field from it.

fix: Trim conflicting key `max_fee_per_blob_gas` from Eip1559 tx type

---

crates/rpc-types-eth/src/syncing.rs

Ref: https://github.com/paradigmxyz/reth/issues/7838
CC: @mattsse 
Adding a new optional field to sync info to show stages sync detail on eth_syncing rpc method.

Added stages to the sync info rpc type

---

crates/provider/src/provider/trait.rs

Blocks: https://github.com/foundry-rs/foundry/pull/8477
Related to: https://github.com/foundry-rs/foundry/issues/8468

removing async get account

---

crates/eips/Cargo.toml
crates/eips/src/eip7702/auth_list.rs
crates/eips/src/lib.rs

This is an attempt to fix https://github.com/alloy-rs/alloy/pull/1070
The key generation can be made infallible by instead seeding a rng, and generating a `NonZeroScalar` with it.

fix(eips): make SignedAuthorizationList arbitrary less fallible

---

crates/consensus/src/account.rs
crates/rpc-types-admin/src/admin.rs
crates/rpc-types-mev/src/mev_calls.rs
crates/rpc-types-trace/src/otterscan.rs
crates/transport/src/error.rs

chore : fix typos

---

crates/consensus/src/request.rs
crates/eips/Cargo.toml
crates/eips/src/eip7702/auth_list.rs
crates/eips/src/lib.rs
crates/node-bindings/src/anvil.rs
crates/provider/src/ext/debug.rs
crates/provider/src/provider/trait.rs
crates/rpc-types-eth/src/account.rs
crates/rpc-types-eth/src/syncing.rs

as mentionned here https://github.com/alloy-rs/alloy/issues/1074 call_many is not implemented

feat: Add call_many 

---

crates/eips/src/eip7702/auth_list.rs

closes https://github.com/alloy-rs/alloy/issues/1068

feat(eip): make 7702 auth recovery fallible

---

crates/rpc-types-trace/src/filter.rs

Filter the trace with trace {action,result}'s address, not by tx's {from, to}_address, inspired by https://github.com/openethereum/openethereum/blob/6c2d392d867b058ff867c4373e40850ca3f96969/crates/ethcore/src/trace/types/filter.rs#L95-L131 and https://github.com/ledgerwatch/erigon/blob/72ab70be8b28964a8446e52b7a9975958c6726bf/turbo/jsonrpc/trace_filtering.go#L238-L289

feat(rpc/trace): filter matches with trace

---

crates/json-rpc/Cargo.toml
crates/json-rpc/src/response/error.rs

Closes #787 
Adds helper method allowing decoding of custom errors from `ErrorPayload`

feat: add helper for decoding custom errors

---

crates/rpc-types-trace/src/parity.rs

That will resolve the issue when the RPC server returns "output": null, as Nethermind does.
That will resolve the issue when the RPC server returns "output": null, as Nethermind does.

fix: make Parity TraceResults output optional

---

crates/rpc-types-eth/src/filter.rs

Make it possible to use non-default `FilterChanges` in reth RPC
Make `Deserialize` impl for `FilterChanges` generic over transaction

chore(rpc): Make `Deserialize` impl for `FilterChanges` generic over transaction

---

crates/rpc-types-eth/src/pubsub.rs

To plug into reth RPC, transaction type needs to be configurable at node builder level and adopted by all types further down, incl `SubscriptionResult`
Make `SubscriptionResult` generic over transaction

Make `alloy_rpc_types_eth::SubscriptionResult` generic over tx

---

crates/eips/src/eip1898.rs

Implementing `reth_rpc_eth_types::EthApiError` https://github.com/paradigmxyz/reth/pull/7416#discussion_r1703734505
Adds conversion from `alloy_eips::BlockHashOrNumber` to `alloy_eips::BlockId`

Add conversion from BlockHashOrNumber to BlockId

---

crates/json-rpc/src/response/error.rs

```
➜  foundry_test git:(master) ✗ cast send 0x5FbDB2315678afecb367f032d93F642f64180aa3  "customError()" --private-key $PK
Error:
server returned an error response: error code 3: execution reverted:
```
cast send result in execution revert with out reason(data) is hard to debug.  
old version of cast send result would be like:  
```
(code: 3, message: execution reverted: CustomError3333, data: Some(String("0x8d6ea8be0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f437573746f6d4572726f72333333330000000000000000000000000000000000"))) 
```
it's good to make cast send print data like "0x8d6ea8be...".
add data to print in fmt

fix(rpc): show data in when cast send result in custom error

---

crates/rpc-types-engine/Cargo.toml
crates/rpc-types-engine/src/lib.rs

ref https://github.com/paradigmxyz/reth/pull/10141

chore(dep): feature gate jwt in engine types

---

crates/rpc-types-eth/Cargo.toml
crates/rpc-types-eth/src/transaction/request.rs

The `TransactionArguments` struct's `build_typed_tx` method will, in case of **EIP-4844** transaction, always try to build  a `TypedTransaction` using `sidecar`.
This isn't necessarily correct if `sidecar` is `None` but `blob_versioned_hashes` are set to `Some(...)`.
In this case, it should be fine to build a transaction _without sidecar_.
This PR allows that to happen.
* implement `build_consensus_tx` for `TransactionRequest` for conversion into `TypedTransaction`
* modifies some _private_ legacy functions to return `Result<...>` instead of panicking
* leaves the other legacy function(s) functionally the same

TxRequest into EIP-4844 without sidecar

---

.github/workflows/ci.yml
crates/provider/src/ext/debug.rs
crates/provider/src/ext/trace.rs
crates/provider/src/provider/trait.rs
crates/provider/src/provider/with_block.rs
crates/rpc-client/src/builtin.rs

Closes #1134 
- Aligns use with Reth implementation, using `BlockId` where implemented
- See: [trace.rs](https://github.com/paradigmxyz/reth/blob/e907f0eab0d90f286f2197ee8935f10817ff1edf/crates/rpc/rpc/src/trace.rs)
- See: [debug.rs](https://github.com/paradigmxyz/reth/blob/e907f0eab0d90f286f2197ee8935f10817ff1edf/crates/rpc/rpc/src/debug.rs)
- Fixes `get_block_receipts` as raised in https://github.com/foundry-rs/foundry/pull/8623
- Align parameter naming, prefer ambigious `block` for consistency
- Adds a new `--all-features` CI flag to make sure all features are actually tested, `trace` / `debug` (and presumably other) tests were not actually ran in the CI. Created https://github.com/alloy-rs/alloy/issues/1136 to investigate failing `subscribe_block_ws` and `subscribe_ws_boxed` tests on …

fix: use `BlockId` superset over `BlockNumberOrTag` where applicable 

---

crates/contract/src/error.rs
crates/provider/Cargo.toml
crates/provider/src/heart.rs
crates/provider/src/lib.rs
crates/provider/src/provider/trait.rs

Currently on `TxWatcher` timeout we just drop it, resulting in `TransportError::BackendGone` error which is not really user-friendly.

fix: return more user-friendly error on tx timeout

---

crates/rpc-types-eth/src/transaction/receipt.rs

```tx_receipt_7702.status()``` would always yield `false`.
Add `ReceiptEnvelope::Eip7702` variant in `match`

fix(rpc-types-eth): match 7702 in TxReceipt.status()

---

crates/consensus/src/transaction/eip7702.rs

Related https://github.com/paradigmxyz/reth/issues/9484

TxEip7702: add payload length methods

---

crates/rpc-types-eth/src/block.rs
crates/rpc-types-eth/src/transaction/mod.rs

Those currently consume all extra data, forcing `AnyNetwork` users to do `value.inner.other` instead of just `value.other`.
Should be merged after https://github.com/alloy-rs/alloy/pull/1106 which makes block responses use `WithOtherFields<Block>` while with this PR returned blocks are just `Block` which will miss extra fields

fix: remove `OtherFields` from Transaction and Block

---

crates/network/src/ethereum/wallet.rs
crates/network/src/transaction/signer.rs

Not needed, and was never object-safe

chore: remove async_trait from NetworkWallet

---

crates/json-rpc/src/lib.rs
crates/json-rpc/src/notification.rs
crates/pubsub/src/managers/in_flight.rs
crates/pubsub/src/managers/req.rs
crates/pubsub/src/managers/sub.rs
crates/pubsub/src/service.rs

Closes https://github.com/alloy-rs/alloy/issues/1158
This adds `SubId` enum similar to `json_rpc::Id` but without `None` variant and with `U256` in place of `Number variant`.

fix: allow arbitrary strings in subscription ids

---

crates/json-rpc/src/request.rs
crates/provider/src/ext/trace.rs
crates/provider/src/lib.rs
crates/provider/src/provider/mod.rs
crates/provider/src/provider/prov_call.rs
crates/provider/src/provider/trait.rs
crates/provider/src/provider/with_block.rs
crates/rpc-client/src/call.rs

Proposing different approach for integrating `ProviderCall` into `RpcWithBlock`
- Add `map_params` method to `RpcCall`, allowing to change request params type. Useful for conversion of `Params` into `ParamsWithBlock`
- Add `WithBlockInner` type, containing two variants: https://github.com/alloy-rs/alloy/blob/1d49e4bd41c25e42c2e82fb24e438efdde301329/crates/provider/src/provider/with_block.rs#L40-L55
The idea is to allow people providing arbitrary `Fn(BlockId) -> ProviderCall` methods
- Change `RpcWithBlock::Future` to `ProviderCall`. When awaited, `RpcWithBlock` will convert `WithBlockInner` into `ProviderCall` by either changing rpc call params, or invoking function.
- Also changed `ProviderCall::Ready` inner value to `Result` to allow error propagation from synchronous sources. …

refactor(`ProviderCall`): don't rely on `Caller` in `RpcWithBlock`

---

crates/provider/src/provider/trait.rs

add missing provider function for eth_getRawTransactionByHash

feat: add get raw transaction by hash

---

Cargo.toml
README.md
crates/rpc-types-debug/CHANGELOG.md
crates/rpc-types-debug/Cargo.toml
crates/rpc-types-debug/README.md
crates/rpc-types-debug/src/debug.rs
crates/rpc-types-debug/src/lib.rs
crates/rpc-types/Cargo.toml
crates/rpc-types/src/lib.rs

https://github.com/paradigmxyz/reth/issues/10404
`debug_executionWitness` is a Reth-only JSON RPC method [recently introduced](https://github.com/paradigmxyz/reth/pull/9249) for generating historical execution witnesses.
This PR contains an updated version that includes state preimages that will be implemented in https://github.com/paradigmxyz/reth/issues/10404.

feat(rpc-types): `debug_executionWitness`

---

crates/provider/src/provider/root.rs
crates/provider/src/provider/trait.rs
crates/pubsub/src/frontend.rs
crates/pubsub/src/ix.rs
crates/pubsub/src/managers/sub.rs
crates/pubsub/src/service.rs
crates/rpc-client/src/client.rs

ref https://t.me/ethers_rs/40198
Uses `server_id` when sending `eth_unsubscribe` request. Also updated all `local_id`s to use `B256` everywhere to avoid unneccesary conversions

fix: use `server_id` when unsubscribing

---

crates/network/src/any/mod.rs
crates/rpc-types-eth/src/block.rs

This PR allows Header to assume a type based on generic.
Closes #1177

feat: make block struct generic over header type

---

crates/network/src/any/mod.rs
crates/rpc-types-eth/src/block.rs

https://github.com/alloy-rs/alloy/pull/1179 added header generic to block as a first one, resulting in a breaking change. I think it is safe to assume that users are more likely to change the transaction generic, especially given that we are already doing this across other codebases

fix: change generics order for `Block`

---

crates/provider/src/chain.rs
crates/provider/src/ext/admin.rs
crates/provider/src/ext/anvil.rs
crates/provider/src/ext/debug.rs
crates/provider/src/ext/net.rs
crates/provider/src/ext/rpc.rs
crates/provider/src/ext/txpool.rs
crates/provider/src/provider/trait.rs
crates/rpc-client/README.md
crates/rpc-client/src/client.rs
crates/rpc-client/src/lib.rs
crates/rpc-client/tests/it/http.rs
crates/rpc-client/tests/it/ipc.rs
crates/rpc-client/tests/it/ws.rs

Turns out unit/empty tuple (`()`) is special-cased in serde to be serialized as `null`, when we want an empty array.
Fixes https://github.com/alloy-rs/alloy/issues/1190

fix(provider): serialize no parameters as `[]` instead of `null`

---

crates/rpc-types-eth/src/block.rs
crates/rpc-types-trace/src/otterscan.rs

chore: rm Rich type

---

crates/transport/src/error.rs

I received a 503 status code from Alchemy indicating the service was temporarily unavailable. This caused a long-running process to abort so naturally I started to add the RetryBackoffLayer functionality but noticed it only retried HTTP errors involving rate limits. The 503 status code represents a temporarily unavailable service and may even indicate when to try the request again making this error a good candidate to retry.
Return true in the `is_retry_err` function when the status code is 503

feat(transport): retry http errors with 503 status code

---

crates/rpc-types-eth/src/transaction/optimism.rs

Should we deprecate optimism types in favor of op-alloy's for the next release?

fix: serde for `depositReceiptVersion`

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/envelope.rs
crates/consensus/src/transaction/legacy.rs
crates/consensus/src/transaction/mod.rs
crates/consensus/src/transaction/typed.rs

Getters needed for making `alloy_network::Network::TransactionResponse` from `alloy_consensus::Transaction` types
Adds missing getters to `alloy_consensus::Transaction`

chore(consensus): Add missing getter trait methods for `alloy_consensus::Transaction`

---

crates/rpc-types-eth/src/filter.rs

`FilterBlockOption` deals with inclusive ranges.
https://github.com/alloy-rs/alloy/blob/02ccb77a26f11198f1dfeacec875f7d871aa4504/crates/rpc-types-eth/src/filter.rs#L171-L179
While passing an exclusive range (eg `.select(start..end)`), it was wrongly including the end range in the filter.
Only allow conversion from `RangeInclusive` instead of `Range`, since decrementing a block tag is not possible.

fix: use `impl From<RangeInclusive> for FilterBlockOption` instead of `Range` 

---

crates/rpc-types-engine/src/payload.rs

adds new variant for when requests are provided before prague, similar to `PreShanghaiBlockWithWitdrawals`

feat: add error for pre prague requests

---

crates/rpc-types-eth/src/transaction/signature.rs

Converting `alloy_consensus::Transaction` types into `alloy_network_primitives::TransactionResponse` types, requires conversion from `alloy_primitives::Signature` to `alloy_rpc_types_eth::Signature`
Implement `From<alloy_primitives::Signature> for alloy_rpc_types_eth::Signature`

Implement conversion between signature types

---

crates/alloy/Cargo.toml

Both of those are already included as `alloy-provider` dependencies, so this just enables useful re-exports for users doing just `features = ["providers"]`

chore(features): enable `consensus` and `network` along with `providers`

---

crates/consensus/src/transaction/eip1559.rs

`TxEip1559::ty()` returns a value indicating EIP-2930 transactions without EIP-1559 features. This is not correct.
Change the value

fix: value of TxEip1559.ty

---

crates/consensus/src/transaction/eip7702.rs

Related https://github.com/paradigmxyz/reth/issues/9484
To be in agreement with https://github.com/paradigmxyz/reth/blob/b0f3949510418e327a39143df5c6c68a7c8fa6d3/crates/primitives/src/transaction/mod.rs#L90-L92 requirement

eip7702: derive `arbitrary::Arbitrary` for `TxEip7702`

---

crates/eips/Cargo.toml

**Description**
Fixes alloy-eips to have `no_std` compat.

fix(eips): no-std compat

---

crates/node-bindings/src/anvil.rs

Anvil builder `new()` method docs states the default port to be 8545. In practice, however, current code sets random port number.
Set default port inside `try_spawn()` to 8545, unless otherwise specified.
Unit test added.

fix: Anvil builder default port

---

Cargo.toml

> warning: /Users/Matthias/git/rust/alloy/crates/eips/Cargo.toml: `default-features` is ignored for derive_more, since `default-features` was not specified for `workspace.dependencies.derive_more`,

chore: derive more default features false

---

crates/network-primitives/src/traits.rs
crates/rpc-types-eth/src/block.rs

`HeaderResponse` exposed very limited fields. `BlockResponse` doesn't expose `other` fields in case of `WithOtherFields<Block>`. 
- Expose `miner, gas_limit, mix_hash, difficulty` in `HeaderResponse`. Exposing these fields helps to initialize a `revm::BlockEnv` like so: 
```rust
BlockEnv {
number: U256::from(block.header().number()),
timestamp: U256::from(block.header().timestamp()),
coinbase: block.header().miner(),
difficulty: block.header().difficulty(),
prevrandao: block.header().mix_hash(),
basefee: U256::from(block.header().base_fee_per_gas().unwrap_or_default()),
gas_limit: U256::from(block.header().gas()),
..Default::default()
}
```
- Add `other_fields(&self) -> Option<OtherFields>` to `BlockResponse` which returns `None` by default unless overridden.

feat(network-primitives): expose more fields via block response traits

---

crates/rpc-types-engine/src/forkchoice.rs

Returning an option whether or not the hash is zero, is useful when processing forkchoice states in reth, because the CL will often send all-zero forkchoice states.
This introduces helper methods which perform the zero check.

feat(rpc-types-engine): add forkchoice state zero helpers

---

crates/consensus/src/header.rs

Related https://github.com/paradigmxyz/reth/issues/10687 cc @mattsse

consensus: implement `Arbitrary` for `Header`

---

.github/workflows/no_std.yml
Cargo.toml
README.md
crates/network-primitives/Cargo.toml
crates/network-primitives/src/block.rs
crates/network-primitives/src/lib.rs
crates/rpc-types-eth/Cargo.toml

> [!NOTE]
>
> Stacked ontop of https://github.com/alloy-rs/alloy/pull/1250
Makes `alloy-network-primitives` support `no_std`.
This is a pre-requisite to supporting `no_std` in `alloy-rpc-types-eth`.

feat: no_std network primitives

---

crates/eips/src/eip1898.rs

this type is useful when dealing with any combinations of number+hash and introduces aliases that remove Block form the name so that this can be used when the number or the hash don't originate from a block

chore: add aliases for Num Hash

---

crates/rpc-types-trace/src/parity.rs

I'm checking with reth's trace results with erigon's, seems erigon will always return `result:null` if no error occurred:
And found the OG OpenEthereum's serialized logic as below:
https://github.com/openethereum/openethereum/blob/main/crates/rpc/src/v1/types/trace.rs#L532
```rust
match self.result {
Res::Call(ref call) => struc.serialize_field("result", call)?,
Res::Create(ref create) => struc.serialize_field("result", create)?,
Res::FailedCall(ref error) => struc.serialize_field("error", &error.to_string())?,
Res::FailedCreate(ref error) => struc.serialize_field("error", &error.to_string())?,
Res::None => struc.serialize_field("result", &None as &Option<u8>)?,
}
```

feat(rpc-types-trace): always serialize result if no error

---

crates/rpc-types-trace/src/otterscan.rs

Ref https://github.com/foundry-rs/foundry/issues/8830#issuecomment-2338108826
`OtsReceipt` uses `alloy_primitives::Log`. 
Use `rpc_types_eth::Log` instead of `alloy_primitives::Log`

fix(rpc-types-trace): use rpc-types Log in OtsReceipt

---

crates/network-primitives/src/traits.rs

Small PR to remove the unused `alloc::vec::Vec` dependency in `alloy-network-primitives`.

chore(network-primitives): Remove alloc Vec Dep

---

crates/consensus/src/header.rs

Removes the redundant commented out `parent_num_hash` method that has [a `const` impl further below](https://github.com/alloy-rs/alloy/blob/main/crates/consensus/src/header.rs#L357).

chore(consensus): Remove Header Method

---

crates/consensus/src/header.rs

Helper for https://github.com/paradigmxyz/reth/pull/10691

consensus: implement `seal` helper for `Header`

---

crates/provider/src/fillers/nonce.rs
crates/rpc-types-eth/src/simulate.rs
crates/rpc-types-eth/src/state.rs

Updates serde for `eth_simulateV1` to match JSON encoding in geth. ref https://github.com/ethereum/go-ethereum/pull/27720
There's another change for `BlockOverrides` fields which I am not sure we should address now:
> Block override fields of eth_call and debug_traceCall have had the following fields renamed
> * `coinbase` -> `feeRecipient`
> * `random` -> `prevRandao`
> * `baseFee` -> `baseFeePerGas`

fix: serde for `eth_simulateV1`

---

crates/network-primitives/src/traits.rs
crates/rpc-types-eth/src/transaction/receipt.rs

Use generic `ReceiptResponse` type in place of `alloy_rpc_types_eth::TransactionReceipt` in reth RPC
Adds trait methods `ReceiptResponse::cumulative_gas_used` and `ReceiptResponse::state_root`

Add trait methods `cumulative_gas_used` and `state_root` to `ReceiptResponse`

---

crates/node-bindings/src/nodes/reth.rs
crates/provider/src/ext/debug.rs
crates/provider/src/ext/trace.rs
crates/rpc-types-eth/src/call.rs

Closes: https://github.com/alloy-rs/alloy/issues/1074
Does not include the addition of `eth_callMany`, to be added in https://github.com/alloy-rs/alloy/issues/1274 as it requires more consideration (i.e. it being integrated into `multicall` or the `EthCall` builder). Ties into #328 / #1119.
Excludes Reth binding improvements previously added in https://github.com/alloy-rs/alloy/pull/1076#event-14227702047.

fix: `debug_traceCallMany` and `trace_callMany`

---

crates/contract/Cargo.toml
crates/network/Cargo.toml
crates/provider/Cargo.toml
crates/rpc-types-engine/Cargo.toml
crates/rpc-types-eth/Cargo.toml
crates/rpc-types-eth/src/account.rs
crates/rpc-types-eth/src/block.rs
crates/rpc-types-eth/src/call.rs
crates/rpc-types-eth/src/erc4337.rs
crates/rpc-types-eth/src/fee.rs
crates/rpc-types-eth/src/filter.rs
crates/rpc-types-eth/src/index.rs
crates/rpc-types-eth/src/log.rs
crates/rpc-types-eth/src/pubsub.rs
crates/rpc-types-eth/src/simulate.rs
crates/rpc-types-eth/src/state.rs
crates/rpc-types-eth/src/syncing.rs
crates/rpc-types-eth/src/transaction/mod.rs
crates/rpc-types-eth/src/transaction/receipt.rs
crates/rpc-types-eth/src/transaction/request.rs
crates/rpc-types-eth/src/transaction/signature.rs
crates/rpc-types-eth/src/work.rs
crates/rpc-types-trace/Cargo.toml
crates/signer-trezor/Cargo.toml

Downstream crates would like to use types from `alloy-rpc-types-eth` without the need for `serde` support. This PR places serialization for core eth types behind the `serde` feature flag that is enabled-by-default.

feat(alloy-rpc-types-eth): Optional serde

---

crates/eip7547/Cargo.toml
crates/provider/Cargo.toml
crates/rpc-types-beacon/Cargo.toml
crates/rpc-types-engine/Cargo.toml
crates/rpc-types-engine/src/cancun.rs
crates/rpc-types-engine/src/forkchoice.rs
crates/rpc-types-engine/src/identification.rs
crates/rpc-types-engine/src/jwt.rs
crates/rpc-types-engine/src/payload.rs
crates/rpc-types-engine/src/transition.rs

Replaces #1282 
Since `alloy-rpc-types-engine` doesn't depend on `alloy-rpc-types-eth`, we can split this out from `serde` feature support in `alloy-rpc-types-eth`.
This PR makes `serde` optional on the `alloy-rpc-types-engine` crate. Some JWT functionality now sits behind the `serde` feature flag since it uses `serde` internally for encoding/decoding. `serde` is also enabled-by-default.

feat(engine): Optional Serde

---

crates/rpc-types-eth/src/block.rs
crates/rpc-types-eth/src/simulate.rs

missing `serde(default)` + new aliases for block overrides fields to handle new names correctly on server side

fix: `eth_simulateV1`

---

scripts/check_no_std.sh

Adds `alloy-rpc-types-engine` to the `no_std` checks ci workflow.

chore(engine): `no_std` Checks

---

crates/contract/src/call.rs
crates/network/src/any/builder.rs
crates/network/src/ethereum/builder.rs
crates/network/src/lib.rs
crates/network/src/transaction/builder.rs
crates/network/src/transaction/mod.rs
crates/provider/src/builder.rs
crates/provider/src/fillers/gas.rs
crates/provider/src/fillers/mod.rs

Not all netwoks support 7702 and 4844 transactions, however, current network abstraction requires `TransactionRequest` to contain setters for both of those tx types. This results in custom network implementations either having no-op setters/getters on builders, or introducing additional fallible steps during transaction conversion pipeline to reject attempts to construct unsupported transactions.
Extracts part of `TransactionBuilder` methods into `TransactionBuilder4844` and `TransactionBuilder7702`. Extracts blob fee filling from `GasFiller` into `BlobGasFiller` which enforces `N::TxRequest: TransactionBuilder4844` bound.
Given that filling logic now depends on transaction request properties, I've extracted recomended fillers into `RecommendedFillers` trait which can be implemented on …

refactor: separate transaction builders for tx types

---

crates/node-bindings/src/nodes/anvil.rs
crates/node-bindings/src/nodes/geth.rs
crates/node-bindings/src/nodes/reth.rs

Currently, users cannot append any extra args to pass to `reth` or `geth`. We can only launch their respective instances with settings we have available in the builder api. 
Adds `args: Vec<OsString>` to both `Reth` and `Geth` that get appended to the `cmd` before spawning the instance.

feat(`node-bindings`): support appending extra args

---

crates/rpc-types-trace/src/geth/call.rs
crates/rpc-types-trace/src/geth/mod.rs

closes #1291
adds missing types, luckily the flatcallframe appears to be the same as parity's type

feat: add types for flat call tracer

---

crates/eips/src/eip4844/engine.rs
crates/eips/src/eip4844/mod.rs

ref https://github.com/paradigmxyz/reth/issues/10788

feat: add blob and proof v1

---

crates/eips/src/eip7002.rs
crates/rpc-types-beacon/src/relay.rs
crates/rpc-types-engine/src/payload.rs

Introduce `SignedBidSubmissionV4`.
Type reference: https://github.com/attestantio/go-builder-client/blob/e06dcb494024bf24ec7bd01299d226c578c97276/api/electra/submitblockrequest.go#L26-L32
SSZ reference: https://github.com/attestantio/go-eth2-client/blob/07eba3e76a14af9226495bdf4a571a5b0388bf88/spec/electra/executionpayload_ssz.go

feat(rpc-types-beacon): `SignedBidSubmissionV4`

---

crates/consensus/src/transaction/eip1559.rs
crates/consensus/src/transaction/eip2930.rs
crates/consensus/src/transaction/eip4844.rs
crates/consensus/src/transaction/eip7702.rs
crates/consensus/src/transaction/legacy.rs

Enforces that we only accept 0 or 1 as parity for typed transactions, and only 27, 28 or 35.. for legacy transactions
ref https://github.com/paradigmxyz/reth/pull/10758

fix: enforce correct parity encoding for typed transactions

---

crates/consensus/src/account.rs

This PR fixes #1312. See the issue for more context.
Add a custom `Default` implementation that corresponds to the valid empty account.

Implement custom default for `Account` representing a valid empty account

---

crates/rpc-types-beacon/src/relay.rs

I'd like to add support for `flashbots_validateBuilderSubmissionV3` to reth, but we need the `BuilderBlockValidationRequestV3` for the rpc request param.
This adds the aforementioned struct.  Note that the new struct does _not_ contain the `withdrawls_root` field present in `V2`.  I went through the latest flashbots/builder code and this parameter was [removed from the `V2` requests](https://github.com/flashbots/builder/blob/7577ac81da21e760ec6693637ce2a81fe58ac9f8/eth/block-validation/api.go#L159-L162), and is not present in `V3`:
https://github.com/flashbots/builder/blob/7577ac81da21e760ec6693637ce2a81fe58ac9f8/eth/block-validation/api.go#L198-L202
Furthermore the ultrasoundmoney implementation doesn't contain it either: https://github.com/ultrasoundmoney/reth-payload-validator/blob/main …

feat(rpc-types-beacon): `BuilderBlockValidationRequestV3`

---

crates/rpc-types-beacon/src/relay.rs

As suggested by @mattsse [here](https://github.com/alloy-rs/alloy/pull/1310#issuecomment-2360727290) this is a simple type alias for `BuilderBlockValidationRequestV4`.
I still think we should consider refactoring these structs to use an explicit versioned `ExecutionPayloadV*` instead of the enum, but I'm not sure how we feel about breaking compat on the V1 and V2 structs.
We could also move them from `::relay` to `::validation` to mirror the layout in reth: https://github.com/paradigmxyz/reth/blob/3daec1d9b97c2d654c7f84e8521ac552dcaf4928/crates/rpc/rpc-api/src/validation.rs
Anyways the type alias works for Pectra in the short-term, but happy to make the other changes if people are ok with that.

feat(rpc-types-beacon): `BuilderBlockValidationRequestV4`

---

crates/rpc-types-eth/src/simulate.rs

adds helper function to easily create a SimulatePayload request arg

feat: add builder style function to simulate payload args

---

crates/consensus/Cargo.toml
crates/consensus/src/lib.rs
crates/consensus/src/request.rs

It moves the `Requests` definition from reth to where `Request` is defined.
Related to: https://github.com/paradigmxyz/reth/issues/11082

feat(consensus): move requests struct definition from reth

---

crates/network-primitives/src/traits.rs
crates/rpc-types-eth/src/transaction/mod.rs

Closes https://github.com/alloy-rs/alloy/issues/1297
Adds getters into the `TransactionResponse` trait and updates implementations accordingly.

feat: Add getters into TransactionResponse and update implementations 

---

crates/consensus/src/header.rs
crates/consensus/src/lib.rs
crates/network/src/lib.rs

consensus: add `BlockHeader` getter trait

---

crates/rpc-types-eth/src/erc4337.rs

Factory and paymaster related fields don't need to be required, as it forces to pass some default value, i.e `null address` for `Address`, 0 for gas limits, etc. which leads to invalid user ops.
make factory and paymaster related fields optional

make factory and paymaster fields optional in `PackedUserOperation`

---

crates/provider/src/provider/root.rs
crates/provider/src/provider/trait.rs
crates/rpc-client/src/builtin.rs

Ref https://github.com/alloy-rs/alloy/pull/1321#discussion_r1769277823
Adds test to cover `BuiltinConnectionString.connect_boxed()`

fix(`rpc-client`): add test for BuiltInConnString.connect_boxed

---

Cargo.toml
crates/consensus/Cargo.toml

As per the `derive_more` documentation and specifically https://github.com/JelteF/derive_more?tab=readme-ov-file#installation, it seems that in last versions of Rust, to compile properly, we need to specify features to avoid errors of this type:
```shell
error[E0432]: unresolved imports `derive_more::Deref`, `derive_more::DerefMut`, `derive_more::From`, `derive_more::IntoIterator`
--> crates/consensus/src/request.rs:10:19
|
10  | use derive_more::{Deref, DerefMut, From, IntoIterator};
|                   ^^^^^  ^^^^^^^^  ^^^^  ^^^^^^^^^^^^ no `IntoIterator` in the root
|                   |      |         |
|                   |      |         no `From` in the root
|                   |      no `DerefMut` in the root
|                   no `Deref` in the root
```
Since we are using quite …

dep: add full feature to `derive_more`

---

crates/network-primitives/src/traits.rs
crates/provider/src/blocks.rs
crates/provider/src/ext/anvil.rs
crates/provider/src/heart.rs
crates/provider/src/lib.rs
crates/provider/src/provider/root.rs
crates/provider/src/provider/trait.rs
crates/pubsub/src/sub.rs
crates/rpc-client/src/builtin.rs
crates/rpc-client/src/client.rs
crates/rpc-client/src/poller.rs
crates/rpc-types-eth/src/block.rs

Ref https://github.com/alloy-rs/alloy/issues/1318

feat(provider): subscribe to new blocks if possible in heartbeat

---

crates/rpc-types-trace/src/geth/call.rs

this should be a vec of course because it's a flattened callframe..
ref https://github.com/paradigmxyz/reth/pull/11114

fix: use vec for flat call frame

---

crates/serde/src/num.rs
crates/serde/src/quantity.rs

There are binary formats such as bincode that care whether an `Option` is serialized using `serialize_some` or just `serialize`, because they prepend the enum variant of `Option` as a starting byte.
The tests were passing because JSON doesn't care about this.
Serialize `quantity::opt` as `Some` when the value is `Some`.

fix(serde): encode optional types as Some

---

crates/json-rpc/src/request.rs

feat: deserialize requests

---

crates/consensus/src/transaction/envelope.rs
crates/eips/src/eip2718.rs

`Eip2718Error` is just a more specific decoding error and it is useful to have an easy way to convert it to alloy-rlp error

feat: impl From<Eip2718Error> for alloy_rlp::Error

---

crates/consensus/src/transaction/envelope.rs

We did not include header length when calculating 2718 len for legacy transaction. This PR fixes this, refactors `rlp_payload_length` a bit and adds a test for legacy tx scenario

fix: correct `encode_2718_len` for legacy transactions

---

crates/consensus/src/transaction/envelope.rs
crates/eips/src/eip2718.rs

This PR makes `decode_2718` advance the buffer it receives. Right now we only advance it when decoding legacy transactions

fix: advance buffer during 2718 decoding
