crates/transport-http/src/hyper.rs
=> avoid allocation when convert Box<RawValue> into a hyper request

crates/providers/src/provider.rs
Since `T: Transport + Clone + Send + Sync`, then `Provider<T>` automaticlly implements `Sync`.
=> remove Sync constraint for provider

.github/workflows/ci.yml
=> ci: deploy documentation to GitHub Pages

.github/ISSUE_TEMPLATE/BUG-FORM.yml, .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
=> chore(meta): update ISSUE_TEMPLATE

crates/rpc-types/src/eth/call.rs
=> feat: improve CallInput

crates/providers/src/provider.rs, crates/rpc-types/src/eth/block.rs
=> chore: address provider review comments

crates/rpc-types/src/eth/transaction/mod.rs
=> Revert "fix: correct signature type for transaction rpc object"

crates/rpc-types/src/eth/log.rs
make it compatible with ethers
=> chore: make Log Default

Cargo.toml
=> chore(deps): unpatch core

crates/rpc-trace-types/Cargo.toml, crates/rpc-trace-types/README.md, crates/rpc-trace-types/src/lib.rs, crates/rpc-types/Cargo.toml
=> chore: cleanup rpc types

crates/json-rpc/src/packet.rs
=> chore: correct doc typo

crates/rpc-types/src/eth/mod.rs
Needed to be able to handle errors when converting alloy_rpc_types `Log` to alloy_primitives `LogData`
=> feat(rpc-types): expose LogError

Cargo.toml, crates/rpc-types/Cargo.toml
we have ssz support for various types 
https://github.com/alloy-rs/alloy/blob/80f42e3ebfa3afd12756b01627b92e564ee3cbfa/crates/rpc-types/src/eth/withdrawal.rs#L25-L25
=> chore: add back ssz feature

.github/ISSUE_TEMPLATE/BUG-FORM.yml
=> chore(`github`): add consensus component to bug report form

.github/ISSUE_TEMPLATE/BUG-FORM.yml, .github/ISSUE_TEMPLATE/FEATURE-FORM.yml, README.md, crates/consensus/README.md, crates/eips/README.md, crates/genesis/Cargo.toml, crates/genesis/README.md, crates/providers/README.md, crates/pubsub/README.md, crates/rpc-client/Cargo.toml, crates/rpc-client/README.md, crates/rpc-engine-types/Cargo.toml, crates/rpc-engine-types/README.md, crates/rpc-trace-types/Cargo.toml, crates/rpc-trace-types/README.md, crates/transport/Cargo.toml, crates/transport/README.md
=> docs: update descriptions and top level summary

crates/rpc-engine-types/Cargo.toml
=> fix: add ssz feature back to engine types

.config/nextest.toml, .github/workflows/ci.yml
Race conditions with Anvil port that I have no clue how to fix: <https://github.com/alloy-rs/alloy/actions/runs/7585493165/job/20661506007>
=> ci: use nextest as the test runner

crates/node-bindings/src/anvil.rs
should prevent flaky tests by letting the OS choose the port instead of the unused port hack
ref #134
=> fix: use port 0 for anvil by default

crates/json-rpc/src/request.rs, crates/pubsub/src/handle.rs, crates/pubsub/src/service.rs, crates/rpc-client/src/batch.rs, crates/rpc-trace-types/src/geth/pre_state.rs
=> perf: don't collect or try_for_each in pubsub code

crates/rpc-engine-types/src/payload.rs
Expose `prev_randao` on `ExecutionPayload`.
=> chore: expose prev randao on `ExecutionPayload`

crates/rpc-engine-types/src/payload.rs
=> chore: more execution payload getters

crates/signer/src/lib.rs, crates/signer/src/wallet/private_key.rs
Closes https://github.com/alloy-rs/alloy/issues/172
=> feat(signer): re-export k256, add `Wallet::from_bytes(B256)`

crates/rpc-trace-types/src/geth/pre_state.rs
=> docs: update PrestateMode docs

crates/rpc-types/src/eth/transaction/optimism.rs
Related to https://github.com/paradigmxyz/reth/issues/6547
=> fix: add deposit_receipt_version field in OptimismTransactionReceiptFields

crates/providers/src/provider.rs
This should be optional and default to latest.
Make it optional.
=> chore(`provider`): make `BlockId` opt on get_storage_at

crates/rpc-types/src/eth/transaction/request.rs
sanity test
https://github.com/paradigmxyz/reth/issues/6670
clippy unrelated
=> chore: add from to test

crates/json-rpc/src/response/error.rs
=> test: add deserde test for errorpayload with missing data

crates/rpc-trace-types/src/common.rs, crates/rpc-trace-types/src/geth/mod.rs
need to rename individually for untagged
=> fix: ensure camel case for untagged

crates/rpc-trace-types/src/lib.rs, crates/rpc-trace-types/src/opcode.rs
ref https://github.com/paradigmxyz/reth/issues/6421
@sslivkoff
=> feat: add types for opcode tracing

crates/rpc-types/src/eth/filter.rs
closes #256
cc @shekhirin
ref https://github.com/paradigmxyz/reth/pull/7060
=> chore: only accept required args

crates/providers/src/builder.rs, crates/providers/src/heart.rs, crates/providers/src/signer.rs
Progress towards enabling debug/copy lints
Add more debug/copy derives
=> chore: debug/copy/clone derives

crates/transport-ipc/src/connect.rs
Ref: #321 
Impl `new` method for `IpcConnect`.
=> add: `new` method to initialize IpcConnect

.github/workflows/ci.yml, Cargo.toml, README.md, crates/consensus/Cargo.toml, crates/contract/Cargo.toml, crates/eips/Cargo.toml, crates/genesis/Cargo.toml, crates/json-rpc/Cargo.toml, crates/node-bindings/Cargo.toml, crates/rpc-types/src/eth/transaction/error.rs, crates/serde/Cargo.toml, crates/signer/Cargo.toml, scripts/check_no_std.sh
Closes https://github.com/alloy-rs/alloy/issues/364
=> ci: check no_std in CI

crates/provider/src/provider.rs
Add missing fee functions:
ref https://ethereum.github.io/execution-apis/api-documentation/
=> feat: add eth_blobBaseFee and eth_maxPriorityFeePerGas

crates/eips/Cargo.toml, crates/eips/src/eip4844/env_settings.rs
Closes #384 
Move `MAINNET_KZG_TRUSTED_SETUP` from RETH to eip/4844.rs
=> mod: added MAINNET_KZG_TRUSTED_SETUP

crates/rpc-types/src/eth/call.rs
sanity tests for 
https://github.com/paradigmxyz/reth/issues/7349
=> test: add serde tests for eth_callMany

crates/network/src/ethereum/builder.rs
ref https://github.com/alloy-rs/alloy/issues/403
the versioned hashes can be automatically set if missing
separately, the default legacy fallback could use a few checks, because currently it's possible that we enter here even if other fields are set, for example sidecar present, missing blobfee
=> fix: automatically set blob versioned hashes if missing

crates/provider/src/builder.rs, crates/provider/src/layers/mod.rs, crates/provider/src/layers/nonce.rs
=> Rename `ManagedNonceLayer` to `NonceManagerLayer`

CONTRIBUTING.md, crates/contract/src/call.rs, crates/internal-test-utils/Cargo.toml, crates/internal-test-utils/src/providers.rs, crates/provider/Cargo.toml, crates/provider/src/builder.rs, crates/provider/src/layers/gas.rs, crates/provider/src/layers/nonce.rs, crates/provider/src/layers/signer.rs, crates/provider/src/lib.rs, crates/provider/src/provider.rs
=> feat: make HTTP provider optional

Cargo.toml, crates/contract/README.md, crates/contract/src/call.rs, crates/contract/src/event.rs, crates/contract/src/instance.rs, crates/contract/src/interface.rs, crates/contract/src/lib.rs, crates/provider/src/admin.rs, crates/provider/src/builder.rs, crates/provider/src/chain.rs, crates/provider/src/heart.rs, crates/provider/src/layers/gas.rs, crates/provider/src/layers/nonce.rs, crates/provider/src/layers/signer.rs, crates/provider/src/lib.rs, crates/provider/src/provider.rs
This PR defaults `Network` parameters to Ethereum in `alloy-provider` and `alloy-contract`.
From: https://github.com/alloy-rs/alloy/issues/263
=> feat: Default to Ethereum network in `alloy-provider` and `alloy-contract`

crates/rpc-types/src/eth/transaction/mod.rs
=> chore: export AnyReceiptEnvelope

crates/network/src/any/mod.rs
Uses `AnyReceiptEnvelope` in `AnyNetwork`
=> feat: use `AnyReceiptEnvelope` for `AnyNetwork`

crates/consensus/src/receipt/any.rs, crates/consensus/src/receipt/envelope.rs
adds a few more helper functions
cc @klkvr
=> feat: receipt qol functions

crates/rpc-types/src/eth/transaction/receipt.rs
adds a helper to convert the receipt type
=> feat: add map_inner

crates/eips/src/eip2930.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/eth/block.rs, crates/rpc-types/src/eth/transaction/mod.rs, crates/rpc-types/src/eth/transaction/signature.rs
- Derive `arbitrary` for `Header` and `Transaction` rpc types.
=> Derive arbitrary for rpc `Header` and `Transaction`

crates/provider/src/builder.rs, crates/rpc-client/src/builder.rs, crates/rpc-client/tests/it/http.rs
Closes #448 
Removed reqwest prefix. [`on_reqwest_http` to `on_http`]
=> Removed reqwest prefix

crates/rpc-types-engine/Cargo.toml, crates/rpc-types/Cargo.toml
unblocks
https://github.com/paradigmxyz/reth/pull/5894
=> chore: bump jsonrpsee 0.22

crates/eips/src/eip1559/basefee.rs
add the function to basefeeparams directly
=> chore: add helper for next block base fee

crates/rpc-types/src/eth/transaction/tx_type.rs
=> docs: update txtype docs

crates/rpc-types/src/eth/call.rs
ref https://github.com/paradigmxyz/reth/issues/7542
=> test: add bundle test

crates/rpc-types/src/eth/transaction/error.rs, crates/rpc-types/src/eth/transaction/mod.rs
4844 must have versioned hashes
=> feat: add missing blob versioned hashes error variant

crates/rpc-types/src/eth/transaction/error.rs
=> chore: reorder conversion error variants

crates/provider/src/provider.rs
Required for anvil tests migration in foundry.
Introduce `get_uncle_count` in `Provider`
=> feat(provider): get_uncle_count

crates/eips/src/eip1559/basefee.rs
makes creating constants easier
=> feat: add BaseFeeParams::new

crates/provider/src/debug.rs, crates/provider/src/lib.rs, crates/provider/src/provider.rs
closes #204. Unblock anvil tests migration in foundry.
Implemented as an extension trait on `Provider`
=> feat(provider): `debug_*` methods

crates/provider/src/debug.rs
fix conflict between #505 and #548
=> fix: conflict between to change and debug tests

crates/provider/src/fillers/nonce.rs, crates/provider/src/fillers/signer.rs
Unexpected behavior when both SignerFiller and NonceFiller are active causes nonces to not be filled properly, as from is unset. This kinda sucks
- SignerFiller sets from if from is unset
=> fix: signer fills from if unset

crates/eips/src/eip6110.rs, crates/rpc-types-engine/src/exit.rs, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload.rs
fix exitV1 type fields
also rename deposit to depositReceipt
=> fix: correct exitV1 type

crates/consensus/src/transaction/envelope.rs
Issue #572
Implement a getter method for the signed hash.
=> feat: add the txhash getter.

crates/rpc-client/src/call.rs
=> feat: bubble up set_subscription_status

crates/rpc-types/src/eth/transaction/error.rs
Add signature related `ConversionError` variants.
Related https://github.com/paradigmxyz/reth/pull/7752#discussion_r1572680180
=> Add signature related `ConversionError` variants

crates/rpc-types/src/eth/block.rs
=> feat: add Display for block hash or number

crates/contract/src/call.rs
Issue https://github.com/alloy-rs/alloy/issues/571
Add the set_sidecar method to the CallBuilder
=> feat: add set_sidecar to the callbuilder

crates/rpc-types-trace/src/filter.rs, crates/rpc-types-trace/src/geth/mod.rs
Issue #583 
Implement builder methods for all fields
=> feat: add builder methods

crates/provider/src/lib.rs
Expose enum `SendableTx` in provider crate.
=> Expose SendableTx in providers

crates/transport-ipc/src/lib.rs
closes https://github.com/alloy-rs/alloy/issues/607
=> chore: b'a'

crates/rpc-types/src/eth/transaction/request.rs
Fixes https://github.com/foundry-rs/foundry/issues/7739
=> fix: don't serialize nulls in tx request

crates/provider/src/heart.rs, crates/rpc-client/src/client.rs, crates/rpc-client/src/poller.rs
Closes #618
Update poll_interval to return Duration instead of u64
=> refactor: change u64 to Duration

crates/rpc-types-trace/src/parity.rs
Related https://eips.ethereum.org/EIPS/eip-3074
=> Add `AuthCall` variant to `CallType`

crates/alloy/src/lib.rs
https://github.com/alloy-rs/core/pull/615
=> docs: unhide `sol!` wrapper in meta crate

crates/alloy/Cargo.toml
This is needed for the example showing how to send a 4844 transaction using `SidecarBuilder`
Add `kzg` feature to alloy namespace
=> Enable kzg feature on consensus

README.md
=> fix(`README.md`): Add `alloy-signer-wallet` to crate list in readme

Cargo.toml
See issue https://github.com/alloy-rs/core/issues/617
=> Bump version of alloy core to 0.7.2 to incorporate sol macro cloning fix

crates/consensus/Cargo.toml, crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/eip4844/builder.rs, crates/consensus/src/transaction/envelope.rs, crates/eips/Cargo.toml, crates/eips/src/eip4844/mod.rs, crates/eips/src/eip4844/sidecar.rs
closes #402
* moved sidecar types to eips crate
* c-kzg conversion via trasmute, from_raw_parts where required
=> feat: use alloy types for BlobTransactionSidecar

crates/provider/src/provider/trait.rs
Doesn't map to primitive, results in deser error
Map to primitive `u128`
=> fix(provider): `get_blob_base_fee` map to primitive u128

crates/eips/src/eip4844/sidecar.rs
derives arbitrary
it would be better to implement all of this manually, but this would unblock
https://github.com/paradigmxyz/reth/issues/8081
tracking proper arbitrary impl here: #680
=> feat: derive arbitrary for BlobTransactionSidecar

crates/rpc-types-engine/src/payload.rs
#695 added all the util funcs but did not add the `From` impl
Add the `From` impl 🙃
=> chore: actually impl from for payload v4

crates/rpc-types/src/eth/other.rs
=> chore: collapse Debug for OtherFields

crates/eips/src/eip7002.rs
EIP-7002 encodes its requests using RLP.
Derive RLP for the request type.
=> feat: rlp for eip-7002 requests

crates/consensus/src/request.rs, crates/eips/src/eip7685.rs
this type should also be moved to eips
=> feat: rlp enc/dec for requests

crates/consensus/src/request.rs
everything in reth derives arbitrary
derive arbitrary for request
=> feat: derive arbitrary for `Request`

crates/consensus/src/request.rs
these are sent over engine api
derive serde
=> feat: serde for `Request`

crates/consensus/Cargo.toml, crates/consensus/src/request.rs
needed by reth
derive it for now but axe it later (why do we derive 2x arbitrary???) https://github.com/paradigmxyz/reth/issues/8209
=> feat: derive proptest arbitrary for `Request`

crates/rpc-types-engine/src/payload.rs
missing response value for getPayloadV4
=> feat: add payload envelope v4

crates/contract/src/call.rs, crates/provider/Cargo.toml, crates/provider/src/fillers/gas.rs, crates/provider/src/fillers/nonce.rs, crates/provider/src/lib.rs, crates/provider/src/provider/call.rs, crates/provider/src/provider/mod.rs, crates/provider/src/provider/trait.rs, crates/provider/src/provider/with_block.rs, crates/provider/src/utils.rs, crates/rpc-client/src/call.rs
followup to #645 
closes #613 
Generic builder struct for rpc calls that take optional block id parameters
=> RpcWithBlock

crates/rpc-types/src/eth/fee.rs
ref https://github.com/alloy-rs/alloy/issues/745
=> test: add another serde test for fee history

crates/eips/src/eip6110.rs
=> fix: serde rename camelcase

CONTRIBUTING.md
add section against typo farmers from foundry
=> docs: add section contributions related to spelling

crates/transport/src/common.rs
closes #771
include the auth token in the display impl
=> fix: include auth token in display

crates/rpc-types/src/eth/filter.rs
Followup to #784 
Seemed nice to be able to collect
Add a `FromIterator` impl
=> feat: fromiterator for filterset

crates/consensus/Cargo.toml, crates/consensus/src/lib.rs
accidentally got lost here https://github.com/alloy-rs/alloy/pull/708
=> fix: add request mod back

crates/eips/src/eip4844/sidecar.rs
=> fix: add proptest derives back

crates/consensus/src/account.rs
Added a test to encode & decode Account type
Added a test for trie hash slow function 
Added encode_to_vec function to encode the structure to a Vec<u8>
Closes https://github.com/alloy-rs/alloy/issues/800
=> Feat(consensus) Add test for account 

crates/contract/src/call.rs
Closes https://github.com/alloy-rs/alloy/issues/809
=> Feat(contract) : add reference to TransactionRequest type

crates/eips/src/eip2718.rs
=> [Fix] Mark `Eip2718Error` as `non_exhaustive`

crates/signer-wallet/Cargo.toml
Ran some tests, everything seems to work fine, the lib had mostly minor updates. Needed for upcoming Foundry PR
=> bump `coins-bip32` and `coins-bip39` deps

crates/provider/src/provider/trait.rs
Closes #269 
Reordered as per JSON-RPC spec, which follows the alphabetical order.
=> chore(provider): reorder methods in `Provider` trait

Cargo.toml, crates/alloy/Cargo.toml, crates/eips/Cargo.toml, crates/eips/src/eip1898.rs, crates/eips/src/eip2930.rs, crates/eips/src/eip4844/sidecar.rs, crates/eips/src/eip4895.rs, deny.toml
Closes #798 
Put tests behind the `serde` feature flag
=> chore(eips):  compile tests with default features

Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-eth/Cargo.toml, crates/signer-ledger/Cargo.toml, crates/transport-ws/Cargo.toml, crates/transport/src/common.rs
jsonrpsee bump required for https://github.com/paradigmxyz/reth/pull/7018
=> chore(deps): bump all

crates/rpc-types/src/lib.rs
For backwards compatibility, export types on `eth` namespace as well as directly in root.
=> fix(rpc-types): additionally export on `eth` namespace as well as *

crates/consensus/src/transaction/envelope.rs
adds some helper functions to check/access variants
=> feat: add as_ is_ functions to envelope

crates/network/src/any/builder.rs, crates/network/src/ethereum/builder.rs, crates/network/src/lib.rs, crates/network/src/transaction/builder.rs, crates/network/src/transaction/mod.rs, crates/network/src/transaction/signer.rs
closes #871
adds an error type for the tuple that includes the original request and the error
=> feat: add UnbuiltTransactionError type

crates/consensus/src/receipt/status.rs, crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/typed.rs, crates/json-rpc/src/common.rs, crates/json-rpc/src/packet.rs, crates/network/src/any/builder.rs, crates/network/src/ethereum/builder.rs, crates/provider/src/provider/trait.rs, crates/pubsub/src/managers/in_flight.rs, crates/rpc-types-engine/src/payload.rs, crates/serde/src/num.rs, crates/serde/src/quantity.rs
* same order as trait
* remove redundant `()`
* lift return
=> chore(clippy): apply lint suggestions

crates/provider/Cargo.toml
Can't run tests with rust-analyzer otherwise
=> test: add rand feature in providers

README.md
Closes https://github.com/alloy-rs/alloy/issues/909
=> docs: update MSRV policy

crates/consensus/CHANGELOG.md, crates/consensus/src/request.rs, crates/eips/src/eip7251.rs, crates/eips/src/lib.rs
=> feat: add eip-7251 consolidation request

.github/workflows/ci.yml
=> chore: don't self-host documentation anymore

crates/genesis/Cargo.toml, crates/genesis/src/lib.rs
Closes #932 
Uses `OtherFields` from `alloy-serde` instead of custom implementation
=> feat(genesis): update `extra_fields` to use `OtherFields`

crates/provider/src/provider/trait.rs
closes #937
outdated docs re blockid
=> docs: update get_balance docs

crates/eips/README.md
=> docs: update alloy-eips supported eip list

crates/consensus/src/request.rs
=> docs: copy/paste error of eip-7251 link

RELEASE_CHECKLIST.md
Closes https://github.com/alloy-rs/alloy/issues/935
=> docs: add release checklist

crates/rpc-types-mev/src/eth_calls.rs
Ref https://github.com/paradigmxyz/reth/issues/9027
=> dev(hotfix): typo change pub(crate) to pub

crates/rpc-types-eth/src/block.rs
adds an into iter functions for full transactions
=> feat: add into transactions iterator

crates/eips/src/eip7251.rs, crates/rpc-types-beacon/src/payload.rs, crates/rpc-types-engine/src/payload.rs
adds missing new consolidation requests field:
https://github.com/ethereum/execution-apis/blob/3ae3d29fc9900e5c48924c238dff7643fdc3680e/src/engine/prague.md#executionpayloadv4
=> feat: add consolidation requests to v4 payload

crates/rpc-types-engine/src/payload.rs
closes #886
adds missing type with new fields
https://github.com/ethereum/execution-apis/blob/3ae3d29fc9900e5c48924c238dff7643fdc3680e/src/engine/prague.md#executionpayloadbodyv2
=> feat: add execution payloadbodyv2

crates/eips/src/eip7702/auth_list.rs
ref https://github.com/paradigmxyz/reth/pull/9214
=> chore: add helper functions for destructuring auth types

crates/eips/src/eip7702/auth_list.rs
error from https://github.com/alloy-rs/alloy/actions/runs/9904006769/job/27360566257?pr=1043
```
Run cargo fmt --all --check
Diff in /home/runner/work/alloy/alloy/crates/eips/src/eip7702/auth_list.rs:13:
#[derive(Debug, Clone, Hash, RlpEncodable, RlpDecodable, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
-#[cfg_attr(
-    any(test, feature = "arbitrary"),
-    derive(arbitrary::Arbitrary)
-)]
+#[cfg_attr(any(test, feature = "arbitrary"), derive(arbitrary::Arbitrary))]
pub struct Authorization {
/// The chain ID of the authorization.
pub chain_id: ChainId,
Diff in /home/runner/work/alloy/alloy/crates/eips/src/eip7702/auth_list.rs:233:
/// The wrapper type is used for RLP encoding …
```
=> fix: cargo fmt

crates/signer-trezor/Cargo.toml
Likely resolves reported signing bug as reported in https://github.com/foundry-rs/foundry/issues/7660 + https://github.com/foundry-rs/foundry/issues/7342 
Related comment: https://github.com/foundry-rs/foundry/issues/7660#issuecomment-2169205625
Related fix / bug: https://github.com/trezor/trezor-firmware/pull/3952/files + https://github.com/trezor/trezor-firmware/pull/3952#issuecomment-2225060273
Bumps to `=0.1.4`
=> chore(deps): bump Trezor client to `=0.1.4` to fix signing bug

Cargo.toml
Update version of core libs to access the new features in latest release from alloy
Update version
=> feat(core): update core version

crates/rpc-types-eth/src/call.rs
useful for writing test & testing locally
=> feat(rpc-type-eth) convert vec TxReq to bundle

Cargo.toml
https://github.com/alloy-rs/alloy/pull/1101
=> chore: allow override all group

README.md, crates/network/src/lib.rs
Follow-up https://github.com/alloy-rs/alloy/pull/1101
=> chore: re-export and document network-primitives

crates/rpc-types-engine/src/payload.rs
Ref https://github.com/paradigmxyz/reth/pull/9993
=> feat(engine-types): `PayloadError::PrePragueBlockWithEip7702Transactions`

crates/rpc-types-eth/src/transaction/mod.rs, crates/rpc-types-eth/src/transaction/request.rs
closes https://github.com/alloy-rs/alloy/issues/1122
=> feat: add authorization list to TransactionRequest

crates/network/src/ethereum/builder.rs
this is kinda redundant, but for completeness
=> chore: add missing 7702 check

crates/consensus/src/transaction/eip1559.rs, crates/consensus/src/transaction/eip2930.rs, crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/eip7702.rs
This is needed to complete the following issue in reth: https://github.com/paradigmxyz/reth/issues/9484
=> feat: make signature methods generic over EncodableSignature

crates/eips/src/eip7702/auth_list.rs
Function doc for EIP-7702's `signature_hash` specified incorrect order of the fields
Fixed the doc
=> fix(doc): correct order of fields

crates/rpc-types/Cargo.toml
Include default features of engine types in rpc-types meta crate.
=> Export types engine default features

crates/consensus/src/transaction/envelope.rs
=> update TxType comment

crates/rpc-types-eth/src/transaction/optimism.rs
ref https://github.com/paradigmxyz/reth/issues/10462
=> fix: add missing op fields

crates/rpc-types-eth/src/transaction/optimism.rs
ref https://github.com/paradigmxyz/reth/issues/10463
add missing rpc field
=> chore: add deposit receipt version

.github/CODEOWNERS
=> Add emhane to codeowners

crates/provider/src/ext/txpool.rs, crates/rpc-types-trace/src/otterscan.rs, crates/rpc-types-txpool/src/txpool.rs
=> feat: add block and transaction generics to otterscan and txpool types

Cargo.toml, crates/alloy/Cargo.toml, crates/eips/Cargo.toml, crates/rpc-types-beacon/Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-eth/Cargo.toml, crates/rpc-types/Cargo.toml
Ref #1166 
Bump core to `0.8.0`, rm `ssz` feature from meta-crate.
=> chore: bump core and rm ssz feat

crates/network-primitives/src/traits.rs, crates/network/src/lib.rs, crates/provider/src/provider/trait.rs, crates/rpc-types-eth/src/block.rs
=> fix: make `Block::hash` required

README.md
The link to `alloy-rpc-types-debug` on README.md was not working
=> chore(README): Add a link to `rpc-types-debug`

crates/consensus/src/transaction/eip7702.rs
Related https://github.com/paradigmxyz/reth/issues/9484
=> eip7702: implement `tx_type` for `TxEip7702`

crates/consensus/src/transaction/eip7702.rs
Related https://github.com/alloy-rs/alloy/pull/1218#issuecomment-2320961010
=> eip7702: rm useless methods for `TxEip7702`

.github/workflows/no_std.yml
Adds a workflow to validate `no_std` compatibility for a matrix of crates. This should pass CI following #1222.
=> feat: workflow to validate no_std compatibility

crates/consensus/src/header.rs
Related https://github.com/paradigmxyz/reth/issues/10687 cc @mattsse
=> consensus: impl parent_num_hash for Header

crates/consensus/src/header.rs
Related https://github.com/paradigmxyz/reth/issues/10687 cc @mattsse
=> consensus: impl `is_zero_difficulty` for `Header`

crates/consensus/src/header.rs
Related https://github.com/paradigmxyz/reth/issues/10687 cc @mattsse
=> consensus: impl `exceeds_allowed_future_timestamp` for `Header`

crates/eips/src/eip1898.rs
Closes https://github.com/alloy-rs/alloy/issues/1206
Impl `Display` for `RpcBlockHash` and `BlockId`
=> chore(eip1898): display `RpcBlockHash`

crates/rpc-types-eth/src/lib.rs
Ref https://github.com/foundry-rs/foundry/pull/8771#discussion_r1746409228
Add type alias `AnyNetworkBlock` for `WithOtherFields<Block<WithOtherFields<Transaction>>>`
=> feat(rpc-types-eth): AnyBlock

crates/consensus/src/header.rs
Related https://github.com/paradigmxyz/reth/pull/10691
=> consensus: implement `AsRef` for `Header`

crates/node-bindings/src/nodes/anvil.rs
=> test: dont use fork test

crates/eips/src/eip1898.rs, crates/eips/src/lib.rs
closes #1264
ref https://github.com/alloy-rs/alloy/pull/1253#discussion_r1751059358
will do BlockHashOrNumber separately
=> chore: swap BlockNumHash alias and struct name

crates/consensus/src/header.rs, crates/consensus/src/lib.rs, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/eip1559.rs, crates/consensus/src/transaction/eip2930.rs, crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/eip7702.rs, crates/consensus/src/transaction/legacy.rs, crates/consensus/src/transaction/mod.rs
Unflags the feature around `extern crate alloc`.
=> chore(consensus): Alloc by Default

crates/eips/src/eip1898.rs, crates/eips/src/lib.rs
Related: #1266 
Reference: [1253 comment](https://github.com/alloy-rs/alloy/pull/1253#discussion_r1751059358)
=> chore: swap `BlockHashOrNumber` alias and struct name

crates/eips/src/eip1898.rs
ref https://github.com/alloy-rs/op-alloy/pull/91
=> feat: add serde for NumHash

crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/payload.rs
=> chore: remove eth rpc types dep from engine types

crates/rpc-types-engine/src/payload.rs
=> fix: add missing conversion

crates/provider/src/builder.rs, crates/provider/src/fillers/mod.rs
=> fix: RecommendedFillers typo

crates/provider/src/provider/trait.rs
add eth_simulateV1 to provider
=> feat: add eth_simulateV1

crates/rpc-types-mev/src/eth_calls.rs
=> feat: add builder style functions to ethcallbundle

crates/rpc-types-trace/src/otterscan.rs
Update to otterscan https://github.com/otterscan/otterscan/pull/2473
Adds `OperationType::OpEofCreate`
=> Add `OperationType::OpEofCreate`

crates/rpc-types-eth/src/filter.rs
=> rpc: remove repetitive as_ref

crates/rpc-types-debug/src/debug.rs
Return codes in ExecutionWitness
=> chore: add codes into execution witness

crates/consensus/src/header.rs
convenience function
cc @shekhirin
=> feat: add Header::num_hash_slow

crates/eips/src/eip2718.rs
ref https://github.com/alloy-rs/alloy/pull/1359#discussion_r1775369108 + clippy fix
=> fix: `Error::source` for `Eip2718Error`

crates/transport/src/error.rs
closes https://github.com/foundry-rs/foundry/issues/4894
=> test: add retry test

crates/consensus/src/transaction/eip1559.rs, crates/consensus/src/transaction/eip2930.rs, crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/eip7702.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/legacy.rs, crates/consensus/src/transaction/mod.rs, crates/consensus/src/transaction/typed.rs, crates/contract/src/call.rs, crates/genesis/src/lib.rs, crates/network-primitives/src/traits.rs, crates/network/src/any/builder.rs, crates/network/src/ethereum/builder.rs, crates/network/src/transaction/builder.rs, crates/provider/src/fillers/gas.rs, crates/provider/src/provider/trait.rs, crates/rpc-types-eth/src/transaction/mod.rs, crates/rpc-types-eth/src/transaction/request.rs, crates/signer-trezor/src/signer.rs
=> consensus: make `gas_limit` u64 for transactions

crates/rpc-types-debug/src/debug.rs
Update comments on fields to be more accurate
=> chore: Update comment to be more accurate

crates/provider/src/fillers/gas.rs
=> chore: move type def to where it belongs

crates/provider/Cargo.toml, crates/provider/src/builder.rs, crates/provider/src/fillers/wallet.rs
=> fix: set chain id for eth signer

crates/consensus/src/receipt/envelope.rs, crates/consensus/src/transaction/envelope.rs, crates/eips/src/eip2718.rs
closes https://github.com/alloy-rs/alloy/issues/1430
=> feat: `Encodable2718::network_len`

deny.toml
`foldhash` has a [Zlib license](https://github.com/orlp/foldhash?tab=Zlib-1-ov-file) which hasn't been explicitly allowed.
Allow zlib
=> chore(deny): allow Zlib

crates/rpc-types-engine/src/payload.rs
Add `Default` to payload id derive so `EthPayloadBuilderAttributes` can also be derived as well.
=> Add default to payload id

crates/alloy/Cargo.toml
Seems to be an oversight
This is a patch change
=> fix: enable serde on alloy-consensus

crates/consensus/src/receipt/mod.rs, crates/consensus/src/transaction/eip4844.rs
=> chore(consensus): test use Vec::with_capacity

crates/consensus/src/transaction/eip4844.rs
Split off from #1460 
Simple missing from impl
=> feat: From impl for variant

crates/serde/src/quantity.rs
prevents one recollect by using manual serde
=> perf: manual serde for quantity vec

crates/eips/src/eip7685.rs
closes https://github.com/alloy-rs/alloy/issues/1514
=> chore: add empty requests constant

crates/consensus/src/header.rs, crates/consensus/src/transaction/eip1559.rs, crates/consensus/src/transaction/legacy.rs
putting this below mod test is a bold choice
=> chore: reorder bincode modules

crates/rpc-types-eth/src/filter.rs
This is a successor of https://github.com/alloy-rs/alloy/pull/1342, thanks for @keefel, based on @keefel's codebase, add more testcases.
=> fix(filter): treat null fields as null

crates/rpc-types-engine/Cargo.toml
ref https://github.com/paradigmxyz/reth/pull/10616
=> fix: enable std with jwt

crates/rpc-types-beacon/src/relay.rs
actualize relay types based on https://github.com/flashbots/builder/blob/03ee71cf0a344397204f65ff6d3a917ee8e06724/eth/block-validation/api.go and https://github.com/flashbots/rbuilder/blob/7ff6fe15d0a108f16b2301fcc13e534d7fbd3967/crates/rbuilder/src/mev_boost/mod.rs
=> fix: relay types

crates/provider/src/provider/trait.rs
Closes #1585 
Instead of returning `Subscription<N::BlockResponse>` return `Subscription<N::HeaderResponse>`. Adjust tests accordingly.
=> fix(`provider`): return `Subscription<N::HeaderResponse>`

Cargo.toml
https://github.com/alloy-rs/alloy/pull/1581 requires a function added in 0.3.9.
=> chore(deps): bump alloy-rlp requirement

Cargo.toml
=> chore(deps): bump wasmtimer

crates/consensus/src/block/any.rs
=> feat: add impl From<Header> for AnyHeader

crates/rpc-types-trace/src/otterscan.rs
=> feat: make Otterscan types generic over header

crates/consensus/src/transaction/rlp.rs, crates/eips/src/eip4844/sidecar.rs
Add missing payload length checks
=> fix: add more rlp correctness checks

crates/rpc-types-trace/src/otterscan.rs
=> feat: make more Otterscan types generic over header

crates/consensus/src/transaction/envelope.rs
Expose signature on `TxEnvelope` type.
=> feat(consensus): `TxEnvelope::signature`

Cargo.toml, crates/rpc-types-eth/src/transaction/mod.rs
=> test: add test for 7702 with v

Cargo.toml, crates/consensus/Cargo.toml, crates/consensus/src/lib.rs, crates/consensus/src/proofs.rs
migrated from reth
will be integrated into BlockBody next
ref https://github.com/paradigmxyz/reth/issues/12519
cc @stevencartavia
=> chore: add some proof fns

.github/workflows/deps.yml
@prestwich gets too many emails
I will take on the burden of deps failure emails
=> chore(ci): edit cron syntax

.github/workflows/deps.yml, deny.toml
This will be reported on main or in a PR anyway.
=> ci: remove cron schedule for deps.yml

crates/consensus/src/block/header.rs
We have this for blob fee, makes sense to add for base fee as well
=> feat: add `next_block_base_fee` to `BlockHeader` trait

crates/rpc-types-eth/src/transaction/request.rs
ports this reth function
https://github.com/paradigmxyz/reth/blob/d51b347c8197a463cdcca49fa1a882c3c764135a/crates/rpc/rpc-types-compat/src/transaction.rs#L67-L67
=> feat: add helpers to initialize Tx request

crates/rpc-types-eth/src/transaction/request.rs
=> chore: move from impls to where they belong

crates/rpc-types-trace/src/opcode.rs
add some helpers to check if a block/tx contains an opcode
=> feat: add contains for opcodegas container

crates/eips/src/eip7685.rs
Fixes https://github.com/alloy-rs/alloy/issues/1694.
=> fix: use B256::new instead of from

crates/eips/src/eip7685.rs
Closes: https://github.com/alloy-rs/alloy/issues/1710
=> Update docs for eip7685 `Requests`

crates/rpc-types-engine/src/payload.rs
Addresses issue in the https://github.com/alloy-rs/alloy/issues/1722
I've gone with the first option and changed unwrap implementation to basic safe code
=> Change BlobsBundleV1Ssz unwrap implementation to safe code

release.toml
wasn't able to test it but it should ensure that owners are configured right
https://github.com/clap-rs/clap/blob/b4ea2d4be9f01b6c7945084cbd158d6075cf2408/release.toml#L1
=> chore: update release.toml

crates/consensus/src/receipt/receipts.rs
those are useful and we could reuse them in op-alloy https://github.com/alloy-rs/op-alloy/blob/3ee67a1e5a7c6cd56b564bf1828bcc0ce5ada2b8/crates/consensus/src/receipt/receipts.rs#L61
=> feat: make Receipt rlp methods pub

crates/provider/src/ext/debug.rs
Same as https://github.com/alloy-rs/alloy/issues/1738 but for debug_traceCall.
=> specialized geth tracer for debug trace call

crates/provider/src/ext/debug.rs
Fixes wrong types on debug_traceCall.
=> fix: wrong func sig

crates/consensus/src/block/header.rs
converts the `Header::is_empty` to a trait function
=> feat: move is_empty to trait function

crates/consensus/src/block/header.rs
=> feat: add `BlockHeader::blob_fee`

Cargo.toml, crates/genesis/Cargo.toml, crates/genesis/src/lib.rs
ported from reth
https://github.com/paradigmxyz/reth/blob/866d070c179656420623138bbfd123ed22f0cead/crates/trie/common/src/account.rs#L32-L49
=> feat: add TrieAccount conversion for genesis account

crates/rpc-types-eth/src/block.rs
Relaxes requirements for some of the helpers to construct blocks/headers
=> feat: relax RPC `Block` bounds

crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/version.rs
Introduces a forkchoice update version type.
Context: https://github.com/alloy-rs/op-alloy/pull/321#discussion_r1866125516
=> feat(engine): Forkchoice Version

Cargo.toml, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/pooled.rs, crates/rpc-types-eth/src/log.rs
=> fix: use asref impl for receipt

crates/consensus/src/transaction/eip1559.rs, crates/consensus/src/transaction/eip2930.rs, crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/eip7702.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/legacy.rs, crates/consensus/src/transaction/mod.rs, crates/consensus/src/transaction/typed.rs, crates/network/src/any/either.rs, crates/network/src/any/unknowns.rs, crates/rpc-types-eth/src/transaction/mod.rs, crates/rpc-types-eth/src/transaction/request.rs
Broke build due to stale branch.
=> Revert "feat(consensus): require typed2718 for transaction (#1746)"

crates/eips/src/eip1898.rs
=> chore: derive Copy for BlockWithParent

crates/consensus/src/transaction/envelope.rs
=> feat: add serde for `TxType`

crates/consensus/src/receipt/mod.rs
TIL `#[auto_impl(keep_default_for`
=> chore: add TxReceipt default helpers

crates/eips/src/eip4844/mod.rs, crates/eips/src/eip7691.rs
This should close [1725](https://github.com/alloy-rs/alloy/issues/1725)
=> calc_blob_gasprice made const

crates/consensus/src/transaction/recovered.rs
=> chore: add clone_tx

crates/consensus/src/block/mod.rs
=> feat: add some helper functions for blockbody

crates/eips/src/eip7685.rs
useful for
https://github.com/alloy-rs/alloy/pull/1787#discussion_r1884220073
=> feat: add requests with capacity

crates/rpc-types-debug/src/debug.rs
stray sentence
remove stray sentence
=> docs: remove stray sentence

crates/rpc-types-trace/src/parity.rs
=> fix: use default for creation method

crates/consensus/src/block/mod.rs
these are useful when dealing with iterators + map chains
=> feat: add helpers for block

crates/consensus-any/src/block/header.rs
adds convenience conversion fn
=> feat: add tryfrom for anyheader to header

crates/consensus/src/block/mod.rs
adds helpers to map the tx type
=> feat: add map transactions fn

Cargo.toml, crates/consensus/src/transaction/envelope.rs, crates/network/src/ethereum/builder.rs
Closes https://github.com/alloy-rs/alloy/issues/1829
=> EIP-7702: change `chain_id` type to `U256`

crates/consensus/src/block/mod.rs, crates/rpc-types-eth/src/block.rs
all of these should retire
https://github.com/paradigmxyz/reth/blob/ec21e895c10b5131e41113225c29789f816d118b/crates/primitives/src/alloy_compat.rs#L10-L10
=> chore: map header fns

crates/rpc-types-engine/src/payload.rs
#1851 followup for
https://github.com/paradigmxyz/reth/blob/d644900a8078db976cdbfb310a19df5df9b33125/crates/rpc/rpc-types-compat/src/engine/payload.rs#L95-L106
=> feat: add tryfrom payloadv2 + v3 for block

crates/consensus/Cargo.toml
this is cyclic dep and actually unused now
=> chore: rm unused alloy-signer dep

crates/signer/Cargo.toml, crates/signer/README.md, crates/signer/src/lib.rs
these are only used for docs, we can remove them if we only include the readme if no doctest
no idea why this does not work in ci
> error: couldn't read `crates/signer/src/../Readme.md`: No such file or directory (os error 2)
works locally
any ideas @DaniPopes 
EDIT: used rust,ignore instead
=> chore: rm cyclic test deps

crates/rpc-types-engine/src/payload.rs
gets rid of
https://github.com/paradigmxyz/reth/blob/b5536e4f2534b928254d10230f2b5cf1aa88f46a/crates/rpc/rpc-types-compat/src/engine/payload.rs#L118-L126
=> feat: add block to payloadbodyv1

crates/rpc-types-engine/src/payload.rs
https://github.com/paradigmxyz/reth/blob/b5536e4f2534b928254d10230f2b5cf1aa88f46a/crates/rpc/rpc-types-compat/src/engine/payload.rs#L52-L74
=> feat: add block to payloadv1

crates/rpc-types-engine/src/payload.rs
add conversion for ExecutionPayloadV2 and v3
=> feat: add additional conversion fn

crates/genesis/src/lib.rs
helper function to iterate over key,values
ref https://github.com/paradigmxyz/reth/blob/fc9d95a4d18978d7da649b1dcd53e69eef3d9a98/crates/storage/db-common/src/init.rs#L212-L224
=> chore: add storage_slots helper

crates/eips/src/eip4844/sidecar.rs
=> feat: add match_versioned_hashes

crates/eips/src/eip4844/sidecar.rs
#1882 followup 
fields are pub, uses .get to prevent outofbounds
=> chore: use safe get api 

crates/eips/src/eip1898.rs
=> chore: improve FromStr for `BlockNumberOrTag` to be case-insensitive

crates/provider/src/ext/debug.rs, crates/provider/src/ext/trace.rs, crates/provider/src/provider/trait.rs, crates/rpc-client/src/builtin.rs
Closes https://github.com/alloy-rs/alloy/issues/1894.
=> test: fix warnings on windows

crates/rpc-types-engine/src/payload.rs
=> feat: add missing conversion for ExecutionPayloadFieldV2

crates/eips/src/eip7840.rs, crates/genesis/src/lib.rs
With https://github.com/ethereum/EIPs/pull/9240 we can now unify those.
=> feat: unify `BlobParams` and `BlobScheduleItem`

crates/eips/src/eip1898.rs
=> test: migrate eip1898 tests

crates/consensus/src/transaction/recovered.rs, crates/rpc-types-eth/src/transaction/mod.rs
adds helpers to convert the wrapped tx
=> feat: add map fns to rpc transaction type

crates/eips/Cargo.toml
=> chore: forward arbitrary feature

crates/rpc-types-eth/src/erc4337.rs
adds missing helpers to check if any max parameter are exceeded
=> feat: add helpers for tx conditional

.config/zepter.yaml, .github/workflows/ci.yml, crates/consensus-any/Cargo.toml, crates/consensus/Cargo.toml, crates/eips/Cargo.toml, crates/genesis/Cargo.toml, crates/network-primitives/Cargo.toml, crates/rpc-types-beacon/Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-eth/Cargo.toml
adds zepter CI and propagate features
=> ci: add zepter and propagate features

crates/rpc-types-eth/src/transaction/request.rs
=> feat: add TxRequest::from_recovered_transaction helper

crates/rpc-types-engine/src/sidecar.rs
=> feat: add helpers to consume payloadfields

crates/rpc-types-engine/src/payload.rs
ported from reth
https://github.com/paradigmxyz/reth/blob/209b44829ee80a2e5a7b3e673c02b4fa1d81233e/crates/rpc/rpc-types-compat/src/engine/payload.rs#L29-L29
=> test: add payload block conversion tests

crates/rpc-types-engine/src/payload.rs
helper to create an empty blobsbundle
=> feat: add default for blobsbundle

crates/transport/src/layers/retry.rs
closes #1761
happens if cost > CU/S
=> fix: overflow on CU offset

crates/provider/src/lib.rs, crates/provider/src/provider/mod.rs, crates/provider/src/provider/sendable.rs
towards #793
this adds missing consuming conversions
=> feat: add helper fn to unwrap Sendable

crates/consensus/src/transaction/mod.rs
add helper that counts the versioned hashes
=> feat: add blob_count helper fn

crates/consensus/src/transaction/mod.rs
add convenience fn for # auths in a 7702
=> feat: add auth count helper fn

crates/rpc-types-eth/src/block.rs
adds helper function that can be useful if the Block is used as builder like type
=> feat: add Block::apply

crates/serde/src/other/mod.rs
makes it simpler to get mandatory fields
=> feat: add try_get_deserialized

crates/provider/src/layers/chain.rs
Noticed this was causing issues when playing around with `AnyNetwork`
=> fix: make `ChainLayer` network agnostic

crates/eips/src/eip4844/mod.rs
Closes #1907 
Supersedes #1912
Create a wrapper type `HeapBlob` over `Bytes`.
=> feat(`eip4844`): heap allocated blob

crates/consensus/src/block/mod.rs, crates/consensus/src/transaction/recovered.rs, crates/rpc-types-eth/src/block.rs
adds additional convert fns that map via `From/Into` TryFrom/Into
cc @cakevm
=> chore: additional From TryFrom conversion helpers

crates/consensus/src/error.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/pooled.rs
adds a fallible conversion from txenvelope to pooled
=> chore: add try_into_pooled conversion

crates/contract/src/error.rs
Ref https://github.com/alloy-rs/examples/issues/179
Add convenience fns to `alloy_contract::Error` to handle reverts easily.
=> feat(`contract`): handle reverts

crates/network/src/transaction/builder.rs
add fallible helper to builder
=> feat: add try_apply

crates/consensus/src/block/mod.rs, crates/consensus/src/block/traits.rs, crates/consensus/src/lib.rs
Closes #2033 
Unblocks #2032 
Introduce `BlockBodyT` and `BlockT`
=> feat(`consensus`): introduce block traits

crates/rpc-types-eth/src/transaction/request.rs
=> chore: smol typo

crates/transport-ws/src/native.rs
fixes #2067 
Missed Pong frame marks the connection as errored.
Not sure a test is required for this, not sure what test to write either. Let me know if one should be done and I'll think about it when I can.
=> fix: ws transport now checks for missed pongs within two pings

crates/rpc-types-engine/src/error.rs
Fixes #2081
Removed the error enum and ran the tests to check if it builds
=> Payload error removal

crates/eips/src/eip2718.rs
solve [#14634](https://github.com/paradigmxyz/reth/issues/14634)
=> Move WithEncoded helper type to alloy

crates/rpc-types-eth/src/block.rs
=> feat: add helper rpc to block body conversion

.github/workflows/ci.yml
=> ci: rm cc pin

crates/consensus/src/signed.rs, crates/consensus/src/transaction/envelope.rs, crates/rpc-types-eth/src/transaction/mod.rs
adds various helpers to convert from envelope -> Signed and for the rpc tx variant
=> feat: add more transaction conversion helpers

crates/rpc-types-engine/src/payload.rs
some helpers for https://github.com/paradigmxyz/reth/issues/14651
=> feat: add helper fn to execution data

crates/rpc-types-eth/src/state.rs
Ref #2105 
Create a `Builder` for `StateOverride`
Creates a struct called `StateOverridesBuilder` to make using `StateOverride` easier
=> feat: create StateOverridesBuilder

crates/provider/src/provider/trait.rs
A bug in reth is causing the `call_mainnet`  test to fail. Ref: https://github.com/paradigmxyz/reth/pull/14727
Switch to quicknode until fix has been released and node is updated.
=> chore(`provider`): use quicknode

crates/alloy/Cargo.toml
I was writing a basic script to create transaction, sign them and submit to a remote node. However, during the `send_raw_transaction` we need a rlp encoded transaction. I had to do the following:
```
alloy = { version = "0.11", features = ["full", "rlp"] }
```
I assume that `full` feature covers everything that is required for basic ethereum interaction and it appears `rlp` was missing in that. 
This PR simply adds `rlp` feature to the `full` feature.
=> add `rlp` feature to `full` feature

crates/provider/src/fillers/mod.rs, crates/provider/src/provider/erased.rs, crates/provider/src/provider/trait.rs
=> feat: add eth_sendRawTransactionConditional

crates/node-bindings/tests/it/reth.rs, crates/provider/src/ext/debug.rs, crates/provider/src/ext/trace.rs, crates/provider/src/provider/trait.rs, crates/rpc-client/src/builtin.rs
Closes https://github.com/alloy-rs/alloy/issues/1136
Plus adds some reasons to `#[ignore]`
=> test: enable more tests on windows

crates/provider/src/fillers/nonce.rs
Refs https://github.com/alloy-rs/alloy/issues/1507.
=> test: add a test for cloning CachedNonceManager

crates/consensus/src/transaction/typed.rs
=> feat: add signabletx impl for typedtx

crates/contract/src/call.rs, crates/contract/src/eth_call.rs, crates/provider/src/fillers/gas.rs, crates/provider/src/fillers/mod.rs, crates/provider/src/provider/erased.rs, crates/provider/src/provider/eth_call/caller.rs, crates/provider/src/provider/eth_call/mod.rs, crates/provider/src/provider/eth_call/params.rs, crates/provider/src/provider/multicall/mod.rs, crates/provider/src/provider/trait.rs
=> feat(`eth-call`)!: rm borrowing from provider api

.config/zepter.yaml, Cargo.toml, crates/consensus-any/Cargo.toml, crates/consensus/Cargo.toml, crates/eips/Cargo.toml, crates/genesis/Cargo.toml, crates/network-primitives/Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-eth/Cargo.toml
`--workspace` results in zepter not checking whether features are propagated to non-workspace deps
=> fix: run zepter checks for features of non-workspace dependencies

crates/contract/src/call.rs, crates/contract/src/eth_call.rs, crates/provider/src/provider/eth_call/mod.rs, crates/provider/src/provider/multicall/mod.rs, crates/rpc-types-eth/src/state.rs
this allows nicer ux via the builder type
=> chore!: use impl Into StateOverride

crates/provider/src/provider/get_block.rs, crates/rpc-types-eth/src/block.rs
Closes #2117 
Closes #2139 
- Add new variant `PendingBlock` for fetching pending blocks.
- Deser to `serde_json::Value` first
- Check if any of these fields are missing/null `hash`, `miner`, `nonce`.
- If yes, set them to their respective Zero types.
- Finally, Deser to `BlockResponse` from `Value` representation
=> fix(`provider`): custom deser for pending blocks

crates/network/src/any/either.rs, crates/network/src/any/mod.rs
one more tryfrom impl
will add a few more separately
=> chore: add any tx conversion

crates/contract/src/call.rs, crates/provider/src/provider/eth_call/mod.rs
Currently the result of `EthCall` is `Bytes` which is correct according to the spec.
Users would likely decode this into a `SolCall::Return` type.
- Adds a `decode_resp<S: SolCall>` convenience fn to decode the response `Bytes`.
=> feat(`provider`): `decode_resp` for `EthCall`

crates/network/src/any/either.rs, crates/network/src/any/mod.rs
more conversion dogfeeding
this changes the conversion slightly so that this enforces `TryFrom<Self>`
=> chore: change try into either

README.md
=> docs: bump version

Cargo.toml, crates/rpc-types-beacon/Cargo.toml, crates/rpc-types-beacon/src/relay.rs
Closes #1024 
- Add `tree_hash` and `tree_hash_derive` deps
- Derive `TreeHash` for `BidTrace` using `tree_hash_derive` when `"ssz"` feature is enabled
=> feat(`types-beacon`): derive `TreeHash` for `BidTrace`

crates/rpc-types-eth/src/state.rs
=> chore: add fromiter helper for stateoverridesbuilder

crates/contract/Cargo.toml, crates/contract/src/call.rs
Closes #793 
Adds the following methods to the `CallBuilder`
1. `build_unsigned_raw_transaction`
2. `build_raw_transactions`. Returns the signed 2718 representation
=> feat(`contract`): build signed and usigned txs from CallBuilder

Cargo.toml, crates/consensus/src/signed.rs
With https://github.com/matklad/once_cell/pull/275 we don't need the manual `Clone` impl
=> chore: bump once_cell

crates/consensus/src/transaction/envelope.rs
ref https://github.com/paradigmxyz/reth/issues/15012
=> feat: add missing U8 conversion

crates/provider/src/heart.rs, crates/provider/src/provider/root.rs
This is unused, and doesn't look like there are any observable side effects.
=> chore(provider): remove 'latest' channel from heartbeat

crates/eips/src/eip4844/engine.rs
Add`BlobAndProofV2`
Closes #2201 
Added `BlobAndProofV2` type
=> feat: add BlobAndProofV2

crates/consensus/src/transaction/recovered.rs
=> feat: derive `Serialize` and `Deserialize` for `Recovered<T>`

Cargo.toml, crates/node-bindings/Cargo.toml, crates/node-bindings/src/nodes/anvil.rs
Closes #1905 
- Adds `alloy-hardforks` dep: https://crates.io/crates/alloy-hardforks.
- Adds convenience fns to set the `--hardfork` flag in anvil using `EthereumHardfork`
=> feat(`node-bindings`): anvil typed hardforks

crates/consensus/src/constants.rs
New testnet, new genesis
add genesis hash from https://github.com/eth-clients/hoodi
=> feat(consensus): add hoodi genesis hash

crates/rpc-types-engine/src/payload.rs
=> feat: add BlobsBundleV2

crates/consensus/src/transaction/mod.rs
Because not long 1559 have max_fee and max_priority_fee, but also 4844 and 7702, so these comment should be updated
=> update tx fee comment about Transaction trait

crates/eips/src/eip7685.rs
https://github.com/paradigmxyz/reth/pull/15123
=> feat(eips): serde untagged for EIP-7685 `RequestsOrHash`

RELEASE_CHECKLIST.md
Closes https://github.com/alloy-rs/core/issues/740.
=> docs: suggest running cargo-semver-checks when releasing

crates/rpc-types-eth/src/filter.rs
This should add some more details for this [issue](https://github.com/alloy-rs/alloy/issues/2223)
closes #2223
=> Add more details on FilterSet

crates/eips/src/eip2718.rs
Add auto_impl(&) to Encodable2718 to avoid unnecessary clones. Link to [issues](https://github.com/alloy-rs/alloy/issues/2214).
=> auto_impl(&) for Encodable2718

crates/transport/src/error.rs
=> test: add test for 429 error message

crates/pubsub/src/managers/active_sub.rs
ref https://github.com/alloy-rs/alloy/pull/2222#discussion_r2008794034
thanks @DaniPopes
=> fix: use unwrap_or_else for subscribe

crates/provider/Cargo.toml, crates/provider/src/fillers/mod.rs, crates/provider/src/provider/erased.rs, crates/provider/src/provider/trait.rs
Closes #2235 
- Introduces `eth_signTransaction` to the provider trait
- Add to `FillProvider` and `DynProvider` impls
=> feat(`provider`): eth_signTransaction

crates/signer/src/error.rs
some convenience helper to configure a signer error with a message
=> chore: add error message helper

crates/rpc-types-eth/src/filter.rs
=> feat: make it easier to configure non u256 topics in filterset

crates/rpc-types-eth/src/filter.rs
helpers for impl FilterSet to insert new address, u256, bool
=> feat: filterset topics extend

crates/rpc-client/src/poller.rs
Updated in https://github.com/alloy-rs/alloy/pull/2197
=> docs: remove outdated doc on PollerBuilder

crates/rpc-client/src/poller.rs
Follow-up https://github.com/alloy-rs/alloy/pull/2267
I actually re-read the docs now
=> docs: update doc on PollerBuilder

crates/consensus/src/transaction/mod.rs, crates/consensus/src/transaction/typed.rs
=> feat: add bincode compat to eth typed tx

crates/consensus/src/transaction/envelope.rs
=> added TxType::is_eipxxx fxns

crates/contract/src/multicall.rs
this has been fixed on anvil
just updates the expected error
cc @DaniPopes
=> test: update error handling

crates/rpc-types-engine/src/payload.rs
Introduce `ExecutionPayloadEnvelopeV5`. See relevant links in the doc comments.
=> feat: `ExecutionPayloadEnvelopeV5`

crates/provider/src/fillers/nonce.rs
Add two new constructors to `NonceFiller`
- `NonceFiller::simple()`: Initializes the `SimpleNonceManager`
- `NonceFiller::cached()`: Initializes the `CachedNonceManager`
=> feat(`provider`): nonce filler helpers

crates/provider/src/fillers/mod.rs, crates/provider/src/provider/erased.rs, crates/provider/src/provider/trait.rs
=> feat: add eth get transaction by sender and nonce

crates/contract/src/multicall.rs, crates/node-bindings/src/nodes/anvil.rs, crates/provider/src/builder.rs, crates/provider/src/fillers/join_fill.rs, crates/provider/src/layers/anvil.rs, crates/provider/src/provider/trait.rs
Allows:
- calling the filler helper methods at any point of the builder
- using on_anvil* with any network
=> feat!: relax ProviderBuilder bounds

crates/consensus/src/transaction/envelope.rs
Hey @mattsse , do check this out once free!
This pr will close issue #2291
=>  Added Is_dyanamic_fee to TxType

crates/json-rpc/src/packet.rs
misc helpers for rpc data
cc @onbjerg
=> feat: add helpers for rpc types

crates/provider/src/heart.rs
=> chore: misc heartbeat

crates/json-rpc/src/packet.rs
=> feat: requestpacket helpers

crates/json-rpc/src/packet.rs
=> feat: more response packet helpers

crates/node-bindings/src/nodes/anvil.rs, crates/node-bindings/src/nodes/geth.rs
adds non consuming setters for args
=> feat: add mut arg setters for node bindings

crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/mod.rs
this mirros a constructor we have in reth rn, this prevents a lot of breaking changes
=> feat: add txenvelope helpers

crates/consensus/src/transaction/envelope.rs
=> chore: relax into typed fn

Cargo.toml
=> update gcloud-sdk to 0.27

crates/pubsub/src/frontend.rs, crates/pubsub/src/ix.rs, crates/pubsub/src/lib.rs, crates/pubsub/src/managers/in_flight.rs, crates/pubsub/src/managers/mod.rs, crates/pubsub/src/sub.rs
Closes https://github.com/alloy-rs/alloy/issues/2311
=> make PubSubFrontend new public

crates/json-rpc/src/response/payload.rs
=> chore: add try into success

crates/provider/src/builder.rs
=> chore: fix unused warnings

crates/transport-ws/src/native.rs, crates/transport-ws/src/wasm.rs
towards #2252 
- Make the URL field private
- Expose the URL string of the Websocket connection using a getter
=> feat(transport-ws): expose Ws url

crates/consensus/src/transaction/envelope.rs
required for https://github.com/paradigmxyz/reth/pull/15768
=> chore: more 4844 conversions

crates/rpc-types-eth/src/transaction/mod.rs
smol breaking change that slipped in in #2345 via copy paste
=> fix: use correct type in conversion

crates/rpc-types-eth/src/transaction/request.rs
Hey ! I found and fixed some duplicated words
=> deleted duplicate `for for` to `for` request.rs

crates/transport/Cargo.toml, crates/transport/src/dual.rs, crates/transport/src/lib.rs
=> feat: added DualTransport implementation that wraps two transport

crates/pubsub/README.md, crates/pubsub/src/sub.rs, crates/rpc-types-admin/src/admin.rs
`i1n` - `in`
`This/` - `This`
`identifier(also` - `identifier (also`
=> docs(refactor): minor corrections and cleanup

crates/consensus-any/src/receipt/envelope.rs, crates/consensus/src/receipt/receipts.rs
=> chore: add bloom_ref

crates/consensus/Cargo.toml, crates/consensus/src/crypto.rs
=> test: make test compile

crates/rpc-types-eth/src/transaction/request.rs
=> docs: add a note about transaction input

crates/rpc-types-beacon/src/relay.rs
add enum type for all available versions
=> chore: SubmitBlockRequest enum

crates/rpc-types-eth/src/transaction/request.rs
closes #2381
fyi @ratankaliani
=> feat: add input data helpers

crates/consensus/src/transaction/eip4844.rs, crates/contract/src/error.rs, crates/eips/src/eip7892.rs, crates/network/src/any/mod.rs, crates/provider/src/fillers/mod.rs, crates/provider/src/heart.rs
=> chore : fix typos

crates/provider/src/heart.rs
=> feat: add PendingTransactionBuilder::inspect

crates/provider/src/builder.rs, crates/provider/src/fillers/mod.rs, crates/provider/src/provider/erased.rs, crates/provider/src/provider/trait.rs, crates/rpc-types-eth/src/account.rs
Hello @mattsse , do check this pr out once free, it is for issue.
https://github.com/paradigmxyz/reth/issues/16027
=> Introducing eth_getAccountInfo

crates/provider/src/fillers/mod.rs, crates/transport/src/error.rs
Is this a good start @mattsse ?
Closes #2406
=> feat: Add fn `fill_envelope`

crates/network/src/ethereum/builder.rs, crates/rpc-types-eth/src/transaction/request.rs
closes https://github.com/foundry-rs/foundry/issues/9918
we need to ensure the to field is set
=> fix: ensure mandatory to field

crates/rpc-types-eth/src/filter.rs
we can keep these for a bit because this would otherwise cause additional friction in anvil
=> chore: add back filteredparams

crates/eips/src/eip7594.rs, crates/rpc-types-engine/src/payload.rs
Extracted from https://github.com/paradigmxyz/reth/pull/15534
Ref https://github.com/ethereum/consensus-specs/blob/9d377fd53d029536e57cfda1a4d2c700c59f86bf/specs/fulu/polynomial-commitments-sampling.md#cells
=> feat(eips): add more EIP-7594 constants

crates/eips/src/eip7840.rs, crates/eips/src/eip7892.rs
=> feat(eips): Osaka blob params

crates/eips/src/eip4844/sidecar.rs, crates/eips/src/eip7594/mod.rs, crates/eips/src/eip7594/sidecar.rs
Extracted from https://github.com/alloy-rs/alloy/pull/2273
Add `BlobTransactionSidecarEip7594`. Ref https://eips.ethereum.org/EIPS/eip-7594
=> feat(eips): `BlobTransactionSidecarEip7594`

crates/rpc-types-eth/src/transaction/request.rs
ref https://github.com/paradigmxyz/reth/pull/16182
=> feat: add helpers to check set fields

Cargo.toml, crates/provider/tests/it/ws.rs
=> chore: bump jsonrpsee

crates/consensus/src/crypto.rs
add a way to store source in recoveryerror
=> feat!: add source to recovery err

crates/provider/src/builder.rs, crates/rpc-client/Cargo.toml
=> chore: fix warnings

crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/eip4844_sidecar.rs, crates/eips/src/eip4844/sidecar.rs, crates/eips/src/eip7594/mod.rs, crates/eips/src/eip7594/rlp.rs, crates/eips/src/eip7594/sidecar.rs
Follow up to https://github.com/alloy-rs/alloy/pull/2434
Relax `TxEip4844WithSidecar` trait implementations.
=> feat(consensus): relax `TxEip4844WithSidecar` trait implementations

crates/rpc-types-eth/src/transaction/request.rs
we should check all fields here
=> chore: use has_eip4884 fields

crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/typed.rs
relax some conversions
fyi @rkrasiuk
=> chore: relax some conversions

crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/envelope.rs
Relax creation of 4844 transaction with sidecar.
=> chore(consensus): relax 4844 with sidecar creation

crates/rpc-types-beacon/src/relay.rs
=> feat: add ProposerPayloadDelivered

crates/rpc-types-beacon/src/relay.rs
=> feat: add BuilderBlockReceived

crates/consensus/src/transaction/recovered.rs
=> impl: SignerRecoverable for WithEncoded<T>

crates/provider/src/blocks.rs
The way `into_subscription_stream` is implemented right now does not work because it expects entire blocks as `newHeads` items while they are actually just headers. This results in heartbeat never actually handling any confirmed transactions if used with a ws provider
=> fix: correctly handle websocket subscription to new blocks

crates/rpc-types-eth/src/block.rs
@mattsse @yash-atreya !! resolves #2487
=> feat: Introducing builder fn for BlockOverrides

crates/network/src/any/builder.rs, crates/network/src/ethereum/builder.rs, crates/network/src/transaction/builder.rs
=> chore: impl set_input_kind for anytxrequest

crates/consensus/src/extended.rs, crates/consensus/src/lib.rs
ref https://github.com/paradigmxyz/reth/issues/16411
Move `Extended` type from Reth to Alloy
=> feat: add Extended type with alloy trait impls

crates/consensus-any/Cargo.toml, crates/consensus-any/src/block/header.rs, crates/consensus-any/src/lib.rs, crates/serde/src/lib.rs
=> chore: handle tron '0x' stateRoot as zero

crates/rpc-types-trace/src/parity.rs
ported from
https://github.com/foundry-rs/foundry/blob/7fba3dd72419698d044bf582045563a5157c39f7/crates/anvil/src/eth/otterscan/api.rs#L29-L45
=> feat: add trace helper fns

crates/rpc-types-trace/src/otterscan.rs
ported from
https://github.com/foundry-rs/foundry/blob/7fba3dd72419698d044bf582045563a5157c39f7/crates/anvil/src/eth/otterscan/api.rs#L50-L50
=> chore: add trace entry helper

crates/provider/src/provider/multicall/mod.rs
This should fix [2476](https://github.com/alloy-rs/alloy/issues/2476)
=> feat: empty MulticallBuilder into dynamic

crates/rpc-types-eth/src/transaction/mod.rs
=> chore: generalize rpc tx type conversions

crates/rpc-types-eth/src/block.rs
=> feat: add missing from impl

crates/eips/src/eip4844/env_settings.rs, crates/eips/src/eip4844/sidecar.rs
some relevant docs about default kzg settings
=> docs: add some kzgsettings docs

crates/eips/src/eip1898.rs
need for https://github.com/paradigmxyz/reth/pull/16378
=> chore: add serialize impl

crates/rpc-types-beacon/src/lib.rs, crates/rpc-types-beacon/src/node.rs
some types for
https://ethereum.github.io/beacon-APIs/#/Node
=> feat: add some node types from beacon api

crates/rpc-types-trace/src/otterscan.rs
this way we can get rid of this hack entirely:
https://github.com/paradigmxyz/reth/blob/9089672839a7275c11a77408d3270f786437ff3f/crates/rpc/rpc-types-compat/src/transaction.rs#L45-L48
this introduces some overhead but imo this is still better than offloading this to the user
=> chore: truncate input data for ots block on serialize

crates/network-primitives/Cargo.toml, crates/network-primitives/src/block.rs, crates/rpc-types-eth/Cargo.toml
=> feat: introduce serde feature for network-primitives

crates/rpc-types-eth/src/block.rs
add more convenience functions
=> feat: add additional qol block functions

crates/rpc-types-beacon/src/node.rs
closes #2528 
@mattsse do check this out , maybe can improve on naming convention, if needed , ping me few suggestions!
=> feat: Introducing eth/v1/node types

Cargo.toml, crates/rpc-types-eth/src/log.rs
NOTE: This should be merged only after https://github.com/alloy-rs/core/pull/957 + we need to update crates before merging
Related to https://github.com/alloy-rs/core/issues/955
There was no way to decode log with validation
Added `log_decode_validate` method
=> feat: added `log_decode_validate` method

crates/consensus/src/extended.rs
=> docs: fix typo in comment

crates/consensus/src/transaction/mod.rs
just improve comment section :)
=> chore: fix typo in comment [crates/consensus/src/transaction/mod.rs]

crates/rpc-types-eth/src/transaction/mod.rs
=> fix: move `Transaction::from_transaction`

crates/eips/src/eip2718.rs, crates/rpc-types-engine/src/payload.rs
=> feat: added convinient fn decode_2718_exact

crates/rpc-types-eth/src/filter.rs
ports 
https://github.com/paradigmxyz/reth/blob/7e9f1416047f1dc803a366661a561c1e1b9abd2d/crates/rpc/rpc-eth-types/src/logs_utils.rs#L16-L56
as a new util fn on Filter
=> feat: add log filtering methods to Filter

crates/rpc-types-engine/src/payload.rs
=> chore: remove basefee check from try_into_block

crates/consensus/src/signed.rs
we actually need to encode into the buf
=> fix: encode into buf

crates/consensus/src/crypto.rs
=> feat: add dedicated error for SECP256K1N_HALF error

crates/rpc-types-engine/src/payload.rs
ported from
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc/src/validation.rs#L350-L362
=> feat: add helper conversion for blobsbundlev1

crates/rpc-types-engine/src/payload.rs
same as https://github.com/alloy-rs/alloy/pull/2639
cc @varun-doshi we need this one later
=> chore: add try_into_sidecar helper

crates/node-bindings/src/nodes/anvil.rs
closes #2625
we could likely make this cross platform by dealing with sysinfo or smth but since this is mostly used on unix this should be fine, until there's a request for this
=> fix: kill anvil with sigterm

crates/consensus/src/receipt/mod.rs
=> chore: add into_with_bloom_unchecked

crates/consensus/src/transaction/eip4844.rs
a few helpers for accessing sidecar
=> feat: add sidecar helpers

crates/eips/src/eip4844/sidecar.rs, crates/eips/src/eip7594/sidecar.rs
=> chore: sidecar helper fns

crates/rpc-types-eth/src/log.rs
smol helper for collecting all rpc logs in a block:
https://github.com/paradigmxyz/reth/blob/b9c63f6a10bfbf89b7b3585acf34750d3dbf7493/crates/rpc/rpc-eth-types/src/receipt.rs#L51-L65
cc @lean-apple
=> chore: add helper to collect rpc logs

crates/provider/src/ext/mev/mod.rs
Implement the the method for `eth_sendPrivateRawTransaction`. This is a bit different and does not has just use the json payload as the other methods, since we we have `[tx_bytes, preferences]`. I used the same approach to serializing the tx bytes, as used in `send_raw_transaction`. 
The return is "officially" required, but since I like to keep it similar to the `send_private_transaction` (e.g. titan is not returning anything) it is `Option<TxHash>`. https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint#eth_sendprivaterawtransaction
=> feat(mev): implement `send_private_raw_transaction` method

crates/provider/src/provider/multicall/inner_types.rs, crates/provider/src/provider/multicall/tuple.rs
Fixes https://github.com/alloy-rs/alloy/issues/2704
```rust
If res.success == true
``` 
check: 
```rust
if res.returnData is empty.
```
=> fix: return abi decoding errors as multicall failures

crates/rpc-types-debug/Cargo.toml, crates/rpc-types-debug/src/debug.rs
ref [#17615](https://github.com/paradigmxyz/reth/pull/17615)
=> feat: added type for debug_storageRangeAt

crates/provider/src/provider/get_block.rs
from deserilization to deserialization
=> fix: typo in code comment

crates/json-rpc/src/result.rs, crates/rpc-client/src/call.rs, crates/transport-http/src/hyper_transport.rs, crates/transport-http/src/reqwest_transport.rs
Reduce logs in RpcCall and http transports
=> chore: reduce logs for requests

crates/rpc-types-beacon/src/payload.rs
make clippy happy
Remove `BeaconOptimismPayloadAttributes`
=> chore: remove `BeaconOptimismPayloadAttributes`

crates/eips/src/eip4844/mod.rs
`fake_exponential` function, used to calculate blob gas prices per EIP-4844, would panic on arithmetic overflow when `numerator_accum * numerator` exceeded `u128::MAX`. This occurs when processing blocks with intentionally invalid excess blob gas values near `u64::MAX`.
Added overflow protection using `checked_mul()` to handle multiplication overflow by breaking the loop early instead of panicking.
=> fix(eip4844): prevent overflow panic in fake_exponential with large excess blob gas

crates/eips/src/eip7840.rs, crates/genesis/src/lib.rs
=> feat: apply osaka values in `ChainConfig::blob_schedule_blob_params`

crates/signer-local/src/mnemonic.rs
=> feat: add helpers for MnemonicBuilder

crates/consensus/src/transaction/recovered.rs, crates/eips/src/eip2718.rs
https://github.com/alloy-rs/evm/pull/163#pullrequestreview-3163487834
=> feat: add Asref for recovered withencoded

crates/provider/src/layers/batch.rs, crates/provider/src/provider/multicall/bindings.rs, crates/provider/src/provider/multicall/mod.rs
=> return correct arbitrum block numbers w/ BatchLayer

crates/rpc-types-trace/src/geth/call.rs
=> chore: use quantity for index

crates/rpc-types-beacon/Cargo.toml, crates/rpc-types-beacon/src/payload.rs
smol helper to directly deserde the EL format from CL input
=> feat: add helper json deserde fn

crates/rpc-types-eth/src/error.rs
Adds missing RPC error code 4 for timeout of `eth_sendRawTransactionSync`
=> fix(rpc): Add missing error code `eth_sendRawTransactionSync` timeout

crates/contract/Cargo.toml, crates/contract/src/storage_slot.rs
allows overriding the request object fields
=> feat: add with_request to storage slot finder

crates/json-rpc/src/response/error.rs
closes https://github.com/ithacaxyz/relay/issues/1352
=> chore: treat 1008 rpc error as retryable

crates/consensus/src/transaction/eip1559.rs, crates/consensus/src/transaction/eip4844.rs, crates/consensus/src/transaction/eip7702.rs, crates/eips/src/eip1559/helpers.rs, crates/eips/src/eip1559/mod.rs, crates/network/src/any/unknowns.rs
Moved the duplicate `effective_gas_price` calculation logic from multiple transaction implementations into a single reusable function in the eips/eip1559/helpers module. This eliminates code duplication across TxEip1559, TxEip4844, TxEip7702, and UnknownTypedTransaction implementations.
The consolidated function `calc_effective_gas_price` handles the EIP-1559 calculation logic:
- Returns max_fee_per_gas when no base fee exists
- When base fee exists, calculates the tip and ensures it doesn't exceed max_priority_fee_per_gas
- Maintains the same behavior as the original implementations
All existing tests pass without modification.
=> refactor: consolidate effective gas price calculation into eip1559 module

Cargo.toml, crates/tx-macros/src/serde.rs
alloy-consensus does not compile with latest serde because of a breaking change to private types we rely on https://github.com/serde-rs/serde/pull/2976
Fixes #2876.
=> fix: compilation issues

.github/dependabot.yml, .github/workflows/ci.yml
Hardens permissions in the CI, adds dependabot to manage pinned hashes on a weekly basis
=> chore(`ci`): harden ci + add dependabot for managing pinned hashes

Cargo.toml, crates/tx-macros/src/serde.rs
we need a long term solution for this
=> chore: bump serde 226

crates/rpc-types-beacon/src/payload.rs
To help for https://github.com/foundry-rs/foundry/pull/11629.
Addressing this comment https://github.com/foundry-rs/foundry/pull/11629#discussion_r2344019915.
Add the different structs to help for deserializing the beacon block into an execution payload.
=> feat(rpc-types-beacon): add `BeaconBlockData` conversion to execution payload

crates/consensus/src/transaction/pooled.rs, crates/consensus/src/transaction/rlp.rs
=> chore: fix a couple of grammatical errors

crates/node-bindings/src/nodes/anvil.rs, crates/transport/src/layers/fallback.rs
Unifies tracing target namespaces to match subsystem ownership (node vs transport), improving log filtering and taxonomy consistency.
=> chore: Align tracing targets

.github/CODEOWNERS
=> chore(meta): add onbjerg + zerosnacks, remove yash as a code owner
